// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Management / introspection RPCs on the multigateway. These are intended for
// multiadmin to drive per-gateway debug pages — the gateway-to-gateway query
// cancellation API lives separately on MultigatewayService.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: multigatewaymanagerservice.proto

package multigatewaymanagerconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	multigatewaymanager "github.com/multigres/multigres/go/pb/multigatewaymanager"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MultigatewayManagerName is the fully-qualified name of the MultigatewayManager service.
	MultigatewayManagerName = "multigatewaymanager.MultigatewayManager"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MultigatewayManagerGetQueryRegistryProcedure is the fully-qualified name of the
	// MultigatewayManager's GetQueryRegistry RPC.
	MultigatewayManagerGetQueryRegistryProcedure = "/multigatewaymanager.MultigatewayManager/GetQueryRegistry"
	// MultigatewayManagerGetConsolidatorStatsProcedure is the fully-qualified name of the
	// MultigatewayManager's GetConsolidatorStats RPC.
	MultigatewayManagerGetConsolidatorStatsProcedure = "/multigatewaymanager.MultigatewayManager/GetConsolidatorStats"
)

// MultigatewayManagerClient is a client for the multigatewaymanager.MultigatewayManager service.
type MultigatewayManagerClient interface {
	// GetQueryRegistry returns the per-fingerprint query registry snapshot,
	// including rolling trend samples for sparkline rendering.
	GetQueryRegistry(context.Context, *connect.Request[multigatewaymanager.GetQueryRegistryRequest]) (*connect.Response[multigatewaymanager.GetQueryRegistryResponse], error)
	// GetConsolidatorStats returns a snapshot of the prepared-statement
	// consolidator.
	GetConsolidatorStats(context.Context, *connect.Request[multigatewaymanager.GetConsolidatorStatsRequest]) (*connect.Response[multigatewaymanager.GetConsolidatorStatsResponse], error)
}

// NewMultigatewayManagerClient constructs a client for the multigatewaymanager.MultigatewayManager
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMultigatewayManagerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MultigatewayManagerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	multigatewayManagerMethods := multigatewaymanager.File_multigatewaymanagerservice_proto.Services().ByName("MultigatewayManager").Methods()
	return &multigatewayManagerClient{
		getQueryRegistry: connect.NewClient[multigatewaymanager.GetQueryRegistryRequest, multigatewaymanager.GetQueryRegistryResponse](
			httpClient,
			baseURL+MultigatewayManagerGetQueryRegistryProcedure,
			connect.WithSchema(multigatewayManagerMethods.ByName("GetQueryRegistry")),
			connect.WithClientOptions(opts...),
		),
		getConsolidatorStats: connect.NewClient[multigatewaymanager.GetConsolidatorStatsRequest, multigatewaymanager.GetConsolidatorStatsResponse](
			httpClient,
			baseURL+MultigatewayManagerGetConsolidatorStatsProcedure,
			connect.WithSchema(multigatewayManagerMethods.ByName("GetConsolidatorStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// multigatewayManagerClient implements MultigatewayManagerClient.
type multigatewayManagerClient struct {
	getQueryRegistry     *connect.Client[multigatewaymanager.GetQueryRegistryRequest, multigatewaymanager.GetQueryRegistryResponse]
	getConsolidatorStats *connect.Client[multigatewaymanager.GetConsolidatorStatsRequest, multigatewaymanager.GetConsolidatorStatsResponse]
}

// GetQueryRegistry calls multigatewaymanager.MultigatewayManager.GetQueryRegistry.
func (c *multigatewayManagerClient) GetQueryRegistry(ctx context.Context, req *connect.Request[multigatewaymanager.GetQueryRegistryRequest]) (*connect.Response[multigatewaymanager.GetQueryRegistryResponse], error) {
	return c.getQueryRegistry.CallUnary(ctx, req)
}

// GetConsolidatorStats calls multigatewaymanager.MultigatewayManager.GetConsolidatorStats.
func (c *multigatewayManagerClient) GetConsolidatorStats(ctx context.Context, req *connect.Request[multigatewaymanager.GetConsolidatorStatsRequest]) (*connect.Response[multigatewaymanager.GetConsolidatorStatsResponse], error) {
	return c.getConsolidatorStats.CallUnary(ctx, req)
}

// MultigatewayManagerHandler is an implementation of the multigatewaymanager.MultigatewayManager
// service.
type MultigatewayManagerHandler interface {
	// GetQueryRegistry returns the per-fingerprint query registry snapshot,
	// including rolling trend samples for sparkline rendering.
	GetQueryRegistry(context.Context, *connect.Request[multigatewaymanager.GetQueryRegistryRequest]) (*connect.Response[multigatewaymanager.GetQueryRegistryResponse], error)
	// GetConsolidatorStats returns a snapshot of the prepared-statement
	// consolidator.
	GetConsolidatorStats(context.Context, *connect.Request[multigatewaymanager.GetConsolidatorStatsRequest]) (*connect.Response[multigatewaymanager.GetConsolidatorStatsResponse], error)
}

// NewMultigatewayManagerHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMultigatewayManagerHandler(svc MultigatewayManagerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	multigatewayManagerMethods := multigatewaymanager.File_multigatewaymanagerservice_proto.Services().ByName("MultigatewayManager").Methods()
	multigatewayManagerGetQueryRegistryHandler := connect.NewUnaryHandler(
		MultigatewayManagerGetQueryRegistryProcedure,
		svc.GetQueryRegistry,
		connect.WithSchema(multigatewayManagerMethods.ByName("GetQueryRegistry")),
		connect.WithHandlerOptions(opts...),
	)
	multigatewayManagerGetConsolidatorStatsHandler := connect.NewUnaryHandler(
		MultigatewayManagerGetConsolidatorStatsProcedure,
		svc.GetConsolidatorStats,
		connect.WithSchema(multigatewayManagerMethods.ByName("GetConsolidatorStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/multigatewaymanager.MultigatewayManager/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MultigatewayManagerGetQueryRegistryProcedure:
			multigatewayManagerGetQueryRegistryHandler.ServeHTTP(w, r)
		case MultigatewayManagerGetConsolidatorStatsProcedure:
			multigatewayManagerGetConsolidatorStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMultigatewayManagerHandler returns CodeUnimplemented from all methods.
type UnimplementedMultigatewayManagerHandler struct{}

func (UnimplementedMultigatewayManagerHandler) GetQueryRegistry(context.Context, *connect.Request[multigatewaymanager.GetQueryRegistryRequest]) (*connect.Response[multigatewaymanager.GetQueryRegistryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multigatewaymanager.MultigatewayManager.GetQueryRegistry is not implemented"))
}

func (UnimplementedMultigatewayManagerHandler) GetConsolidatorStats(context.Context, *connect.Request[multigatewaymanager.GetConsolidatorStatsRequest]) (*connect.Response[multigatewaymanager.GetConsolidatorStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multigatewaymanager.MultigatewayManager.GetConsolidatorStats is not implemented"))
}
