//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains data structures for query results in Multigres.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: query.proto

package query

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode is what the caller wants from a query, expressed as a writability /
// consistency constraint. The gateway translates this into a specific pooler
// at routing time based on current consensus state.
//
// Why a mode rather than a pooler-type axis: callers care about "can I
// write?" and "is the read consistent?", not about which fleet (PRIMARY vs
// REPLICA) the underlying pooler belongs to. Decoupling lets the gateway
// take advantage of cluster shape — e.g. routing CONSISTENT reads to a
// caught-up sync standby — without callers having to know.
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	// WRITABLE: must be the consensus leader. Reads here are also strongly
	// consistent. This is the only mode that accepts writes.
	Mode_MODE_WRITABLE Mode = 1
	// CONSISTENT: a read that must reflect all completed writes. Today this
	// resolves to "leader in read-only mode" — the gateway routes to the
	// leader and the pooler rejects DDL/DML server-side. Future routing
	// work may downgrade to a sync standby caught up to the leader's LSN
	// without changing this API contract.
	Mode_MODE_CONSISTENT Mode = 2
	// INCONSISTENT: any healthy follower within the configured lag
	// tolerance, falling back to the leader if none qualify. Cheapest
	// option; reads may be stale.
	Mode_MODE_INCONSISTENT Mode = 3
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_WRITABLE",
		2: "MODE_CONSISTENT",
		3: "MODE_INCONSISTENT",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED":  0,
		"MODE_WRITABLE":     1,
		"MODE_CONSISTENT":   2,
		"MODE_INCONSISTENT": 3,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

// QueryResultPayload is a union type for streaming query results.
// Each stream item is either row data OR a diagnostic (error/notice).
// This enables zero-buffering notice delivery during query execution.
type QueryResultPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*QueryResultPayload_Result
	//	*QueryResultPayload_Diagnostic
	//	*QueryResultPayload_Notification
	Payload       isQueryResultPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultPayload) Reset() {
	*x = QueryResultPayload{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultPayload) ProtoMessage() {}

func (x *QueryResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultPayload.ProtoReflect.Descriptor instead.
func (*QueryResultPayload) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryResultPayload) GetPayload() isQueryResultPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryResultPayload) GetResult() *QueryResult {
	if x != nil {
		if x, ok := x.Payload.(*QueryResultPayload_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *QueryResultPayload) GetDiagnostic() *PgDiagnostic {
	if x != nil {
		if x, ok := x.Payload.(*QueryResultPayload_Diagnostic); ok {
			return x.Diagnostic
		}
	}
	return nil
}

func (x *QueryResultPayload) GetNotification() *PgNotification {
	if x != nil {
		if x, ok := x.Payload.(*QueryResultPayload_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isQueryResultPayload_Payload interface {
	isQueryResultPayload_Payload()
}

type QueryResultPayload_Result struct {
	Result *QueryResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"` // Row data with fields/rows/command_tag
}

type QueryResultPayload_Diagnostic struct {
	Diagnostic *PgDiagnostic `protobuf:"bytes,2,opt,name=diagnostic,proto3,oneof"` // Individual error or notice
}

type QueryResultPayload_Notification struct {
	Notification *PgNotification `protobuf:"bytes,3,opt,name=notification,proto3,oneof"` // Async notification from LISTEN
}

func (*QueryResultPayload_Result) isQueryResultPayload_Payload() {}

func (*QueryResultPayload_Diagnostic) isQueryResultPayload_Payload() {}

func (*QueryResultPayload_Notification) isQueryResultPayload_Payload() {}

// QueryResult represents the result of executing a query
type QueryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fields describes the columns in the result set (nil if no rows returned)
	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// rows_affected is the number of rows affected (INSERT, UPDATE, DELETE, etc.)
	RowsAffected uint64 `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	// rows contains the actual data rows
	Rows []*Row `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	// command_tag is the PostgreSQL command tag for this result set.
	// When streaming results, this should only be set on the final packet of a result set.
	// When set, the protocol layer will send CommandComplete and reset state for the next result set.
	// Examples: "SELECT 42", "INSERT 0 5", "UPDATE 10", "DELETE 3", "CREATE TABLE"
	CommandTag string `protobuf:"bytes,4,opt,name=command_tag,json=commandTag,proto3" json:"command_tag,omitempty"`
	// has_fields distinguishes "no result set" (false, fields is nil) from
	// "zero-column result set" (true, fields is empty). Protobuf cannot
	// distinguish a nil repeated field from an empty one, so this bool
	// preserves the distinction across the gRPC boundary.
	HasFields bool `protobuf:"varint,5,opt,name=has_fields,json=hasFields,proto3" json:"has_fields,omitempty"`
	// notices contains PostgreSQL NoticeResponse diagnostics that belong to this
	// result. Streaming RPCs usually send notices as separate QueryResultPayload
	// diagnostics for zero-buffering delivery; unary RPCs (for example COMMIT via
	// ConcludeTransaction) use this field to preserve backend notice ordering.
	Notices []*PgDiagnostic `protobuf:"bytes,6,rep,name=notices,proto3" json:"notices,omitempty"`
	// passthrough_block is the opaque row-passthrough representation. When set,
	// it contains the next ordered chunk of raw PostgreSQL DataRow ('D') wire
	// bytes and rows is empty. A block may contain complete frames or a frame
	// fragment; concatenating blocks in stream order reconstructs the exact
	// DataRow byte stream from the backend. The multigateway writes the block
	// straight to the client socket. fields (RowDescription) remain structured.
	PassthroughBlock []byte `protobuf:"bytes,7,opt,name=passthrough_block,json=passthroughBlock,proto3" json:"passthrough_block,omitempty"`
	// passthrough_row_count is the number of DataRow frames completed in this
	// block. It may be zero when the block contains only a fragment of a large
	// DataRow. This preserves row accounting while rows is empty.
	PassthroughRowCount uint32 `protobuf:"varint,8,opt,name=passthrough_row_count,json=passthroughRowCount,proto3" json:"passthrough_row_count,omitempty"`
	// parameter_status carries GUC_REPORT values (keyed by PostgreSQL's exact
	// ParameterStatus display name, e.g. "DateStyle") that a routed statement
	// changed on the backend. The multipooler forwards the backend's own
	// ParameterStatus messages here so the multigateway can relay them to the
	// client, covering the paths that run the real statement on PostgreSQL
	// (SET/RESET inside a transaction, and the revert on ROLLBACK).
	ParameterStatus map[string]string `protobuf:"bytes,9,rep,name=parameter_status,json=parameterStatus,proto3" json:"parameter_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// passthrough_row_in_progress reports that this block ends inside a DataRow
	// frame. If the upstream stream fails before a later block completes that
	// frame, the gateway must close the client connection instead of appending
	// an ErrorResponse to the incomplete DataRow.
	PassthroughRowInProgress bool `protobuf:"varint,10,opt,name=passthrough_row_in_progress,json=passthroughRowInProgress,proto3" json:"passthrough_row_in_progress,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResult) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryResult) GetRowsAffected() uint64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryResult) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResult) GetCommandTag() string {
	if x != nil {
		return x.CommandTag
	}
	return ""
}

func (x *QueryResult) GetHasFields() bool {
	if x != nil {
		return x.HasFields
	}
	return false
}

func (x *QueryResult) GetNotices() []*PgDiagnostic {
	if x != nil {
		return x.Notices
	}
	return nil
}

func (x *QueryResult) GetPassthroughBlock() []byte {
	if x != nil {
		return x.PassthroughBlock
	}
	return nil
}

func (x *QueryResult) GetPassthroughRowCount() uint32 {
	if x != nil {
		return x.PassthroughRowCount
	}
	return 0
}

func (x *QueryResult) GetParameterStatus() map[string]string {
	if x != nil {
		return x.ParameterStatus
	}
	return nil
}

func (x *QueryResult) GetPassthroughRowInProgress() bool {
	if x != nil {
		return x.PassthroughRowInProgress
	}
	return false
}

// Field represents metadata about a column in the result set.
// This includes all PostgreSQL wire protocol metadata needed for RowDescription messages.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the column name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is a human-readable type name (for logging/debugging)
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// table_oid is the object ID of the table (0 if not a table column)
	TableOid uint32 `protobuf:"varint,3,opt,name=table_oid,json=tableOid,proto3" json:"table_oid,omitempty"`
	// table_attribute_number is the column number in the table (0 if not a table column)
	TableAttributeNumber int32 `protobuf:"varint,4,opt,name=table_attribute_number,json=tableAttributeNumber,proto3" json:"table_attribute_number,omitempty"`
	// data_type_oid is the object ID of the data type
	DataTypeOid uint32 `protobuf:"varint,5,opt,name=data_type_oid,json=dataTypeOid,proto3" json:"data_type_oid,omitempty"`
	// data_type_size is the size of the data type (-1 for variable length)
	DataTypeSize int32 `protobuf:"varint,6,opt,name=data_type_size,json=dataTypeSize,proto3" json:"data_type_size,omitempty"`
	// type_modifier is the type modifier (-1 for no modifier)
	TypeModifier int32 `protobuf:"varint,7,opt,name=type_modifier,json=typeModifier,proto3" json:"type_modifier,omitempty"`
	// format is the format code (0=text, 1=binary)
	Format        int32 `protobuf:"varint,8,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetTableOid() uint32 {
	if x != nil {
		return x.TableOid
	}
	return 0
}

func (x *Field) GetTableAttributeNumber() int32 {
	if x != nil {
		return x.TableAttributeNumber
	}
	return 0
}

func (x *Field) GetDataTypeOid() uint32 {
	if x != nil {
		return x.DataTypeOid
	}
	return 0
}

func (x *Field) GetDataTypeSize() int32 {
	if x != nil {
		return x.DataTypeSize
	}
	return 0
}

func (x *Field) GetTypeModifier() int32 {
	if x != nil {
		return x.TypeModifier
	}
	return 0
}

func (x *Field) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

// Row represents a single row of data in the result set.
type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lengths contains the length of each column value.
	// -1 means NULL, 0 means empty string, >0 means actual length.
	Lengths []int64 `protobuf:"zigzag64,1,rep,packed,name=lengths,proto3" json:"lengths,omitempty"`
	// values contains all non-null values concatenated together.
	// Use lengths to split this into individual column values.
	Values        []byte `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetLengths() []int64 {
	if x != nil {
		return x.Lengths
	}
	return nil
}

func (x *Row) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// PgDiagnostic represents a PostgreSQL diagnostic message (error or notice).
// PostgreSQL uses the same wire format for both ErrorResponse ('E') and NoticeResponse ('N'),
// differentiated by the message_type field. This unified structure captures all 14 fields
// defined in the PostgreSQL protocol for diagnostic messages.
//
// Error severities: ERROR, FATAL, PANIC
// Notice severities: WARNING, NOTICE, DEBUG, INFO, LOG
//
// Reference: https://www.postgresql.org/docs/current/protocol-error-fields.html
type PgDiagnostic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is the PostgreSQL protocol message type byte.
	// 'E' (0x45 = 69) for ErrorResponse, 'N' (0x4E = 78) for NoticeResponse.
	// This determines whether the diagnostic is an error or notice.
	MessageType int32 `protobuf:"varint,15,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// severity is the severity level (e.g., "ERROR", "FATAL", "WARNING", "NOTICE", "INFO")
	Severity string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	// code is the SQLSTATE error code (e.g., "42P01", "22P02")
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// message is the primary human-readable diagnostic message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// detail provides additional detail about the diagnostic (optional)
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// hint provides a hint about how to address the issue (optional)
	Hint string `protobuf:"bytes,5,opt,name=hint,proto3" json:"hint,omitempty"`
	// position is the cursor position in the original query string (1-indexed, 0 if not available)
	Position int32 `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	// internal_position is the cursor position in the internal query (1-indexed, 0 if not available)
	InternalPosition int32 `protobuf:"varint,7,opt,name=internal_position,json=internalPosition,proto3" json:"internal_position,omitempty"`
	// internal_query is the text of the internally-generated query (optional)
	InternalQuery string `protobuf:"bytes,8,opt,name=internal_query,json=internalQuery,proto3" json:"internal_query,omitempty"`
	// where is the context in which the diagnostic occurred, e.g., PL/pgSQL call stack (optional)
	Where string `protobuf:"bytes,9,opt,name=where,proto3" json:"where,omitempty"`
	// schema_name is the name of the schema associated with the diagnostic (optional)
	SchemaName string `protobuf:"bytes,10,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// table_name is the name of the table associated with the diagnostic (optional)
	TableName string `protobuf:"bytes,11,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// column_name is the name of the column associated with the diagnostic (optional)
	ColumnName string `protobuf:"bytes,12,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// data_type_name is the name of the data type associated with the diagnostic (optional)
	DataTypeName string `protobuf:"bytes,13,opt,name=data_type_name,json=dataTypeName,proto3" json:"data_type_name,omitempty"`
	// constraint_name is the name of the constraint associated with the diagnostic (optional)
	ConstraintName string `protobuf:"bytes,14,opt,name=constraint_name,json=constraintName,proto3" json:"constraint_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PgDiagnostic) Reset() {
	*x = PgDiagnostic{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgDiagnostic) ProtoMessage() {}

func (x *PgDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgDiagnostic.ProtoReflect.Descriptor instead.
func (*PgDiagnostic) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *PgDiagnostic) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *PgDiagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *PgDiagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PgDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PgDiagnostic) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PgDiagnostic) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *PgDiagnostic) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PgDiagnostic) GetInternalPosition() int32 {
	if x != nil {
		return x.InternalPosition
	}
	return 0
}

func (x *PgDiagnostic) GetInternalQuery() string {
	if x != nil {
		return x.InternalQuery
	}
	return ""
}

func (x *PgDiagnostic) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *PgDiagnostic) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *PgDiagnostic) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *PgDiagnostic) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *PgDiagnostic) GetDataTypeName() string {
	if x != nil {
		return x.DataTypeName
	}
	return ""
}

func (x *PgDiagnostic) GetConstraintName() string {
	if x != nil {
		return x.ConstraintName
	}
	return ""
}

// PgNotification represents a PostgreSQL asynchronous notification.
// Sent via NotificationResponse ('A') messages to clients that have issued LISTEN.
type PgNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pid is the process ID of the notifying backend.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// channel is the notification channel name.
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// payload is the notification payload string (may be empty).
	Payload       string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgNotification) Reset() {
	*x = PgNotification{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgNotification) ProtoMessage() {}

func (x *PgNotification) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgNotification.ProtoReflect.Descriptor instead.
func (*PgNotification) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *PgNotification) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PgNotification) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PgNotification) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// StatementDescription describes a prepared statement or portal.
// Used for the Describe message ('D') response in the extended query protocol.
type StatementDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parameters describes the parameters of the statement (for statement describe)
	// Nil for portal describe.
	Parameters []*ParameterDescription `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// fields describes the result columns
	// Nil if the statement doesn't return rows.
	Fields []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// has_fields distinguishes "no result set" (false, fields is nil — the
	// backend answered Describe with NoData, e.g. a DML statement) from a
	// row-returning statement with zero result columns (true, fields is a
	// non-nil empty slice — the backend answered with RowDescription carrying 0
	// fields, e.g. `SELECT FROM t`). protobuf serializes both an empty and a nil
	// `repeated fields` identically, so this flag carries the distinction across
	// the wire. Mirror of QueryResult.has_fields.
	HasFields     bool `protobuf:"varint,3,opt,name=has_fields,json=hasFields,proto3" json:"has_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatementDescription) Reset() {
	*x = StatementDescription{}
	mi := &file_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatementDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementDescription) ProtoMessage() {}

func (x *StatementDescription) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementDescription.ProtoReflect.Descriptor instead.
func (*StatementDescription) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *StatementDescription) GetParameters() []*ParameterDescription {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StatementDescription) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *StatementDescription) GetHasFields() bool {
	if x != nil {
		return x.HasFields
	}
	return false
}

// ParameterDescription describes a parameter in a prepared statement.
type ParameterDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data_type_oid is the OID of the parameter's data type
	DataTypeOid   uint32 `protobuf:"varint,1,opt,name=data_type_oid,json=dataTypeOid,proto3" json:"data_type_oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterDescription) Reset() {
	*x = ParameterDescription{}
	mi := &file_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterDescription) ProtoMessage() {}

func (x *ParameterDescription) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterDescription.ProtoReflect.Descriptor instead.
func (*ParameterDescription) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *ParameterDescription) GetDataTypeOid() uint32 {
	if x != nil {
		return x.DataTypeOid
	}
	return 0
}

// Target identifies the destination for query execution: which shard, and
// what mode (writability / consistency) the caller needs. The gateway
// translates the mode into a specific pooler at routing time.
type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shard_key identifies the destination shard (database, table_group, shard).
	// Reuses clustermetadata.ShardKey so the shard-identity vocabulary is the
	// same across the topology and routing layers.
	ShardKey *clustermetadata.ShardKey `protobuf:"bytes,4,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	// mode expresses the caller's writability / consistency needs.
	// See Mode for the semantics of each value.
	Mode          Mode `protobuf:"varint,5,opt,name=mode,proto3,enum=query.Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{8}
}

func (x *Target) GetShardKey() *clustermetadata.ShardKey {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

func (x *Target) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

// PreparedStatement represents a prepared statement in the extended query protocol.
// Prepared statements are created by the Parse message and can be executed
// multiple times with different parameter values.
type PreparedStatement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the client-provided name for the prepared statement.
	// An empty name indicates the unnamed statement.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// query is the SQL query string.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// param_types contains the OIDs of the parameter types.
	// This is sent by the client in the Parse message.
	ParamTypes    []uint32 `protobuf:"varint,3,rep,packed,name=param_types,json=paramTypes,proto3" json:"param_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparedStatement) Reset() {
	*x = PreparedStatement{}
	mi := &file_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedStatement) ProtoMessage() {}

func (x *PreparedStatement) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedStatement.ProtoReflect.Descriptor instead.
func (*PreparedStatement) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{9}
}

func (x *PreparedStatement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreparedStatement) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PreparedStatement) GetParamTypes() []uint32 {
	if x != nil {
		return x.ParamTypes
	}
	return nil
}

// ExecuteSqlPreparedStatement carries a SQL-level EXECUTE wrapper whose
// prepared-statement name must be resolved by the multipooler. The gateway
// renders the legal PostgreSQL wrapper around the name as prefix/suffix, and
// the multipooler materializes:
//
//	sql_prefix || quote_ident(pooler_canonical_name) || sql_suffix
//
// after using prepared_statement to ensure the backend has the consolidated
// pooler-level prepared statement (ppstmt*) for the selected connection.
type ExecuteSqlPreparedStatement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prepared_statement describes the underlying prepared query. The multipooler
	// deduplicates by (query, param_types), ignoring the gateway-local name, and
	// returns a pooler-local canonical name such as ppstmt0.
	PreparedStatement *PreparedStatement `protobuf:"bytes,1,opt,name=prepared_statement,json=preparedStatement,proto3" json:"prepared_statement,omitempty"`
	// sql_prefix is the SQL text before the prepared statement name, generated by
	// the gateway from the parsed AST. Examples: "EXECUTE ",
	// "EXPLAIN EXECUTE ", "CREATE TABLE t AS EXECUTE ".
	SqlPrefix string `protobuf:"bytes,2,opt,name=sql_prefix,json=sqlPrefix,proto3" json:"sql_prefix,omitempty"`
	// sql_suffix is the SQL text after the prepared statement name, including any
	// EXECUTE argument expressions and wrapper tail such as WITH NO DATA.
	SqlSuffix string `protobuf:"bytes,3,opt,name=sql_suffix,json=sqlSuffix,proto3" json:"sql_suffix,omitempty"`
	// force_unnamed_parse asks the multipooler to Parse the prepared statement as
	// the unnamed statement without executing SQL. This preserves PostgreSQL's
	// transaction-time validation and lock acquisition semantics.
	ForceUnnamedParse bool `protobuf:"varint,4,opt,name=force_unnamed_parse,json=forceUnnamedParse,proto3" json:"force_unnamed_parse,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteSqlPreparedStatement) Reset() {
	*x = ExecuteSqlPreparedStatement{}
	mi := &file_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSqlPreparedStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSqlPreparedStatement) ProtoMessage() {}

func (x *ExecuteSqlPreparedStatement) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSqlPreparedStatement.ProtoReflect.Descriptor instead.
func (*ExecuteSqlPreparedStatement) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteSqlPreparedStatement) GetPreparedStatement() *PreparedStatement {
	if x != nil {
		return x.PreparedStatement
	}
	return nil
}

func (x *ExecuteSqlPreparedStatement) GetSqlPrefix() string {
	if x != nil {
		return x.SqlPrefix
	}
	return ""
}

func (x *ExecuteSqlPreparedStatement) GetSqlSuffix() string {
	if x != nil {
		return x.SqlSuffix
	}
	return ""
}

func (x *ExecuteSqlPreparedStatement) GetForceUnnamedParse() bool {
	if x != nil {
		return x.ForceUnnamedParse
	}
	return false
}

// Portal represents a bound prepared statement with parameters.
// Portals are created by the Bind message and can be executed via Execute.
type Portal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the client-provided name for the portal.
	// An empty name indicates the unnamed portal.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// prepared_statement_name is the name of the prepared statement this portal is bound to.
	PreparedStatementName string `protobuf:"bytes,2,opt,name=prepared_statement_name,json=preparedStatementName,proto3" json:"prepared_statement_name,omitempty"`
	// param_lengths contains the length of each parameter value.
	// -1 means NULL, 0 means empty string, >0 means actual length.
	ParamLengths []int64 `protobuf:"zigzag64,3,rep,packed,name=param_lengths,json=paramLengths,proto3" json:"param_lengths,omitempty"`
	// param_values contains all non-null parameter values concatenated together.
	// Use param_lengths to split this into individual parameter values.
	ParamValues []byte `protobuf:"bytes,4,opt,name=param_values,json=paramValues,proto3" json:"param_values,omitempty"`
	// param_formats specifies the format code for each parameter.
	// 0 = text, 1 = binary.
	// If empty, all parameters are text format.
	// If a single element, that format applies to all parameters.
	ParamFormats []int32 `protobuf:"varint,5,rep,packed,name=param_formats,json=paramFormats,proto3" json:"param_formats,omitempty"`
	// result_formats specifies the format code for each result column.
	// 0 = text, 1 = binary.
	// If empty, all results are text format.
	// If a single element, that format applies to all result columns.
	ResultFormats []int32 `protobuf:"varint,6,rep,packed,name=result_formats,json=resultFormats,proto3" json:"result_formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Portal) Reset() {
	*x = Portal{}
	mi := &file_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Portal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Portal) ProtoMessage() {}

func (x *Portal) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Portal.ProtoReflect.Descriptor instead.
func (*Portal) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{11}
}

func (x *Portal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Portal) GetPreparedStatementName() string {
	if x != nil {
		return x.PreparedStatementName
	}
	return ""
}

func (x *Portal) GetParamLengths() []int64 {
	if x != nil {
		return x.ParamLengths
	}
	return nil
}

func (x *Portal) GetParamValues() []byte {
	if x != nil {
		return x.ParamValues
	}
	return nil
}

func (x *Portal) GetParamFormats() []int32 {
	if x != nil {
		return x.ParamFormats
	}
	return nil
}

func (x *Portal) GetResultFormats() []int32 {
	if x != nil {
		return x.ResultFormats
	}
	return nil
}

// ReservedState contains information about a reserved connection.
// Embedded in response messages to convey the authoritative reservation state from multipooler.
type ReservedState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reserved_connection_id is the ID of the reserved connection.
	// Zero when the connection has been released or was not reserved.
	ReservedConnectionId uint64 `protobuf:"varint,1,opt,name=reserved_connection_id,json=reservedConnectionId,proto3" json:"reserved_connection_id,omitempty"`
	// pooler_id identifies which multipooler instance owns the reserved connection
	PoolerId *clustermetadata.ID `protobuf:"bytes,2,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	// reservation_reasons is a bitmask of ReservationReason values indicating why the connection
	// is still reserved. Zero means the connection was released.
	ReservationReasons uint32 `protobuf:"varint,3,opt,name=reservation_reasons,json=reservationReasons,proto3" json:"reservation_reasons,omitempty"`
	// backend_process_id is the real PostgreSQL backend process ID for this
	// reserved connection — the PID visible in pg_stat_activity / pg_locks.
	// Used to bridge the gap between multigateway's virtual PIDs and
	// PostgreSQL's real PIDs so lock-detection functions like
	// pg_isolation_test_session_is_blocked() can map vpid → real pid through
	// the proxy.
	BackendProcessId uint32 `protobuf:"varint,4,opt,name=backend_process_id,json=backendProcessId,proto3" json:"backend_process_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReservedState) Reset() {
	*x = ReservedState{}
	mi := &file_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservedState) ProtoMessage() {}

func (x *ReservedState) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservedState.ProtoReflect.Descriptor instead.
func (*ReservedState) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{12}
}

func (x *ReservedState) GetReservedConnectionId() uint64 {
	if x != nil {
		return x.ReservedConnectionId
	}
	return 0
}

func (x *ReservedState) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

func (x *ReservedState) GetReservationReasons() uint32 {
	if x != nil {
		return x.ReservationReasons
	}
	return 0
}

func (x *ReservedState) GetBackendProcessId() uint32 {
	if x != nil {
		return x.BackendProcessId
	}
	return 0
}

// ExecuteOptions contains execution options for query execution.
// This includes session state like prepared statements and portals that
// need to be available on the connection where the query is executed.
type ExecuteOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_settings contains session variables (SET commands) that should
	// be applied to the connection before executing the query.
	// Key is the variable name, value is the variable value.
	SessionSettings map[string]string `protobuf:"bytes,1,rep,name=session_settings,json=sessionSettings,proto3" json:"session_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// user is the PostgreSQL user/role identity for query execution.
	// This determines which per-user connection pool to use.
	// Required for per-user pool routing in the multipooler.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// max_rows is the maximum number of rows to return from Execute.
	// 0 means return all rows. Used by the Execute message in the extended query protocol.
	MaxRows uint64 `protobuf:"varint,3,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	// reserved_connection_id is the ID of a reserved connection on the multipooler.
	// Used for connection pinning - this tells the multipooler which specific
	// connection to use for executing this query.
	ReservedConnectionId uint64 `protobuf:"varint,4,opt,name=reserved_connection_id,json=reservedConnectionId,proto3" json:"reserved_connection_id,omitempty"`
	// user_auth carries SCRAM-SHA-256 passthrough keys captured during the
	// client's authentication handshake at the multigateway. When the
	// multipooler has SCRAM passthrough enabled, it uses these keys to
	// authenticate to the backing PostgreSQL as the session's real user
	// instead of relying on trust on the local connection. Unset for
	// sessions that did not authenticate via SCRAM.
	UserAuth *UserAuth `protobuf:"bytes,5,opt,name=user_auth,json=userAuth,proto3" json:"user_auth,omitempty"`
	// client_connection_id is the multigateway's virtual PID for this client
	// connection. The multipooler can register it against the underlying
	// PostgreSQL backend PID so lock-detection functions can map virtual PIDs
	// (visible to clients) back to real backend PIDs without altering the
	// client-visible application_name.
	ClientConnectionId uint32 `protobuf:"varint,6,opt,name=client_connection_id,json=clientConnectionId,proto3" json:"client_connection_id,omitempty"`
	// execute_sql_prepared_statement, if set, describes a SQL-level EXECUTE
	// wrapper that references a gateway-managed prepared statement. The
	// multipooler first prepares the underlying query using pooler-level
	// consolidation (ppstmt*), then substitutes that canonical name between the
	// provided SQL prefix/suffix and executes the materialized SQL. Used for
	// top-level EXECUTE, EXPLAIN EXECUTE, and CREATE TABLE ... AS EXECUTE.
	//
	// This field is only consumed by StreamExecute. PortalStreamExecute has its
	// own top-level prepared_statement field.
	ExecuteSqlPreparedStatement *ExecuteSqlPreparedStatement `protobuf:"bytes,7,opt,name=execute_sql_prepared_statement,json=executeSqlPreparedStatement,proto3" json:"execute_sql_prepared_statement,omitempty"`
	// passthrough_row requests opaque row passthrough for this query: the
	// multipooler returns rows as concatenated raw DataRow frames in
	// QueryResult.passthrough_block instead of structured Row messages, and the
	// multigateway writes them straight to the client. The multigateway sets this
	// for straight client pass-through queries and leaves it false for results it
	// must interpret itself (SET, SHOW, catalog rewrites). Defaulting to false
	// keeps non-gateway callers (multiadmin, multiorch) on the structured path.
	PassthroughRow bool `protobuf:"varint,8,opt,name=passthrough_row,json=passthroughRow,proto3" json:"passthrough_row,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteOptions) Reset() {
	*x = ExecuteOptions{}
	mi := &file_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOptions) ProtoMessage() {}

func (x *ExecuteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOptions.ProtoReflect.Descriptor instead.
func (*ExecuteOptions) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteOptions) GetSessionSettings() map[string]string {
	if x != nil {
		return x.SessionSettings
	}
	return nil
}

func (x *ExecuteOptions) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecuteOptions) GetMaxRows() uint64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

func (x *ExecuteOptions) GetReservedConnectionId() uint64 {
	if x != nil {
		return x.ReservedConnectionId
	}
	return 0
}

func (x *ExecuteOptions) GetUserAuth() *UserAuth {
	if x != nil {
		return x.UserAuth
	}
	return nil
}

func (x *ExecuteOptions) GetClientConnectionId() uint32 {
	if x != nil {
		return x.ClientConnectionId
	}
	return 0
}

func (x *ExecuteOptions) GetExecuteSqlPreparedStatement() *ExecuteSqlPreparedStatement {
	if x != nil {
		return x.ExecuteSqlPreparedStatement
	}
	return nil
}

func (x *ExecuteOptions) GetPassthroughRow() bool {
	if x != nil {
		return x.PassthroughRow
	}
	return false
}

// UserAuth carries cryptographic material extracted from the client's SCRAM
// handshake at multigateway. The pair (client_key, server_key) is sufficient
// to authenticate as the user to any SCRAM-SHA-256 verifier of the same
// password, without ever holding the plaintext password.
type UserAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_key is the SCRAM ClientKey recovered from the client's proof
	// during authentication. 32 bytes for SCRAM-SHA-256.
	//
	// [debug_redact = true] is the canonical signal of intent. It is currently
	// advisory in google.golang.org/protobuf (see
	// https://github.com/golang/protobuf/issues/1655); when upstream lands the
	// runtime path, generated String()/prototext output will redact this field
	// automatically. query_redact_test.go locks the annotation in.
	ClientKey []byte `protobuf:"bytes,1,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	// server_key is the SCRAM ServerKey read from the user's verifier in
	// pg_authid. 32 bytes for SCRAM-SHA-256.
	ServerKey     []byte `protobuf:"bytes,2,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuth) Reset() {
	*x = UserAuth{}
	mi := &file_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuth) ProtoMessage() {}

func (x *UserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuth.ProtoReflect.Descriptor instead.
func (*UserAuth) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{14}
}

func (x *UserAuth) GetClientKey() []byte {
	if x != nil {
		return x.ClientKey
	}
	return nil
}

func (x *UserAuth) GetServerKey() []byte {
	if x != nil {
		return x.ServerKey
	}
	return nil
}

// ReservationOptions specifies options when creating or extending a reserved connection.
// This is passed alongside ExecuteOptions on requests that may need to create or modify
// a connection reservation. It is extensible for future options (e.g., isolation level,
// read-only mode).
type ReservationOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reasons is a bitmask of multipoolerservice.ReservationReason values indicating why
	// the connection is being reserved. Multiple reasons can be ORed together (e.g.,
	// TRANSACTION | TEMP_TABLE).
	//
	// When non-zero and reserved_connection_id is 0, StreamExecute creates a new reserved
	// connection. When non-zero and reserved_connection_id is set, the reasons are OR'd
	// into the existing reservation.
	Reasons uint32 `protobuf:"varint,1,opt,name=reasons,proto3" json:"reasons,omitempty"`
	// begin_query is the original BEGIN statement text (e.g., "BEGIN ISOLATION LEVEL SERIALIZABLE"
	// or "START TRANSACTION READ ONLY"). When set and the transaction reason is present, the
	// multipooler uses this instead of a plain "BEGIN" to preserve isolation level and access mode.
	// If empty and transaction reason is set, defaults to "BEGIN".
	BeginQuery string `protobuf:"bytes,2,opt,name=begin_query,json=beginQuery,proto3" json:"begin_query,omitempty"`
	// pin_portal_names lists named portals (cursors) that must be pinned to the
	// reserved connection for the lifetime of the named portal — used for
	// DECLARE ... WITH HOLD, where the cursor must survive COMMIT. The
	// multipooler calls ReserveForPortal(name) for each entry, which adds
	// ReasonPortal to the reservation bitmask and registers the name in the
	// per-connection portal set. Independent of `reasons` — the multipooler
	// sets ReasonPortal implicitly when this list is non-empty.
	PinPortalNames []string `protobuf:"bytes,3,rep,name=pin_portal_names,json=pinPortalNames,proto3" json:"pin_portal_names,omitempty"`
	// release_portal_names lists named portals (cursors) to unpin from the
	// reserved connection — used for CLOSE <name> / CLOSE ALL on a WITH HOLD
	// cursor. The multipooler calls ReleasePortal(name) for each entry; if
	// the call drains the final ReasonPortal bit AND no other reasons remain,
	// the connection is released back to the pool and the returned
	// ReservedState has connection_id == 0.
	ReleasePortalNames []string `protobuf:"bytes,4,rep,name=release_portal_names,json=releasePortalNames,proto3" json:"release_portal_names,omitempty"`
	// recheck_advisory_locks asks the multipooler to re-probe pg_locks after
	// running this statement and drop ReasonSessionAdvisoryLock (releasing the
	// connection if no other reason remains) when the session no longer holds any
	// advisory lock. The gateway sets it only for statements that touch
	// session-level advisory locks (an acquire — to catch a failed
	// pg_try_advisory_lock — or a release), so the probe runs only when it can
	// matter rather than after every query on a pinned connection.
	RecheckAdvisoryLocks bool `protobuf:"varint,5,opt,name=recheck_advisory_locks,json=recheckAdvisoryLocks,proto3" json:"recheck_advisory_locks,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReservationOptions) Reset() {
	*x = ReservationOptions{}
	mi := &file_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationOptions) ProtoMessage() {}

func (x *ReservationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationOptions.ProtoReflect.Descriptor instead.
func (*ReservationOptions) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{15}
}

func (x *ReservationOptions) GetReasons() uint32 {
	if x != nil {
		return x.Reasons
	}
	return 0
}

func (x *ReservationOptions) GetBeginQuery() string {
	if x != nil {
		return x.BeginQuery
	}
	return ""
}

func (x *ReservationOptions) GetPinPortalNames() []string {
	if x != nil {
		return x.PinPortalNames
	}
	return nil
}

func (x *ReservationOptions) GetReleasePortalNames() []string {
	if x != nil {
		return x.ReleasePortalNames
	}
	return nil
}

func (x *ReservationOptions) GetRecheckAdvisoryLocks() bool {
	if x != nil {
		return x.RecheckAdvisoryLocks
	}
	return false
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x05query\x1a\x15clustermetadata.proto\"\xc1\x01\n" +
	"\x12QueryResultPayload\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultH\x00R\x06result\x125\n" +
	"\n" +
	"diagnostic\x18\x02 \x01(\v2\x13.query.PgDiagnosticH\x00R\n" +
	"diagnostic\x12;\n" +
	"\fnotification\x18\x03 \x01(\v2\x15.query.PgNotificationH\x00R\fnotificationB\t\n" +
	"\apayload\"\x9f\x04\n" +
	"\vQueryResult\x12$\n" +
	"\x06fields\x18\x01 \x03(\v2\f.query.FieldR\x06fields\x12#\n" +
	"\rrows_affected\x18\x02 \x01(\x04R\frowsAffected\x12\x1e\n" +
	"\x04rows\x18\x03 \x03(\v2\n" +
	".query.RowR\x04rows\x12\x1f\n" +
	"\vcommand_tag\x18\x04 \x01(\tR\n" +
	"commandTag\x12\x1d\n" +
	"\n" +
	"has_fields\x18\x05 \x01(\bR\thasFields\x12-\n" +
	"\anotices\x18\x06 \x03(\v2\x13.query.PgDiagnosticR\anotices\x12+\n" +
	"\x11passthrough_block\x18\a \x01(\fR\x10passthroughBlock\x122\n" +
	"\x15passthrough_row_count\x18\b \x01(\rR\x13passthroughRowCount\x12R\n" +
	"\x10parameter_status\x18\t \x03(\v2'.query.QueryResult.ParameterStatusEntryR\x0fparameterStatus\x12=\n" +
	"\x1bpassthrough_row_in_progress\x18\n" +
	" \x01(\bR\x18passthroughRowInProgress\x1aB\n" +
	"\x14ParameterStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x02\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttable_oid\x18\x03 \x01(\rR\btableOid\x124\n" +
	"\x16table_attribute_number\x18\x04 \x01(\x05R\x14tableAttributeNumber\x12\"\n" +
	"\rdata_type_oid\x18\x05 \x01(\rR\vdataTypeOid\x12$\n" +
	"\x0edata_type_size\x18\x06 \x01(\x05R\fdataTypeSize\x12#\n" +
	"\rtype_modifier\x18\a \x01(\x05R\ftypeModifier\x12\x16\n" +
	"\x06format\x18\b \x01(\x05R\x06format\"7\n" +
	"\x03Row\x12\x18\n" +
	"\alengths\x18\x01 \x03(\x12R\alengths\x12\x16\n" +
	"\x06values\x18\x02 \x01(\fR\x06values\"\xdd\x03\n" +
	"\fPgDiagnostic\x12!\n" +
	"\fmessage_type\x18\x0f \x01(\x05R\vmessageType\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x12\n" +
	"\x04hint\x18\x05 \x01(\tR\x04hint\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12+\n" +
	"\x11internal_position\x18\a \x01(\x05R\x10internalPosition\x12%\n" +
	"\x0einternal_query\x18\b \x01(\tR\rinternalQuery\x12\x14\n" +
	"\x05where\x18\t \x01(\tR\x05where\x12\x1f\n" +
	"\vschema_name\x18\n" +
	" \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\v \x01(\tR\ttableName\x12\x1f\n" +
	"\vcolumn_name\x18\f \x01(\tR\n" +
	"columnName\x12$\n" +
	"\x0edata_type_name\x18\r \x01(\tR\fdataTypeName\x12'\n" +
	"\x0fconstraint_name\x18\x0e \x01(\tR\x0econstraintName\"V\n" +
	"\x0ePgNotification\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\x98\x01\n" +
	"\x14StatementDescription\x12;\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1b.query.ParameterDescriptionR\n" +
	"parameters\x12$\n" +
	"\x06fields\x18\x02 \x03(\v2\f.query.FieldR\x06fields\x12\x1d\n" +
	"\n" +
	"has_fields\x18\x03 \x01(\bR\thasFields\":\n" +
	"\x14ParameterDescription\x12\"\n" +
	"\rdata_type_oid\x18\x01 \x01(\rR\vdataTypeOid\"a\n" +
	"\x06Target\x126\n" +
	"\tshard_key\x18\x04 \x01(\v2\x19.clustermetadata.ShardKeyR\bshardKey\x12\x1f\n" +
	"\x04mode\x18\x05 \x01(\x0e2\v.query.ModeR\x04mode\"^\n" +
	"\x11PreparedStatement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1f\n" +
	"\vparam_types\x18\x03 \x03(\rR\n" +
	"paramTypes\"\xd4\x01\n" +
	"\x1bExecuteSqlPreparedStatement\x12G\n" +
	"\x12prepared_statement\x18\x01 \x01(\v2\x18.query.PreparedStatementR\x11preparedStatement\x12\x1d\n" +
	"\n" +
	"sql_prefix\x18\x02 \x01(\tR\tsqlPrefix\x12\x1d\n" +
	"\n" +
	"sql_suffix\x18\x03 \x01(\tR\tsqlSuffix\x12.\n" +
	"\x13force_unnamed_parse\x18\x04 \x01(\bR\x11forceUnnamedParse\"\xe8\x01\n" +
	"\x06Portal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x17prepared_statement_name\x18\x02 \x01(\tR\x15preparedStatementName\x12#\n" +
	"\rparam_lengths\x18\x03 \x03(\x12R\fparamLengths\x12!\n" +
	"\fparam_values\x18\x04 \x01(\fR\vparamValues\x12#\n" +
	"\rparam_formats\x18\x05 \x03(\x05R\fparamFormats\x12%\n" +
	"\x0eresult_formats\x18\x06 \x03(\x05R\rresultFormats\"\xd6\x01\n" +
	"\rReservedState\x124\n" +
	"\x16reserved_connection_id\x18\x01 \x01(\x04R\x14reservedConnectionId\x120\n" +
	"\tpooler_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\x12/\n" +
	"\x13reservation_reasons\x18\x03 \x01(\rR\x12reservationReasons\x12,\n" +
	"\x12backend_process_id\x18\x04 \x01(\rR\x10backendProcessId\"\x82\x04\n" +
	"\x0eExecuteOptions\x12U\n" +
	"\x10session_settings\x18\x01 \x03(\v2*.query.ExecuteOptions.SessionSettingsEntryR\x0fsessionSettings\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x19\n" +
	"\bmax_rows\x18\x03 \x01(\x04R\amaxRows\x124\n" +
	"\x16reserved_connection_id\x18\x04 \x01(\x04R\x14reservedConnectionId\x12,\n" +
	"\tuser_auth\x18\x05 \x01(\v2\x0f.query.UserAuthR\buserAuth\x120\n" +
	"\x14client_connection_id\x18\x06 \x01(\rR\x12clientConnectionId\x12g\n" +
	"\x1eexecute_sql_prepared_statement\x18\a \x01(\v2\".query.ExecuteSqlPreparedStatementR\x1bexecuteSqlPreparedStatement\x12'\n" +
	"\x0fpassthrough_row\x18\b \x01(\bR\x0epassthroughRow\x1aB\n" +
	"\x14SessionSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\bUserAuth\x12\"\n" +
	"\n" +
	"client_key\x18\x01 \x01(\fB\x03\x80\x01\x01R\tclientKey\x12\"\n" +
	"\n" +
	"server_key\x18\x02 \x01(\fB\x03\x80\x01\x01R\tserverKey\"\xe1\x01\n" +
	"\x12ReservationOptions\x12\x18\n" +
	"\areasons\x18\x01 \x01(\rR\areasons\x12\x1f\n" +
	"\vbegin_query\x18\x02 \x01(\tR\n" +
	"beginQuery\x12(\n" +
	"\x10pin_portal_names\x18\x03 \x03(\tR\x0epinPortalNames\x120\n" +
	"\x14release_portal_names\x18\x04 \x03(\tR\x12releasePortalNames\x124\n" +
	"\x16recheck_advisory_locks\x18\x05 \x01(\bR\x14recheckAdvisoryLocks*[\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMODE_WRITABLE\x10\x01\x12\x13\n" +
	"\x0fMODE_CONSISTENT\x10\x02\x12\x15\n" +
	"\x11MODE_INCONSISTENT\x10\x03B,Z*github.com/multigres/multigres/go/pb/queryb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_query_proto_goTypes = []any{
	(Mode)(0),                           // 0: query.Mode
	(*QueryResultPayload)(nil),          // 1: query.QueryResultPayload
	(*QueryResult)(nil),                 // 2: query.QueryResult
	(*Field)(nil),                       // 3: query.Field
	(*Row)(nil),                         // 4: query.Row
	(*PgDiagnostic)(nil),                // 5: query.PgDiagnostic
	(*PgNotification)(nil),              // 6: query.PgNotification
	(*StatementDescription)(nil),        // 7: query.StatementDescription
	(*ParameterDescription)(nil),        // 8: query.ParameterDescription
	(*Target)(nil),                      // 9: query.Target
	(*PreparedStatement)(nil),           // 10: query.PreparedStatement
	(*ExecuteSqlPreparedStatement)(nil), // 11: query.ExecuteSqlPreparedStatement
	(*Portal)(nil),                      // 12: query.Portal
	(*ReservedState)(nil),               // 13: query.ReservedState
	(*ExecuteOptions)(nil),              // 14: query.ExecuteOptions
	(*UserAuth)(nil),                    // 15: query.UserAuth
	(*ReservationOptions)(nil),          // 16: query.ReservationOptions
	nil,                                 // 17: query.QueryResult.ParameterStatusEntry
	nil,                                 // 18: query.ExecuteOptions.SessionSettingsEntry
	(*clustermetadata.ShardKey)(nil),    // 19: clustermetadata.ShardKey
	(*clustermetadata.ID)(nil),          // 20: clustermetadata.ID
}
var file_query_proto_depIdxs = []int32{
	2,  // 0: query.QueryResultPayload.result:type_name -> query.QueryResult
	5,  // 1: query.QueryResultPayload.diagnostic:type_name -> query.PgDiagnostic
	6,  // 2: query.QueryResultPayload.notification:type_name -> query.PgNotification
	3,  // 3: query.QueryResult.fields:type_name -> query.Field
	4,  // 4: query.QueryResult.rows:type_name -> query.Row
	5,  // 5: query.QueryResult.notices:type_name -> query.PgDiagnostic
	17, // 6: query.QueryResult.parameter_status:type_name -> query.QueryResult.ParameterStatusEntry
	8,  // 7: query.StatementDescription.parameters:type_name -> query.ParameterDescription
	3,  // 8: query.StatementDescription.fields:type_name -> query.Field
	19, // 9: query.Target.shard_key:type_name -> clustermetadata.ShardKey
	0,  // 10: query.Target.mode:type_name -> query.Mode
	10, // 11: query.ExecuteSqlPreparedStatement.prepared_statement:type_name -> query.PreparedStatement
	20, // 12: query.ReservedState.pooler_id:type_name -> clustermetadata.ID
	18, // 13: query.ExecuteOptions.session_settings:type_name -> query.ExecuteOptions.SessionSettingsEntry
	15, // 14: query.ExecuteOptions.user_auth:type_name -> query.UserAuth
	11, // 15: query.ExecuteOptions.execute_sql_prepared_statement:type_name -> query.ExecuteSqlPreparedStatement
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_query_proto_msgTypes[0].OneofWrappers = []any{
		(*QueryResultPayload_Result)(nil),
		(*QueryResultPayload_Diagnostic)(nil),
		(*QueryResultPayload_Notification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		EnumInfos:         file_query_proto_enumTypes,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
