// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: consensusservice.proto

package consensus

import (
	context "context"
	consensusdata "github.com/multigres/multigres/go/pb/consensusdata"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultipoolerConsensus_UpdateConsensusRule_FullMethodName = "/consensus.MultipoolerConsensus/UpdateConsensusRule"
	MultipoolerConsensus_Recruit_FullMethodName             = "/consensus.MultipoolerConsensus/Recruit"
	MultipoolerConsensus_Promote_FullMethodName             = "/consensus.MultipoolerConsensus/Promote"
	MultipoolerConsensus_SetPrimary_FullMethodName          = "/consensus.MultipoolerConsensus/SetPrimary"
)

// MultipoolerConsensusClient is the client API for MultipoolerConsensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultipoolerConsensus provides consensus APIs for leader election and HA operations.
type MultipoolerConsensusClient interface {
	// UpdateConsensusRule applies a cohort-membership change (add/remove). The
	// primary handler updates synchronous_standby_names and records the cohort
	// change in rule_history.
	UpdateConsensusRule(ctx context.Context, in *multipoolermanagerdata.UpdateConsensusRuleRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.UpdateConsensusRuleResponse, error)
	// Recruit asks a pooler to revoke all terms below the one specified and
	// record the coordinator's exclusive claim on that term.
	Recruit(ctx context.Context, in *consensusdata.RecruitRequest, opts ...grpc.CallOption) (*consensusdata.RecruitResponse, error)
	// Promote sends a complete shard-state proposal to a pooler. The designated
	// leader promotes its postgres; all other cohort members point replication at
	// the new primary.
	Promote(ctx context.Context, in *consensusdata.PromoteRequest, opts ...grpc.CallOption) (*consensusdata.PromoteResponse, error)
	// SetPrimary tells a pooler which postgres primary to follow at a given
	// consensus term. Used both to endorse in-flight proposals and to catch
	// followers up to durable decisions.
	//
	// TODO: consider renaming to SetReplicationPrimary for clarity — this sets the
	// postgres replication primary the pooler follows, distinct from consensus
	// leadership and routing role. "SetPrimary" reads as if it makes the pooler a
	// primary; it actually points the pooler at one.
	SetPrimary(ctx context.Context, in *consensusdata.SetPrimaryRequest, opts ...grpc.CallOption) (*consensusdata.SetPrimaryResponse, error)
}

type multipoolerConsensusClient struct {
	cc grpc.ClientConnInterface
}

func NewMultipoolerConsensusClient(cc grpc.ClientConnInterface) MultipoolerConsensusClient {
	return &multipoolerConsensusClient{cc}
}

func (c *multipoolerConsensusClient) UpdateConsensusRule(ctx context.Context, in *multipoolermanagerdata.UpdateConsensusRuleRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.UpdateConsensusRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.UpdateConsensusRuleResponse)
	err := c.cc.Invoke(ctx, MultipoolerConsensus_UpdateConsensusRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerConsensusClient) Recruit(ctx context.Context, in *consensusdata.RecruitRequest, opts ...grpc.CallOption) (*consensusdata.RecruitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(consensusdata.RecruitResponse)
	err := c.cc.Invoke(ctx, MultipoolerConsensus_Recruit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerConsensusClient) Promote(ctx context.Context, in *consensusdata.PromoteRequest, opts ...grpc.CallOption) (*consensusdata.PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(consensusdata.PromoteResponse)
	err := c.cc.Invoke(ctx, MultipoolerConsensus_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerConsensusClient) SetPrimary(ctx context.Context, in *consensusdata.SetPrimaryRequest, opts ...grpc.CallOption) (*consensusdata.SetPrimaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(consensusdata.SetPrimaryResponse)
	err := c.cc.Invoke(ctx, MultipoolerConsensus_SetPrimary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultipoolerConsensusServer is the server API for MultipoolerConsensus service.
// All implementations must embed UnimplementedMultipoolerConsensusServer
// for forward compatibility.
//
// MultipoolerConsensus provides consensus APIs for leader election and HA operations.
type MultipoolerConsensusServer interface {
	// UpdateConsensusRule applies a cohort-membership change (add/remove). The
	// primary handler updates synchronous_standby_names and records the cohort
	// change in rule_history.
	UpdateConsensusRule(context.Context, *multipoolermanagerdata.UpdateConsensusRuleRequest) (*multipoolermanagerdata.UpdateConsensusRuleResponse, error)
	// Recruit asks a pooler to revoke all terms below the one specified and
	// record the coordinator's exclusive claim on that term.
	Recruit(context.Context, *consensusdata.RecruitRequest) (*consensusdata.RecruitResponse, error)
	// Promote sends a complete shard-state proposal to a pooler. The designated
	// leader promotes its postgres; all other cohort members point replication at
	// the new primary.
	Promote(context.Context, *consensusdata.PromoteRequest) (*consensusdata.PromoteResponse, error)
	// SetPrimary tells a pooler which postgres primary to follow at a given
	// consensus term. Used both to endorse in-flight proposals and to catch
	// followers up to durable decisions.
	//
	// TODO: consider renaming to SetReplicationPrimary for clarity — this sets the
	// postgres replication primary the pooler follows, distinct from consensus
	// leadership and routing role. "SetPrimary" reads as if it makes the pooler a
	// primary; it actually points the pooler at one.
	SetPrimary(context.Context, *consensusdata.SetPrimaryRequest) (*consensusdata.SetPrimaryResponse, error)
	mustEmbedUnimplementedMultipoolerConsensusServer()
}

// UnimplementedMultipoolerConsensusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultipoolerConsensusServer struct{}

func (UnimplementedMultipoolerConsensusServer) UpdateConsensusRule(context.Context, *multipoolermanagerdata.UpdateConsensusRuleRequest) (*multipoolermanagerdata.UpdateConsensusRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConsensusRule not implemented")
}
func (UnimplementedMultipoolerConsensusServer) Recruit(context.Context, *consensusdata.RecruitRequest) (*consensusdata.RecruitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recruit not implemented")
}
func (UnimplementedMultipoolerConsensusServer) Promote(context.Context, *consensusdata.PromoteRequest) (*consensusdata.PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedMultipoolerConsensusServer) SetPrimary(context.Context, *consensusdata.SetPrimaryRequest) (*consensusdata.SetPrimaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrimary not implemented")
}
func (UnimplementedMultipoolerConsensusServer) mustEmbedUnimplementedMultipoolerConsensusServer() {}
func (UnimplementedMultipoolerConsensusServer) testEmbeddedByValue()                              {}

// UnsafeMultipoolerConsensusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultipoolerConsensusServer will
// result in compilation errors.
type UnsafeMultipoolerConsensusServer interface {
	mustEmbedUnimplementedMultipoolerConsensusServer()
}

func RegisterMultipoolerConsensusServer(s grpc.ServiceRegistrar, srv MultipoolerConsensusServer) {
	// If the following call pancis, it indicates UnimplementedMultipoolerConsensusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultipoolerConsensus_ServiceDesc, srv)
}

func _MultipoolerConsensus_UpdateConsensusRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.UpdateConsensusRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerConsensusServer).UpdateConsensusRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerConsensus_UpdateConsensusRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerConsensusServer).UpdateConsensusRule(ctx, req.(*multipoolermanagerdata.UpdateConsensusRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerConsensus_Recruit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(consensusdata.RecruitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerConsensusServer).Recruit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerConsensus_Recruit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerConsensusServer).Recruit(ctx, req.(*consensusdata.RecruitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerConsensus_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(consensusdata.PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerConsensusServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerConsensus_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerConsensusServer).Promote(ctx, req.(*consensusdata.PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerConsensus_SetPrimary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(consensusdata.SetPrimaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerConsensusServer).SetPrimary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerConsensus_SetPrimary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerConsensusServer).SetPrimary(ctx, req.(*consensusdata.SetPrimaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultipoolerConsensus_ServiceDesc is the grpc.ServiceDesc for MultipoolerConsensus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultipoolerConsensus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.MultipoolerConsensus",
	HandlerType: (*MultipoolerConsensusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConsensusRule",
			Handler:    _MultipoolerConsensus_UpdateConsensusRule_Handler,
		},
		{
			MethodName: "Recruit",
			Handler:    _MultipoolerConsensus_Recruit_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _MultipoolerConsensus_Promote_Handler,
		},
		{
			MethodName: "SetPrimary",
			Handler:    _MultipoolerConsensus_SetPrimary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensusservice.proto",
}
