// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: consensusservice.proto

package consensus

import (
	consensusdata "github.com/multigres/multigres/go/pb/consensusdata"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_consensusservice_proto protoreflect.FileDescriptor

const file_consensusservice_proto_rawDesc = "" +
	"\n" +
	"\x16consensusservice.proto\x12\tconsensus\x1a\x13consensusdata.proto\x1a\x1cmultipoolermanagerdata.proto2\xfd\x02\n" +
	"\x14MultipoolerConsensus\x12~\n" +
	"\x13UpdateConsensusRule\x122.multipoolermanagerdata.UpdateConsensusRuleRequest\x1a3.multipoolermanagerdata.UpdateConsensusRuleResponse\x12H\n" +
	"\aRecruit\x12\x1d.consensusdata.RecruitRequest\x1a\x1e.consensusdata.RecruitResponse\x12H\n" +
	"\aPromote\x12\x1d.consensusdata.PromoteRequest\x1a\x1e.consensusdata.PromoteResponse\x12Q\n" +
	"\n" +
	"SetPrimary\x12 .consensusdata.SetPrimaryRequest\x1a!.consensusdata.SetPrimaryResponseB0Z.github.com/multigres/multigres/go/pb/consensusb\x06proto3"

var file_consensusservice_proto_goTypes = []any{
	(*multipoolermanagerdata.UpdateConsensusRuleRequest)(nil),  // 0: multipoolermanagerdata.UpdateConsensusRuleRequest
	(*consensusdata.RecruitRequest)(nil),                       // 1: consensusdata.RecruitRequest
	(*consensusdata.PromoteRequest)(nil),                       // 2: consensusdata.PromoteRequest
	(*consensusdata.SetPrimaryRequest)(nil),                    // 3: consensusdata.SetPrimaryRequest
	(*multipoolermanagerdata.UpdateConsensusRuleResponse)(nil), // 4: multipoolermanagerdata.UpdateConsensusRuleResponse
	(*consensusdata.RecruitResponse)(nil),                      // 5: consensusdata.RecruitResponse
	(*consensusdata.PromoteResponse)(nil),                      // 6: consensusdata.PromoteResponse
	(*consensusdata.SetPrimaryResponse)(nil),                   // 7: consensusdata.SetPrimaryResponse
}
var file_consensusservice_proto_depIdxs = []int32{
	0, // 0: consensus.MultipoolerConsensus.UpdateConsensusRule:input_type -> multipoolermanagerdata.UpdateConsensusRuleRequest
	1, // 1: consensus.MultipoolerConsensus.Recruit:input_type -> consensusdata.RecruitRequest
	2, // 2: consensus.MultipoolerConsensus.Promote:input_type -> consensusdata.PromoteRequest
	3, // 3: consensus.MultipoolerConsensus.SetPrimary:input_type -> consensusdata.SetPrimaryRequest
	4, // 4: consensus.MultipoolerConsensus.UpdateConsensusRule:output_type -> multipoolermanagerdata.UpdateConsensusRuleResponse
	5, // 5: consensus.MultipoolerConsensus.Recruit:output_type -> consensusdata.RecruitResponse
	6, // 6: consensus.MultipoolerConsensus.Promote:output_type -> consensusdata.PromoteResponse
	7, // 7: consensus.MultipoolerConsensus.SetPrimary:output_type -> consensusdata.SetPrimaryResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consensusservice_proto_init() }
func file_consensusservice_proto_init() {
	if File_consensusservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensusservice_proto_rawDesc), len(file_consensusservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensusservice_proto_goTypes,
		DependencyIndexes: file_consensusservice_proto_depIdxs,
	}.Build()
	File_consensusservice_proto = out.File
	file_consensusservice_proto_goTypes = nil
	file_consensusservice_proto_depIdxs = nil
}
