//
//Copyright 2026 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// This file contains the RPC service definition for multigateway.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: multigatewayservice.proto

package multigatewayserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	multigatewayservice "github.com/multigres/multigres/go/pb/multigatewayservice"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MultigatewayServiceName is the fully-qualified name of the MultigatewayService service.
	MultigatewayServiceName = "multigatewayservice.MultigatewayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MultigatewayServiceCancelQueryProcedure is the fully-qualified name of the MultigatewayService's
	// CancelQuery RPC.
	MultigatewayServiceCancelQueryProcedure = "/multigatewayservice.MultigatewayService/CancelQuery"
)

// MultigatewayServiceClient is a client for the multigatewayservice.MultigatewayService service.
type MultigatewayServiceClient interface {
	// CancelQuery forwards a cancel request to the gateway that owns the connection.
	CancelQuery(context.Context, *connect.Request[multigatewayservice.CancelQueryRequest]) (*connect.Response[multigatewayservice.CancelQueryResponse], error)
}

// NewMultigatewayServiceClient constructs a client for the multigatewayservice.MultigatewayService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMultigatewayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MultigatewayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	multigatewayServiceMethods := multigatewayservice.File_multigatewayservice_proto.Services().ByName("MultigatewayService").Methods()
	return &multigatewayServiceClient{
		cancelQuery: connect.NewClient[multigatewayservice.CancelQueryRequest, multigatewayservice.CancelQueryResponse](
			httpClient,
			baseURL+MultigatewayServiceCancelQueryProcedure,
			connect.WithSchema(multigatewayServiceMethods.ByName("CancelQuery")),
			connect.WithClientOptions(opts...),
		),
	}
}

// multigatewayServiceClient implements MultigatewayServiceClient.
type multigatewayServiceClient struct {
	cancelQuery *connect.Client[multigatewayservice.CancelQueryRequest, multigatewayservice.CancelQueryResponse]
}

// CancelQuery calls multigatewayservice.MultigatewayService.CancelQuery.
func (c *multigatewayServiceClient) CancelQuery(ctx context.Context, req *connect.Request[multigatewayservice.CancelQueryRequest]) (*connect.Response[multigatewayservice.CancelQueryResponse], error) {
	return c.cancelQuery.CallUnary(ctx, req)
}

// MultigatewayServiceHandler is an implementation of the multigatewayservice.MultigatewayService
// service.
type MultigatewayServiceHandler interface {
	// CancelQuery forwards a cancel request to the gateway that owns the connection.
	CancelQuery(context.Context, *connect.Request[multigatewayservice.CancelQueryRequest]) (*connect.Response[multigatewayservice.CancelQueryResponse], error)
}

// NewMultigatewayServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMultigatewayServiceHandler(svc MultigatewayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	multigatewayServiceMethods := multigatewayservice.File_multigatewayservice_proto.Services().ByName("MultigatewayService").Methods()
	multigatewayServiceCancelQueryHandler := connect.NewUnaryHandler(
		MultigatewayServiceCancelQueryProcedure,
		svc.CancelQuery,
		connect.WithSchema(multigatewayServiceMethods.ByName("CancelQuery")),
		connect.WithHandlerOptions(opts...),
	)
	return "/multigatewayservice.MultigatewayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MultigatewayServiceCancelQueryProcedure:
			multigatewayServiceCancelQueryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMultigatewayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMultigatewayServiceHandler struct{}

func (UnimplementedMultigatewayServiceHandler) CancelQuery(context.Context, *connect.Request[multigatewayservice.CancelQueryRequest]) (*connect.Response[multigatewayservice.CancelQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multigatewayservice.MultigatewayService.CancelQuery is not implemented"))
}
