// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: serviceinfoservice.proto

package serviceinfoconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	serviceinfo "github.com/multigres/multigres/go/pb/serviceinfo"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceInfoName is the fully-qualified name of the ServiceInfo service.
	ServiceInfoName = "serviceinfo.ServiceInfo"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceInfoGetBuildInfoProcedure is the fully-qualified name of the ServiceInfo's GetBuildInfo
	// RPC.
	ServiceInfoGetBuildInfoProcedure = "/serviceinfo.ServiceInfo/GetBuildInfo"
)

// ServiceInfoClient is a client for the serviceinfo.ServiceInfo service.
type ServiceInfoClient interface {
	// GetBuildInfo returns the VCS revision and build metadata embedded in
	// the running binary.
	GetBuildInfo(context.Context, *connect.Request[serviceinfo.GetBuildInfoRequest]) (*connect.Response[serviceinfo.GetBuildInfoResponse], error)
}

// NewServiceInfoClient constructs a client for the serviceinfo.ServiceInfo service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceInfoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceInfoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceInfoMethods := serviceinfo.File_serviceinfoservice_proto.Services().ByName("ServiceInfo").Methods()
	return &serviceInfoClient{
		getBuildInfo: connect.NewClient[serviceinfo.GetBuildInfoRequest, serviceinfo.GetBuildInfoResponse](
			httpClient,
			baseURL+ServiceInfoGetBuildInfoProcedure,
			connect.WithSchema(serviceInfoMethods.ByName("GetBuildInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceInfoClient implements ServiceInfoClient.
type serviceInfoClient struct {
	getBuildInfo *connect.Client[serviceinfo.GetBuildInfoRequest, serviceinfo.GetBuildInfoResponse]
}

// GetBuildInfo calls serviceinfo.ServiceInfo.GetBuildInfo.
func (c *serviceInfoClient) GetBuildInfo(ctx context.Context, req *connect.Request[serviceinfo.GetBuildInfoRequest]) (*connect.Response[serviceinfo.GetBuildInfoResponse], error) {
	return c.getBuildInfo.CallUnary(ctx, req)
}

// ServiceInfoHandler is an implementation of the serviceinfo.ServiceInfo service.
type ServiceInfoHandler interface {
	// GetBuildInfo returns the VCS revision and build metadata embedded in
	// the running binary.
	GetBuildInfo(context.Context, *connect.Request[serviceinfo.GetBuildInfoRequest]) (*connect.Response[serviceinfo.GetBuildInfoResponse], error)
}

// NewServiceInfoHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceInfoHandler(svc ServiceInfoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceInfoMethods := serviceinfo.File_serviceinfoservice_proto.Services().ByName("ServiceInfo").Methods()
	serviceInfoGetBuildInfoHandler := connect.NewUnaryHandler(
		ServiceInfoGetBuildInfoProcedure,
		svc.GetBuildInfo,
		connect.WithSchema(serviceInfoMethods.ByName("GetBuildInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/serviceinfo.ServiceInfo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceInfoGetBuildInfoProcedure:
			serviceInfoGetBuildInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceInfoHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceInfoHandler struct{}

func (UnimplementedServiceInfoHandler) GetBuildInfo(context.Context, *connect.Request[serviceinfo.GetBuildInfoRequest]) (*connect.Response[serviceinfo.GetBuildInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("serviceinfo.ServiceInfo.GetBuildInfo is not implemented"))
}
