//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// This file contains the RPC service definition for multipooler.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: multipoolerservice.proto

package multipoolerserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	multipoolerservice "github.com/multigres/multigres/go/pb/multipoolerservice"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MultipoolerServiceName is the fully-qualified name of the MultipoolerService service.
	MultipoolerServiceName = "multipoolerservice.MultipoolerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MultipoolerServiceExecuteQueryProcedure is the fully-qualified name of the MultipoolerService's
	// ExecuteQuery RPC.
	MultipoolerServiceExecuteQueryProcedure = "/multipoolerservice.MultipoolerService/ExecuteQuery"
	// MultipoolerServiceStreamExecuteProcedure is the fully-qualified name of the MultipoolerService's
	// StreamExecute RPC.
	MultipoolerServiceStreamExecuteProcedure = "/multipoolerservice.MultipoolerService/StreamExecute"
	// MultipoolerServicePortalStreamExecuteProcedure is the fully-qualified name of the
	// MultipoolerService's PortalStreamExecute RPC.
	MultipoolerServicePortalStreamExecuteProcedure = "/multipoolerservice.MultipoolerService/PortalStreamExecute"
	// MultipoolerServiceDescribeProcedure is the fully-qualified name of the MultipoolerService's
	// Describe RPC.
	MultipoolerServiceDescribeProcedure = "/multipoolerservice.MultipoolerService/Describe"
	// MultipoolerServiceGetAuthCredentialsProcedure is the fully-qualified name of the
	// MultipoolerService's GetAuthCredentials RPC.
	MultipoolerServiceGetAuthCredentialsProcedure = "/multipoolerservice.MultipoolerService/GetAuthCredentials"
	// MultipoolerServiceCopyBidiExecuteProcedure is the fully-qualified name of the
	// MultipoolerService's CopyBidiExecute RPC.
	MultipoolerServiceCopyBidiExecuteProcedure = "/multipoolerservice.MultipoolerService/CopyBidiExecute"
	// MultipoolerServiceStreamReplicationProcedure is the fully-qualified name of the
	// MultipoolerService's StreamReplication RPC.
	MultipoolerServiceStreamReplicationProcedure = "/multipoolerservice.MultipoolerService/StreamReplication"
	// MultipoolerServiceConcludeTransactionProcedure is the fully-qualified name of the
	// MultipoolerService's ConcludeTransaction RPC.
	MultipoolerServiceConcludeTransactionProcedure = "/multipoolerservice.MultipoolerService/ConcludeTransaction"
	// MultipoolerServiceDiscardTempTablesProcedure is the fully-qualified name of the
	// MultipoolerService's DiscardTempTables RPC.
	MultipoolerServiceDiscardTempTablesProcedure = "/multipoolerservice.MultipoolerService/DiscardTempTables"
	// MultipoolerServiceReleaseReservedConnectionProcedure is the fully-qualified name of the
	// MultipoolerService's ReleaseReservedConnection RPC.
	MultipoolerServiceReleaseReservedConnectionProcedure = "/multipoolerservice.MultipoolerService/ReleaseReservedConnection"
	// MultipoolerServiceStreamPoolerHealthProcedure is the fully-qualified name of the
	// MultipoolerService's StreamPoolerHealth RPC.
	MultipoolerServiceStreamPoolerHealthProcedure = "/multipoolerservice.MultipoolerService/StreamPoolerHealth"
	// MultipoolerServiceNotificationStreamProcedure is the fully-qualified name of the
	// MultipoolerService's NotificationStream RPC.
	MultipoolerServiceNotificationStreamProcedure = "/multipoolerservice.MultipoolerService/NotificationStream"
)

// MultipoolerServiceClient is a client for the multipoolerservice.MultipoolerService service.
type MultipoolerServiceClient interface {
	// ExecuteQuery executes a SQL query and returns the result
	// This should be used sparingly only when we know the result set is small,
	// otherwise StreamExecute should be used.
	ExecuteQuery(context.Context, *connect.Request[multipoolerservice.ExecuteQueryRequest]) (*connect.Response[multipoolerservice.ExecuteQueryResponse], error)
	// StreamExecute executes a SQL query and streams the results back
	StreamExecute(context.Context, *connect.Request[multipoolerservice.StreamExecuteRequest]) (*connect.ServerStreamForClient[multipoolerservice.StreamExecuteResponse], error)
	// PortalStreamExecute executes a portal (bound prepared statement) and streams results
	// Returns reserved connection information for session affinity
	PortalStreamExecute(context.Context, *connect.Request[multipoolerservice.PortalStreamExecuteRequest]) (*connect.ServerStreamForClient[multipoolerservice.PortalStreamExecuteResponse], error)
	// Describe returns metadata about a prepared statement or portal
	Describe(context.Context, *connect.Request[multipoolerservice.DescribeRequest]) (*connect.Response[multipoolerservice.DescribeResponse], error)
	// GetAuthCredentials retrieves authentication credentials for a user.
	// Used by multigateway to get SCRAM password hashes for client authentication.
	//
	// NOTE: This API may change. Currently fetches credentials one user at a time.
	// Future iterations could switch to a streaming model where multigateway maintains
	// an up-to-date cache of all password hashes and by real-time updates from multipooler
	// when any credentials change.
	GetAuthCredentials(context.Context, *connect.Request[multipoolerservice.GetAuthCredentialsRequest]) (*connect.Response[multipoolerservice.GetAuthCredentialsResponse], error)
	// CopyBidiExecute handles bidirectional streaming operations (e.g., COPY commands).
	// The gateway sends the initial command and then streams data/messages.
	// The pooler responds with protocol-specific messages and final result.
	CopyBidiExecute(context.Context) *connect.BidiStreamForClient[multipoolerservice.CopyBidiExecuteRequest, multipoolerservice.CopyBidiExecuteResponse]
	// StreamReplication tunnels the raw PostgreSQL replication wire protocol as
	// opaque bytes between the gateway and a pinned replication=database backend.
	// The pooler does not interpret the replication sub-protocol; bytes flow
	// verbatim in both directions. Used for logical replication (Realtime).
	StreamReplication(context.Context) *connect.BidiStreamForClient[multipoolerservice.StreamReplicationRequest, multipoolerservice.StreamReplicationResponse]
	// ConcludeTransaction concludes a transaction on a reserved connection with COMMIT or ROLLBACK.
	// The connection may remain reserved if there are other reasons to keep it (e.g., temp tables).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	ConcludeTransaction(context.Context, *connect.Request[multipoolerservice.ConcludeTransactionRequest]) (*connect.Response[multipoolerservice.ConcludeTransactionResponse], error)
	// DiscardTempTables sends DISCARD TEMP on a reserved connection and removes the temp table reason.
	// The connection may remain reserved if there are other reasons to keep it (e.g., active transaction).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	DiscardTempTables(context.Context, *connect.Request[multipoolerservice.DiscardTempTablesRequest]) (*connect.Response[multipoolerservice.DiscardTempTablesResponse], error)
	// ReleaseReservedConnection forcefully releases a reserved connection regardless of reason.
	// Used during client disconnect to clean up all reserved connections on the multipooler.
	// If the connection has a transaction, ROLLBACK is executed.
	// If the connection has an active COPY, CopyFail is sent.
	// If the connection has portals, they are released.
	// If any cleanup step fails, the connection is tainted and closed.
	ReleaseReservedConnection(context.Context, *connect.Request[multipoolerservice.ReleaseReservedConnectionRequest]) (*connect.Response[multipoolerservice.ReleaseReservedConnectionResponse], error)
	// StreamPoolerHealth streams health updates from the multipooler.
	//
	// The server sends an initial health response immediately upon connection,
	// then pushes updates whenever the health state changes. If no state change
	// occurs within the heartbeat interval, the server sends a heartbeat to
	// confirm the stream is alive.
	//
	// Clients MUST implement a staleness timeout. The recommended timeout is provided
	// in recommended_staleness_timeout in each response. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	//
	// Each response contains the full health state (not incremental updates).
	StreamPoolerHealth(context.Context, *connect.Request[multipoolerservice.StreamPoolerHealthRequest]) (*connect.ServerStreamForClient[multipoolerservice.StreamPoolerHealthResponse], error)
	// NotificationStream opens a bidirectional stream for one gateway client
	// session. Subscription updates and notification delivery share one stream so
	// notifications across channels preserve PostgreSQL delivery order.
	NotificationStream(context.Context) *connect.BidiStreamForClient[multipoolerservice.NotificationStreamRequest, multipoolerservice.NotificationStreamResponse]
}

// NewMultipoolerServiceClient constructs a client for the multipoolerservice.MultipoolerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMultipoolerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MultipoolerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	multipoolerServiceMethods := multipoolerservice.File_multipoolerservice_proto.Services().ByName("MultipoolerService").Methods()
	return &multipoolerServiceClient{
		executeQuery: connect.NewClient[multipoolerservice.ExecuteQueryRequest, multipoolerservice.ExecuteQueryResponse](
			httpClient,
			baseURL+MultipoolerServiceExecuteQueryProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("ExecuteQuery")),
			connect.WithClientOptions(opts...),
		),
		streamExecute: connect.NewClient[multipoolerservice.StreamExecuteRequest, multipoolerservice.StreamExecuteResponse](
			httpClient,
			baseURL+MultipoolerServiceStreamExecuteProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("StreamExecute")),
			connect.WithClientOptions(opts...),
		),
		portalStreamExecute: connect.NewClient[multipoolerservice.PortalStreamExecuteRequest, multipoolerservice.PortalStreamExecuteResponse](
			httpClient,
			baseURL+MultipoolerServicePortalStreamExecuteProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("PortalStreamExecute")),
			connect.WithClientOptions(opts...),
		),
		describe: connect.NewClient[multipoolerservice.DescribeRequest, multipoolerservice.DescribeResponse](
			httpClient,
			baseURL+MultipoolerServiceDescribeProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("Describe")),
			connect.WithClientOptions(opts...),
		),
		getAuthCredentials: connect.NewClient[multipoolerservice.GetAuthCredentialsRequest, multipoolerservice.GetAuthCredentialsResponse](
			httpClient,
			baseURL+MultipoolerServiceGetAuthCredentialsProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("GetAuthCredentials")),
			connect.WithClientOptions(opts...),
		),
		copyBidiExecute: connect.NewClient[multipoolerservice.CopyBidiExecuteRequest, multipoolerservice.CopyBidiExecuteResponse](
			httpClient,
			baseURL+MultipoolerServiceCopyBidiExecuteProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("CopyBidiExecute")),
			connect.WithClientOptions(opts...),
		),
		streamReplication: connect.NewClient[multipoolerservice.StreamReplicationRequest, multipoolerservice.StreamReplicationResponse](
			httpClient,
			baseURL+MultipoolerServiceStreamReplicationProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("StreamReplication")),
			connect.WithClientOptions(opts...),
		),
		concludeTransaction: connect.NewClient[multipoolerservice.ConcludeTransactionRequest, multipoolerservice.ConcludeTransactionResponse](
			httpClient,
			baseURL+MultipoolerServiceConcludeTransactionProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("ConcludeTransaction")),
			connect.WithClientOptions(opts...),
		),
		discardTempTables: connect.NewClient[multipoolerservice.DiscardTempTablesRequest, multipoolerservice.DiscardTempTablesResponse](
			httpClient,
			baseURL+MultipoolerServiceDiscardTempTablesProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("DiscardTempTables")),
			connect.WithClientOptions(opts...),
		),
		releaseReservedConnection: connect.NewClient[multipoolerservice.ReleaseReservedConnectionRequest, multipoolerservice.ReleaseReservedConnectionResponse](
			httpClient,
			baseURL+MultipoolerServiceReleaseReservedConnectionProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("ReleaseReservedConnection")),
			connect.WithClientOptions(opts...),
		),
		streamPoolerHealth: connect.NewClient[multipoolerservice.StreamPoolerHealthRequest, multipoolerservice.StreamPoolerHealthResponse](
			httpClient,
			baseURL+MultipoolerServiceStreamPoolerHealthProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("StreamPoolerHealth")),
			connect.WithClientOptions(opts...),
		),
		notificationStream: connect.NewClient[multipoolerservice.NotificationStreamRequest, multipoolerservice.NotificationStreamResponse](
			httpClient,
			baseURL+MultipoolerServiceNotificationStreamProcedure,
			connect.WithSchema(multipoolerServiceMethods.ByName("NotificationStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// multipoolerServiceClient implements MultipoolerServiceClient.
type multipoolerServiceClient struct {
	executeQuery              *connect.Client[multipoolerservice.ExecuteQueryRequest, multipoolerservice.ExecuteQueryResponse]
	streamExecute             *connect.Client[multipoolerservice.StreamExecuteRequest, multipoolerservice.StreamExecuteResponse]
	portalStreamExecute       *connect.Client[multipoolerservice.PortalStreamExecuteRequest, multipoolerservice.PortalStreamExecuteResponse]
	describe                  *connect.Client[multipoolerservice.DescribeRequest, multipoolerservice.DescribeResponse]
	getAuthCredentials        *connect.Client[multipoolerservice.GetAuthCredentialsRequest, multipoolerservice.GetAuthCredentialsResponse]
	copyBidiExecute           *connect.Client[multipoolerservice.CopyBidiExecuteRequest, multipoolerservice.CopyBidiExecuteResponse]
	streamReplication         *connect.Client[multipoolerservice.StreamReplicationRequest, multipoolerservice.StreamReplicationResponse]
	concludeTransaction       *connect.Client[multipoolerservice.ConcludeTransactionRequest, multipoolerservice.ConcludeTransactionResponse]
	discardTempTables         *connect.Client[multipoolerservice.DiscardTempTablesRequest, multipoolerservice.DiscardTempTablesResponse]
	releaseReservedConnection *connect.Client[multipoolerservice.ReleaseReservedConnectionRequest, multipoolerservice.ReleaseReservedConnectionResponse]
	streamPoolerHealth        *connect.Client[multipoolerservice.StreamPoolerHealthRequest, multipoolerservice.StreamPoolerHealthResponse]
	notificationStream        *connect.Client[multipoolerservice.NotificationStreamRequest, multipoolerservice.NotificationStreamResponse]
}

// ExecuteQuery calls multipoolerservice.MultipoolerService.ExecuteQuery.
func (c *multipoolerServiceClient) ExecuteQuery(ctx context.Context, req *connect.Request[multipoolerservice.ExecuteQueryRequest]) (*connect.Response[multipoolerservice.ExecuteQueryResponse], error) {
	return c.executeQuery.CallUnary(ctx, req)
}

// StreamExecute calls multipoolerservice.MultipoolerService.StreamExecute.
func (c *multipoolerServiceClient) StreamExecute(ctx context.Context, req *connect.Request[multipoolerservice.StreamExecuteRequest]) (*connect.ServerStreamForClient[multipoolerservice.StreamExecuteResponse], error) {
	return c.streamExecute.CallServerStream(ctx, req)
}

// PortalStreamExecute calls multipoolerservice.MultipoolerService.PortalStreamExecute.
func (c *multipoolerServiceClient) PortalStreamExecute(ctx context.Context, req *connect.Request[multipoolerservice.PortalStreamExecuteRequest]) (*connect.ServerStreamForClient[multipoolerservice.PortalStreamExecuteResponse], error) {
	return c.portalStreamExecute.CallServerStream(ctx, req)
}

// Describe calls multipoolerservice.MultipoolerService.Describe.
func (c *multipoolerServiceClient) Describe(ctx context.Context, req *connect.Request[multipoolerservice.DescribeRequest]) (*connect.Response[multipoolerservice.DescribeResponse], error) {
	return c.describe.CallUnary(ctx, req)
}

// GetAuthCredentials calls multipoolerservice.MultipoolerService.GetAuthCredentials.
func (c *multipoolerServiceClient) GetAuthCredentials(ctx context.Context, req *connect.Request[multipoolerservice.GetAuthCredentialsRequest]) (*connect.Response[multipoolerservice.GetAuthCredentialsResponse], error) {
	return c.getAuthCredentials.CallUnary(ctx, req)
}

// CopyBidiExecute calls multipoolerservice.MultipoolerService.CopyBidiExecute.
func (c *multipoolerServiceClient) CopyBidiExecute(ctx context.Context) *connect.BidiStreamForClient[multipoolerservice.CopyBidiExecuteRequest, multipoolerservice.CopyBidiExecuteResponse] {
	return c.copyBidiExecute.CallBidiStream(ctx)
}

// StreamReplication calls multipoolerservice.MultipoolerService.StreamReplication.
func (c *multipoolerServiceClient) StreamReplication(ctx context.Context) *connect.BidiStreamForClient[multipoolerservice.StreamReplicationRequest, multipoolerservice.StreamReplicationResponse] {
	return c.streamReplication.CallBidiStream(ctx)
}

// ConcludeTransaction calls multipoolerservice.MultipoolerService.ConcludeTransaction.
func (c *multipoolerServiceClient) ConcludeTransaction(ctx context.Context, req *connect.Request[multipoolerservice.ConcludeTransactionRequest]) (*connect.Response[multipoolerservice.ConcludeTransactionResponse], error) {
	return c.concludeTransaction.CallUnary(ctx, req)
}

// DiscardTempTables calls multipoolerservice.MultipoolerService.DiscardTempTables.
func (c *multipoolerServiceClient) DiscardTempTables(ctx context.Context, req *connect.Request[multipoolerservice.DiscardTempTablesRequest]) (*connect.Response[multipoolerservice.DiscardTempTablesResponse], error) {
	return c.discardTempTables.CallUnary(ctx, req)
}

// ReleaseReservedConnection calls multipoolerservice.MultipoolerService.ReleaseReservedConnection.
func (c *multipoolerServiceClient) ReleaseReservedConnection(ctx context.Context, req *connect.Request[multipoolerservice.ReleaseReservedConnectionRequest]) (*connect.Response[multipoolerservice.ReleaseReservedConnectionResponse], error) {
	return c.releaseReservedConnection.CallUnary(ctx, req)
}

// StreamPoolerHealth calls multipoolerservice.MultipoolerService.StreamPoolerHealth.
func (c *multipoolerServiceClient) StreamPoolerHealth(ctx context.Context, req *connect.Request[multipoolerservice.StreamPoolerHealthRequest]) (*connect.ServerStreamForClient[multipoolerservice.StreamPoolerHealthResponse], error) {
	return c.streamPoolerHealth.CallServerStream(ctx, req)
}

// NotificationStream calls multipoolerservice.MultipoolerService.NotificationStream.
func (c *multipoolerServiceClient) NotificationStream(ctx context.Context) *connect.BidiStreamForClient[multipoolerservice.NotificationStreamRequest, multipoolerservice.NotificationStreamResponse] {
	return c.notificationStream.CallBidiStream(ctx)
}

// MultipoolerServiceHandler is an implementation of the multipoolerservice.MultipoolerService
// service.
type MultipoolerServiceHandler interface {
	// ExecuteQuery executes a SQL query and returns the result
	// This should be used sparingly only when we know the result set is small,
	// otherwise StreamExecute should be used.
	ExecuteQuery(context.Context, *connect.Request[multipoolerservice.ExecuteQueryRequest]) (*connect.Response[multipoolerservice.ExecuteQueryResponse], error)
	// StreamExecute executes a SQL query and streams the results back
	StreamExecute(context.Context, *connect.Request[multipoolerservice.StreamExecuteRequest], *connect.ServerStream[multipoolerservice.StreamExecuteResponse]) error
	// PortalStreamExecute executes a portal (bound prepared statement) and streams results
	// Returns reserved connection information for session affinity
	PortalStreamExecute(context.Context, *connect.Request[multipoolerservice.PortalStreamExecuteRequest], *connect.ServerStream[multipoolerservice.PortalStreamExecuteResponse]) error
	// Describe returns metadata about a prepared statement or portal
	Describe(context.Context, *connect.Request[multipoolerservice.DescribeRequest]) (*connect.Response[multipoolerservice.DescribeResponse], error)
	// GetAuthCredentials retrieves authentication credentials for a user.
	// Used by multigateway to get SCRAM password hashes for client authentication.
	//
	// NOTE: This API may change. Currently fetches credentials one user at a time.
	// Future iterations could switch to a streaming model where multigateway maintains
	// an up-to-date cache of all password hashes and by real-time updates from multipooler
	// when any credentials change.
	GetAuthCredentials(context.Context, *connect.Request[multipoolerservice.GetAuthCredentialsRequest]) (*connect.Response[multipoolerservice.GetAuthCredentialsResponse], error)
	// CopyBidiExecute handles bidirectional streaming operations (e.g., COPY commands).
	// The gateway sends the initial command and then streams data/messages.
	// The pooler responds with protocol-specific messages and final result.
	CopyBidiExecute(context.Context, *connect.BidiStream[multipoolerservice.CopyBidiExecuteRequest, multipoolerservice.CopyBidiExecuteResponse]) error
	// StreamReplication tunnels the raw PostgreSQL replication wire protocol as
	// opaque bytes between the gateway and a pinned replication=database backend.
	// The pooler does not interpret the replication sub-protocol; bytes flow
	// verbatim in both directions. Used for logical replication (Realtime).
	StreamReplication(context.Context, *connect.BidiStream[multipoolerservice.StreamReplicationRequest, multipoolerservice.StreamReplicationResponse]) error
	// ConcludeTransaction concludes a transaction on a reserved connection with COMMIT or ROLLBACK.
	// The connection may remain reserved if there are other reasons to keep it (e.g., temp tables).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	ConcludeTransaction(context.Context, *connect.Request[multipoolerservice.ConcludeTransactionRequest]) (*connect.Response[multipoolerservice.ConcludeTransactionResponse], error)
	// DiscardTempTables sends DISCARD TEMP on a reserved connection and removes the temp table reason.
	// The connection may remain reserved if there are other reasons to keep it (e.g., active transaction).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	DiscardTempTables(context.Context, *connect.Request[multipoolerservice.DiscardTempTablesRequest]) (*connect.Response[multipoolerservice.DiscardTempTablesResponse], error)
	// ReleaseReservedConnection forcefully releases a reserved connection regardless of reason.
	// Used during client disconnect to clean up all reserved connections on the multipooler.
	// If the connection has a transaction, ROLLBACK is executed.
	// If the connection has an active COPY, CopyFail is sent.
	// If the connection has portals, they are released.
	// If any cleanup step fails, the connection is tainted and closed.
	ReleaseReservedConnection(context.Context, *connect.Request[multipoolerservice.ReleaseReservedConnectionRequest]) (*connect.Response[multipoolerservice.ReleaseReservedConnectionResponse], error)
	// StreamPoolerHealth streams health updates from the multipooler.
	//
	// The server sends an initial health response immediately upon connection,
	// then pushes updates whenever the health state changes. If no state change
	// occurs within the heartbeat interval, the server sends a heartbeat to
	// confirm the stream is alive.
	//
	// Clients MUST implement a staleness timeout. The recommended timeout is provided
	// in recommended_staleness_timeout in each response. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	//
	// Each response contains the full health state (not incremental updates).
	StreamPoolerHealth(context.Context, *connect.Request[multipoolerservice.StreamPoolerHealthRequest], *connect.ServerStream[multipoolerservice.StreamPoolerHealthResponse]) error
	// NotificationStream opens a bidirectional stream for one gateway client
	// session. Subscription updates and notification delivery share one stream so
	// notifications across channels preserve PostgreSQL delivery order.
	NotificationStream(context.Context, *connect.BidiStream[multipoolerservice.NotificationStreamRequest, multipoolerservice.NotificationStreamResponse]) error
}

// NewMultipoolerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMultipoolerServiceHandler(svc MultipoolerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	multipoolerServiceMethods := multipoolerservice.File_multipoolerservice_proto.Services().ByName("MultipoolerService").Methods()
	multipoolerServiceExecuteQueryHandler := connect.NewUnaryHandler(
		MultipoolerServiceExecuteQueryProcedure,
		svc.ExecuteQuery,
		connect.WithSchema(multipoolerServiceMethods.ByName("ExecuteQuery")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceStreamExecuteHandler := connect.NewServerStreamHandler(
		MultipoolerServiceStreamExecuteProcedure,
		svc.StreamExecute,
		connect.WithSchema(multipoolerServiceMethods.ByName("StreamExecute")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServicePortalStreamExecuteHandler := connect.NewServerStreamHandler(
		MultipoolerServicePortalStreamExecuteProcedure,
		svc.PortalStreamExecute,
		connect.WithSchema(multipoolerServiceMethods.ByName("PortalStreamExecute")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceDescribeHandler := connect.NewUnaryHandler(
		MultipoolerServiceDescribeProcedure,
		svc.Describe,
		connect.WithSchema(multipoolerServiceMethods.ByName("Describe")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceGetAuthCredentialsHandler := connect.NewUnaryHandler(
		MultipoolerServiceGetAuthCredentialsProcedure,
		svc.GetAuthCredentials,
		connect.WithSchema(multipoolerServiceMethods.ByName("GetAuthCredentials")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceCopyBidiExecuteHandler := connect.NewBidiStreamHandler(
		MultipoolerServiceCopyBidiExecuteProcedure,
		svc.CopyBidiExecute,
		connect.WithSchema(multipoolerServiceMethods.ByName("CopyBidiExecute")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceStreamReplicationHandler := connect.NewBidiStreamHandler(
		MultipoolerServiceStreamReplicationProcedure,
		svc.StreamReplication,
		connect.WithSchema(multipoolerServiceMethods.ByName("StreamReplication")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceConcludeTransactionHandler := connect.NewUnaryHandler(
		MultipoolerServiceConcludeTransactionProcedure,
		svc.ConcludeTransaction,
		connect.WithSchema(multipoolerServiceMethods.ByName("ConcludeTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceDiscardTempTablesHandler := connect.NewUnaryHandler(
		MultipoolerServiceDiscardTempTablesProcedure,
		svc.DiscardTempTables,
		connect.WithSchema(multipoolerServiceMethods.ByName("DiscardTempTables")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceReleaseReservedConnectionHandler := connect.NewUnaryHandler(
		MultipoolerServiceReleaseReservedConnectionProcedure,
		svc.ReleaseReservedConnection,
		connect.WithSchema(multipoolerServiceMethods.ByName("ReleaseReservedConnection")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceStreamPoolerHealthHandler := connect.NewServerStreamHandler(
		MultipoolerServiceStreamPoolerHealthProcedure,
		svc.StreamPoolerHealth,
		connect.WithSchema(multipoolerServiceMethods.ByName("StreamPoolerHealth")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerServiceNotificationStreamHandler := connect.NewBidiStreamHandler(
		MultipoolerServiceNotificationStreamProcedure,
		svc.NotificationStream,
		connect.WithSchema(multipoolerServiceMethods.ByName("NotificationStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/multipoolerservice.MultipoolerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MultipoolerServiceExecuteQueryProcedure:
			multipoolerServiceExecuteQueryHandler.ServeHTTP(w, r)
		case MultipoolerServiceStreamExecuteProcedure:
			multipoolerServiceStreamExecuteHandler.ServeHTTP(w, r)
		case MultipoolerServicePortalStreamExecuteProcedure:
			multipoolerServicePortalStreamExecuteHandler.ServeHTTP(w, r)
		case MultipoolerServiceDescribeProcedure:
			multipoolerServiceDescribeHandler.ServeHTTP(w, r)
		case MultipoolerServiceGetAuthCredentialsProcedure:
			multipoolerServiceGetAuthCredentialsHandler.ServeHTTP(w, r)
		case MultipoolerServiceCopyBidiExecuteProcedure:
			multipoolerServiceCopyBidiExecuteHandler.ServeHTTP(w, r)
		case MultipoolerServiceStreamReplicationProcedure:
			multipoolerServiceStreamReplicationHandler.ServeHTTP(w, r)
		case MultipoolerServiceConcludeTransactionProcedure:
			multipoolerServiceConcludeTransactionHandler.ServeHTTP(w, r)
		case MultipoolerServiceDiscardTempTablesProcedure:
			multipoolerServiceDiscardTempTablesHandler.ServeHTTP(w, r)
		case MultipoolerServiceReleaseReservedConnectionProcedure:
			multipoolerServiceReleaseReservedConnectionHandler.ServeHTTP(w, r)
		case MultipoolerServiceStreamPoolerHealthProcedure:
			multipoolerServiceStreamPoolerHealthHandler.ServeHTTP(w, r)
		case MultipoolerServiceNotificationStreamProcedure:
			multipoolerServiceNotificationStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMultipoolerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMultipoolerServiceHandler struct{}

func (UnimplementedMultipoolerServiceHandler) ExecuteQuery(context.Context, *connect.Request[multipoolerservice.ExecuteQueryRequest]) (*connect.Response[multipoolerservice.ExecuteQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.ExecuteQuery is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) StreamExecute(context.Context, *connect.Request[multipoolerservice.StreamExecuteRequest], *connect.ServerStream[multipoolerservice.StreamExecuteResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.StreamExecute is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) PortalStreamExecute(context.Context, *connect.Request[multipoolerservice.PortalStreamExecuteRequest], *connect.ServerStream[multipoolerservice.PortalStreamExecuteResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.PortalStreamExecute is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) Describe(context.Context, *connect.Request[multipoolerservice.DescribeRequest]) (*connect.Response[multipoolerservice.DescribeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.Describe is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) GetAuthCredentials(context.Context, *connect.Request[multipoolerservice.GetAuthCredentialsRequest]) (*connect.Response[multipoolerservice.GetAuthCredentialsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.GetAuthCredentials is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) CopyBidiExecute(context.Context, *connect.BidiStream[multipoolerservice.CopyBidiExecuteRequest, multipoolerservice.CopyBidiExecuteResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.CopyBidiExecute is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) StreamReplication(context.Context, *connect.BidiStream[multipoolerservice.StreamReplicationRequest, multipoolerservice.StreamReplicationResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.StreamReplication is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) ConcludeTransaction(context.Context, *connect.Request[multipoolerservice.ConcludeTransactionRequest]) (*connect.Response[multipoolerservice.ConcludeTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.ConcludeTransaction is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) DiscardTempTables(context.Context, *connect.Request[multipoolerservice.DiscardTempTablesRequest]) (*connect.Response[multipoolerservice.DiscardTempTablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.DiscardTempTables is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) ReleaseReservedConnection(context.Context, *connect.Request[multipoolerservice.ReleaseReservedConnectionRequest]) (*connect.Response[multipoolerservice.ReleaseReservedConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.ReleaseReservedConnection is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) StreamPoolerHealth(context.Context, *connect.Request[multipoolerservice.StreamPoolerHealthRequest], *connect.ServerStream[multipoolerservice.StreamPoolerHealthResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.StreamPoolerHealth is not implemented"))
}

func (UnimplementedMultipoolerServiceHandler) NotificationStream(context.Context, *connect.BidiStream[multipoolerservice.NotificationStreamRequest, multipoolerservice.NotificationStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("multipoolerservice.MultipoolerService.NotificationStream is not implemented"))
}
