//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains the RPC service definition for multipooler.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multipoolerservice.proto

package multipoolerservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultipoolerService_ExecuteQuery_FullMethodName              = "/multipoolerservice.MultipoolerService/ExecuteQuery"
	MultipoolerService_StreamExecute_FullMethodName             = "/multipoolerservice.MultipoolerService/StreamExecute"
	MultipoolerService_PortalStreamExecute_FullMethodName       = "/multipoolerservice.MultipoolerService/PortalStreamExecute"
	MultipoolerService_Describe_FullMethodName                  = "/multipoolerservice.MultipoolerService/Describe"
	MultipoolerService_GetAuthCredentials_FullMethodName        = "/multipoolerservice.MultipoolerService/GetAuthCredentials"
	MultipoolerService_CopyBidiExecute_FullMethodName           = "/multipoolerservice.MultipoolerService/CopyBidiExecute"
	MultipoolerService_StreamReplication_FullMethodName         = "/multipoolerservice.MultipoolerService/StreamReplication"
	MultipoolerService_ConcludeTransaction_FullMethodName       = "/multipoolerservice.MultipoolerService/ConcludeTransaction"
	MultipoolerService_DiscardTempTables_FullMethodName         = "/multipoolerservice.MultipoolerService/DiscardTempTables"
	MultipoolerService_ReleaseReservedConnection_FullMethodName = "/multipoolerservice.MultipoolerService/ReleaseReservedConnection"
	MultipoolerService_StreamPoolerHealth_FullMethodName        = "/multipoolerservice.MultipoolerService/StreamPoolerHealth"
	MultipoolerService_NotificationStream_FullMethodName        = "/multipoolerservice.MultipoolerService/NotificationStream"
)

// MultipoolerServiceClient is the client API for MultipoolerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultipoolerService provides connection pooling and query execution
type MultipoolerServiceClient interface {
	// ExecuteQuery executes a SQL query and returns the result
	// This should be used sparingly only when we know the result set is small,
	// otherwise StreamExecute should be used.
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error)
	// StreamExecute executes a SQL query and streams the results back
	StreamExecute(ctx context.Context, in *StreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamExecuteResponse], error)
	// PortalStreamExecute executes a portal (bound prepared statement) and streams results
	// Returns reserved connection information for session affinity
	PortalStreamExecute(ctx context.Context, in *PortalStreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortalStreamExecuteResponse], error)
	// Describe returns metadata about a prepared statement or portal
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// GetAuthCredentials retrieves authentication credentials for a user.
	// Used by multigateway to get SCRAM password hashes for client authentication.
	//
	// NOTE: This API may change. Currently fetches credentials one user at a time.
	// Future iterations could switch to a streaming model where multigateway maintains
	// an up-to-date cache of all password hashes and by real-time updates from multipooler
	// when any credentials change.
	GetAuthCredentials(ctx context.Context, in *GetAuthCredentialsRequest, opts ...grpc.CallOption) (*GetAuthCredentialsResponse, error)
	// CopyBidiExecute handles bidirectional streaming operations (e.g., COPY commands).
	// The gateway sends the initial command and then streams data/messages.
	// The pooler responds with protocol-specific messages and final result.
	CopyBidiExecute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CopyBidiExecuteRequest, CopyBidiExecuteResponse], error)
	// StreamReplication tunnels the raw PostgreSQL replication wire protocol as
	// opaque bytes between the gateway and a pinned replication=database backend.
	// The pooler does not interpret the replication sub-protocol; bytes flow
	// verbatim in both directions. Used for logical replication (Realtime).
	StreamReplication(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamReplicationRequest, StreamReplicationResponse], error)
	// ConcludeTransaction concludes a transaction on a reserved connection with COMMIT or ROLLBACK.
	// The connection may remain reserved if there are other reasons to keep it (e.g., temp tables).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	ConcludeTransaction(ctx context.Context, in *ConcludeTransactionRequest, opts ...grpc.CallOption) (*ConcludeTransactionResponse, error)
	// DiscardTempTables sends DISCARD TEMP on a reserved connection and removes the temp table reason.
	// The connection may remain reserved if there are other reasons to keep it (e.g., active transaction).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	DiscardTempTables(ctx context.Context, in *DiscardTempTablesRequest, opts ...grpc.CallOption) (*DiscardTempTablesResponse, error)
	// ReleaseReservedConnection forcefully releases a reserved connection regardless of reason.
	// Used during client disconnect to clean up all reserved connections on the multipooler.
	// If the connection has a transaction, ROLLBACK is executed.
	// If the connection has an active COPY, CopyFail is sent.
	// If the connection has portals, they are released.
	// If any cleanup step fails, the connection is tainted and closed.
	ReleaseReservedConnection(ctx context.Context, in *ReleaseReservedConnectionRequest, opts ...grpc.CallOption) (*ReleaseReservedConnectionResponse, error)
	// StreamPoolerHealth streams health updates from the multipooler.
	//
	// The server sends an initial health response immediately upon connection,
	// then pushes updates whenever the health state changes. If no state change
	// occurs within the heartbeat interval, the server sends a heartbeat to
	// confirm the stream is alive.
	//
	// Clients MUST implement a staleness timeout. The recommended timeout is provided
	// in recommended_staleness_timeout in each response. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	//
	// Each response contains the full health state (not incremental updates).
	StreamPoolerHealth(ctx context.Context, in *StreamPoolerHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPoolerHealthResponse], error)
	// NotificationStream opens a bidirectional stream for one gateway client
	// session. Subscription updates and notification delivery share one stream so
	// notifications across channels preserve PostgreSQL delivery order.
	NotificationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NotificationStreamRequest, NotificationStreamResponse], error)
}

type multipoolerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultipoolerServiceClient(cc grpc.ClientConnInterface) MultipoolerServiceClient {
	return &multipoolerServiceClient{cc}
}

func (c *multipoolerServiceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteQueryResponse)
	err := c.cc.Invoke(ctx, MultipoolerService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerServiceClient) StreamExecute(ctx context.Context, in *StreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultipoolerService_ServiceDesc.Streams[0], MultipoolerService_StreamExecute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamExecuteRequest, StreamExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_StreamExecuteClient = grpc.ServerStreamingClient[StreamExecuteResponse]

func (c *multipoolerServiceClient) PortalStreamExecute(ctx context.Context, in *PortalStreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortalStreamExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultipoolerService_ServiceDesc.Streams[1], MultipoolerService_PortalStreamExecute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortalStreamExecuteRequest, PortalStreamExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_PortalStreamExecuteClient = grpc.ServerStreamingClient[PortalStreamExecuteResponse]

func (c *multipoolerServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, MultipoolerService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerServiceClient) GetAuthCredentials(ctx context.Context, in *GetAuthCredentialsRequest, opts ...grpc.CallOption) (*GetAuthCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthCredentialsResponse)
	err := c.cc.Invoke(ctx, MultipoolerService_GetAuthCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerServiceClient) CopyBidiExecute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CopyBidiExecuteRequest, CopyBidiExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultipoolerService_ServiceDesc.Streams[2], MultipoolerService_CopyBidiExecute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyBidiExecuteRequest, CopyBidiExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_CopyBidiExecuteClient = grpc.BidiStreamingClient[CopyBidiExecuteRequest, CopyBidiExecuteResponse]

func (c *multipoolerServiceClient) StreamReplication(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamReplicationRequest, StreamReplicationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultipoolerService_ServiceDesc.Streams[3], MultipoolerService_StreamReplication_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamReplicationRequest, StreamReplicationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_StreamReplicationClient = grpc.BidiStreamingClient[StreamReplicationRequest, StreamReplicationResponse]

func (c *multipoolerServiceClient) ConcludeTransaction(ctx context.Context, in *ConcludeTransactionRequest, opts ...grpc.CallOption) (*ConcludeTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConcludeTransactionResponse)
	err := c.cc.Invoke(ctx, MultipoolerService_ConcludeTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerServiceClient) DiscardTempTables(ctx context.Context, in *DiscardTempTablesRequest, opts ...grpc.CallOption) (*DiscardTempTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardTempTablesResponse)
	err := c.cc.Invoke(ctx, MultipoolerService_DiscardTempTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerServiceClient) ReleaseReservedConnection(ctx context.Context, in *ReleaseReservedConnectionRequest, opts ...grpc.CallOption) (*ReleaseReservedConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseReservedConnectionResponse)
	err := c.cc.Invoke(ctx, MultipoolerService_ReleaseReservedConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerServiceClient) StreamPoolerHealth(ctx context.Context, in *StreamPoolerHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPoolerHealthResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultipoolerService_ServiceDesc.Streams[4], MultipoolerService_StreamPoolerHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPoolerHealthRequest, StreamPoolerHealthResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_StreamPoolerHealthClient = grpc.ServerStreamingClient[StreamPoolerHealthResponse]

func (c *multipoolerServiceClient) NotificationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NotificationStreamRequest, NotificationStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultipoolerService_ServiceDesc.Streams[5], MultipoolerService_NotificationStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotificationStreamRequest, NotificationStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_NotificationStreamClient = grpc.BidiStreamingClient[NotificationStreamRequest, NotificationStreamResponse]

// MultipoolerServiceServer is the server API for MultipoolerService service.
// All implementations must embed UnimplementedMultipoolerServiceServer
// for forward compatibility.
//
// MultipoolerService provides connection pooling and query execution
type MultipoolerServiceServer interface {
	// ExecuteQuery executes a SQL query and returns the result
	// This should be used sparingly only when we know the result set is small,
	// otherwise StreamExecute should be used.
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error)
	// StreamExecute executes a SQL query and streams the results back
	StreamExecute(*StreamExecuteRequest, grpc.ServerStreamingServer[StreamExecuteResponse]) error
	// PortalStreamExecute executes a portal (bound prepared statement) and streams results
	// Returns reserved connection information for session affinity
	PortalStreamExecute(*PortalStreamExecuteRequest, grpc.ServerStreamingServer[PortalStreamExecuteResponse]) error
	// Describe returns metadata about a prepared statement or portal
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// GetAuthCredentials retrieves authentication credentials for a user.
	// Used by multigateway to get SCRAM password hashes for client authentication.
	//
	// NOTE: This API may change. Currently fetches credentials one user at a time.
	// Future iterations could switch to a streaming model where multigateway maintains
	// an up-to-date cache of all password hashes and by real-time updates from multipooler
	// when any credentials change.
	GetAuthCredentials(context.Context, *GetAuthCredentialsRequest) (*GetAuthCredentialsResponse, error)
	// CopyBidiExecute handles bidirectional streaming operations (e.g., COPY commands).
	// The gateway sends the initial command and then streams data/messages.
	// The pooler responds with protocol-specific messages and final result.
	CopyBidiExecute(grpc.BidiStreamingServer[CopyBidiExecuteRequest, CopyBidiExecuteResponse]) error
	// StreamReplication tunnels the raw PostgreSQL replication wire protocol as
	// opaque bytes between the gateway and a pinned replication=database backend.
	// The pooler does not interpret the replication sub-protocol; bytes flow
	// verbatim in both directions. Used for logical replication (Realtime).
	StreamReplication(grpc.BidiStreamingServer[StreamReplicationRequest, StreamReplicationResponse]) error
	// ConcludeTransaction concludes a transaction on a reserved connection with COMMIT or ROLLBACK.
	// The connection may remain reserved if there are other reasons to keep it (e.g., temp tables).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	ConcludeTransaction(context.Context, *ConcludeTransactionRequest) (*ConcludeTransactionResponse, error)
	// DiscardTempTables sends DISCARD TEMP on a reserved connection and removes the temp table reason.
	// The connection may remain reserved if there are other reasons to keep it (e.g., active transaction).
	// Returns the reserved state - if non-empty, the connection is still reserved.
	DiscardTempTables(context.Context, *DiscardTempTablesRequest) (*DiscardTempTablesResponse, error)
	// ReleaseReservedConnection forcefully releases a reserved connection regardless of reason.
	// Used during client disconnect to clean up all reserved connections on the multipooler.
	// If the connection has a transaction, ROLLBACK is executed.
	// If the connection has an active COPY, CopyFail is sent.
	// If the connection has portals, they are released.
	// If any cleanup step fails, the connection is tainted and closed.
	ReleaseReservedConnection(context.Context, *ReleaseReservedConnectionRequest) (*ReleaseReservedConnectionResponse, error)
	// StreamPoolerHealth streams health updates from the multipooler.
	//
	// The server sends an initial health response immediately upon connection,
	// then pushes updates whenever the health state changes. If no state change
	// occurs within the heartbeat interval, the server sends a heartbeat to
	// confirm the stream is alive.
	//
	// Clients MUST implement a staleness timeout. The recommended timeout is provided
	// in recommended_staleness_timeout in each response. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	//
	// Each response contains the full health state (not incremental updates).
	StreamPoolerHealth(*StreamPoolerHealthRequest, grpc.ServerStreamingServer[StreamPoolerHealthResponse]) error
	// NotificationStream opens a bidirectional stream for one gateway client
	// session. Subscription updates and notification delivery share one stream so
	// notifications across channels preserve PostgreSQL delivery order.
	NotificationStream(grpc.BidiStreamingServer[NotificationStreamRequest, NotificationStreamResponse]) error
	mustEmbedUnimplementedMultipoolerServiceServer()
}

// UnimplementedMultipoolerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultipoolerServiceServer struct{}

func (UnimplementedMultipoolerServiceServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedMultipoolerServiceServer) StreamExecute(*StreamExecuteRequest, grpc.ServerStreamingServer[StreamExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamExecute not implemented")
}
func (UnimplementedMultipoolerServiceServer) PortalStreamExecute(*PortalStreamExecuteRequest, grpc.ServerStreamingServer[PortalStreamExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PortalStreamExecute not implemented")
}
func (UnimplementedMultipoolerServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedMultipoolerServiceServer) GetAuthCredentials(context.Context, *GetAuthCredentialsRequest) (*GetAuthCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthCredentials not implemented")
}
func (UnimplementedMultipoolerServiceServer) CopyBidiExecute(grpc.BidiStreamingServer[CopyBidiExecuteRequest, CopyBidiExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CopyBidiExecute not implemented")
}
func (UnimplementedMultipoolerServiceServer) StreamReplication(grpc.BidiStreamingServer[StreamReplicationRequest, StreamReplicationResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamReplication not implemented")
}
func (UnimplementedMultipoolerServiceServer) ConcludeTransaction(context.Context, *ConcludeTransactionRequest) (*ConcludeTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConcludeTransaction not implemented")
}
func (UnimplementedMultipoolerServiceServer) DiscardTempTables(context.Context, *DiscardTempTablesRequest) (*DiscardTempTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscardTempTables not implemented")
}
func (UnimplementedMultipoolerServiceServer) ReleaseReservedConnection(context.Context, *ReleaseReservedConnectionRequest) (*ReleaseReservedConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseReservedConnection not implemented")
}
func (UnimplementedMultipoolerServiceServer) StreamPoolerHealth(*StreamPoolerHealthRequest, grpc.ServerStreamingServer[StreamPoolerHealthResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPoolerHealth not implemented")
}
func (UnimplementedMultipoolerServiceServer) NotificationStream(grpc.BidiStreamingServer[NotificationStreamRequest, NotificationStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method NotificationStream not implemented")
}
func (UnimplementedMultipoolerServiceServer) mustEmbedUnimplementedMultipoolerServiceServer() {}
func (UnimplementedMultipoolerServiceServer) testEmbeddedByValue()                            {}

// UnsafeMultipoolerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultipoolerServiceServer will
// result in compilation errors.
type UnsafeMultipoolerServiceServer interface {
	mustEmbedUnimplementedMultipoolerServiceServer()
}

func RegisterMultipoolerServiceServer(s grpc.ServiceRegistrar, srv MultipoolerServiceServer) {
	// If the following call pancis, it indicates UnimplementedMultipoolerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultipoolerService_ServiceDesc, srv)
}

func _MultipoolerService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerServiceServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerService_StreamExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MultipoolerServiceServer).StreamExecute(m, &grpc.GenericServerStream[StreamExecuteRequest, StreamExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_StreamExecuteServer = grpc.ServerStreamingServer[StreamExecuteResponse]

func _MultipoolerService_PortalStreamExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PortalStreamExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MultipoolerServiceServer).PortalStreamExecute(m, &grpc.GenericServerStream[PortalStreamExecuteRequest, PortalStreamExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_PortalStreamExecuteServer = grpc.ServerStreamingServer[PortalStreamExecuteResponse]

func _MultipoolerService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerService_GetAuthCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerServiceServer).GetAuthCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerService_GetAuthCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerServiceServer).GetAuthCredentials(ctx, req.(*GetAuthCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerService_CopyBidiExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultipoolerServiceServer).CopyBidiExecute(&grpc.GenericServerStream[CopyBidiExecuteRequest, CopyBidiExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_CopyBidiExecuteServer = grpc.BidiStreamingServer[CopyBidiExecuteRequest, CopyBidiExecuteResponse]

func _MultipoolerService_StreamReplication_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultipoolerServiceServer).StreamReplication(&grpc.GenericServerStream[StreamReplicationRequest, StreamReplicationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_StreamReplicationServer = grpc.BidiStreamingServer[StreamReplicationRequest, StreamReplicationResponse]

func _MultipoolerService_ConcludeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcludeTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerServiceServer).ConcludeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerService_ConcludeTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerServiceServer).ConcludeTransaction(ctx, req.(*ConcludeTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerService_DiscardTempTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardTempTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerServiceServer).DiscardTempTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerService_DiscardTempTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerServiceServer).DiscardTempTables(ctx, req.(*DiscardTempTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerService_ReleaseReservedConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseReservedConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerServiceServer).ReleaseReservedConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerService_ReleaseReservedConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerServiceServer).ReleaseReservedConnection(ctx, req.(*ReleaseReservedConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerService_StreamPoolerHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPoolerHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MultipoolerServiceServer).StreamPoolerHealth(m, &grpc.GenericServerStream[StreamPoolerHealthRequest, StreamPoolerHealthResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_StreamPoolerHealthServer = grpc.ServerStreamingServer[StreamPoolerHealthResponse]

func _MultipoolerService_NotificationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultipoolerServiceServer).NotificationStream(&grpc.GenericServerStream[NotificationStreamRequest, NotificationStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerService_NotificationStreamServer = grpc.BidiStreamingServer[NotificationStreamRequest, NotificationStreamResponse]

// MultipoolerService_ServiceDesc is the grpc.ServiceDesc for MultipoolerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultipoolerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multipoolerservice.MultipoolerService",
	HandlerType: (*MultipoolerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _MultipoolerService_ExecuteQuery_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _MultipoolerService_Describe_Handler,
		},
		{
			MethodName: "GetAuthCredentials",
			Handler:    _MultipoolerService_GetAuthCredentials_Handler,
		},
		{
			MethodName: "ConcludeTransaction",
			Handler:    _MultipoolerService_ConcludeTransaction_Handler,
		},
		{
			MethodName: "DiscardTempTables",
			Handler:    _MultipoolerService_DiscardTempTables_Handler,
		},
		{
			MethodName: "ReleaseReservedConnection",
			Handler:    _MultipoolerService_ReleaseReservedConnection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExecute",
			Handler:       _MultipoolerService_StreamExecute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PortalStreamExecute",
			Handler:       _MultipoolerService_PortalStreamExecute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CopyBidiExecute",
			Handler:       _MultipoolerService_CopyBidiExecute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamReplication",
			Handler:       _MultipoolerService_StreamReplication_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamPoolerHealth",
			Handler:       _MultipoolerService_StreamPoolerHealth_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NotificationStream",
			Handler:       _MultipoolerService_NotificationStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "multipoolerservice.proto",
}
