// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multiorchservice.proto

package multiorch

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiorchService_GetShardStatus_FullMethodName           = "/multiorch.MultiorchService/GetShardStatus"
	MultiorchService_DisableRecovery_FullMethodName          = "/multiorch.MultiorchService/DisableRecovery"
	MultiorchService_EnableRecovery_FullMethodName           = "/multiorch.MultiorchService/EnableRecovery"
	MultiorchService_GetRecoveryStatus_FullMethodName        = "/multiorch.MultiorchService/GetRecoveryStatus"
	MultiorchService_TriggerRecoveryNow_FullMethodName       = "/multiorch.MultiorchService/TriggerRecoveryNow"
	MultiorchService_ApplyCertifiedRuleChange_FullMethodName = "/multiorch.MultiorchService/ApplyCertifiedRuleChange"
)

// MultiorchServiceClient is the client API for MultiorchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiorchService provides APIs for controlling multiorch behavior.
// This includes recovery control for testing and future operational features
// like forced failovers and chaos testing.
type MultiorchServiceClient interface {
	// GetShardStatus returns diagnostic information for a specific shard
	GetShardStatus(ctx context.Context, in *ShardStatusRequest, opts ...grpc.CallOption) (*ShardStatusResponse, error)
	// DisableRecovery stops the recovery engine from automatically repairing issues.
	// This is intended for testing scenarios where manual control over recovery is needed.
	// When this returns, no recovery actions are in-flight (strong synchronization guarantee).
	DisableRecovery(ctx context.Context, in *DisableRecoveryRequest, opts ...grpc.CallOption) (*DisableRecoveryResponse, error)
	// EnableRecovery resumes the recovery engine's automatic repair operations.
	EnableRecovery(ctx context.Context, in *EnableRecoveryRequest, opts ...grpc.CallOption) (*EnableRecoveryResponse, error)
	// GetRecoveryStatus returns whether recovery is currently enabled or disabled.
	GetRecoveryStatus(ctx context.Context, in *GetRecoveryStatusRequest, opts ...grpc.CallOption) (*GetRecoveryStatusResponse, error)
	// TriggerRecoveryNow immediately executes recovery operations and blocks until
	// either no problems remain or the request context times out.
	// This is intended for testing scenarios requiring deterministic recovery execution.
	//
	// Behavior:
	// - Re-polls all poolers to get fresh health state
	// - Runs recovery cycles repeatedly until no problems are detected
	// - Returns when either: (1) no problems remain, or (2) context times out
	// - If recovery is disabled, this temporarily enables it during this operation
	TriggerRecoveryNow(ctx context.Context, in *TriggerRecoveryNowRequest, opts ...grpc.CallOption) (*TriggerRecoveryNowResponse, error)
	// ApplyCertifiedRuleChange installs a new shard rule using an externally
	// certified revocation. Handles both initial leader appointment (term 0)
	// and stuck-quorum recovery (term > 0): the caller supplies the proposed
	// leader, cohort, and durability policy, plus a cert that attests to which
	// outgoing rule and WAL position the absent cohort members are frozen at.
	ApplyCertifiedRuleChange(ctx context.Context, in *ApplyCertifiedRuleChangeRequest, opts ...grpc.CallOption) (*ApplyCertifiedRuleChangeResponse, error)
}

type multiorchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiorchServiceClient(cc grpc.ClientConnInterface) MultiorchServiceClient {
	return &multiorchServiceClient{cc}
}

func (c *multiorchServiceClient) GetShardStatus(ctx context.Context, in *ShardStatusRequest, opts ...grpc.CallOption) (*ShardStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardStatusResponse)
	err := c.cc.Invoke(ctx, MultiorchService_GetShardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiorchServiceClient) DisableRecovery(ctx context.Context, in *DisableRecoveryRequest, opts ...grpc.CallOption) (*DisableRecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableRecoveryResponse)
	err := c.cc.Invoke(ctx, MultiorchService_DisableRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiorchServiceClient) EnableRecovery(ctx context.Context, in *EnableRecoveryRequest, opts ...grpc.CallOption) (*EnableRecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableRecoveryResponse)
	err := c.cc.Invoke(ctx, MultiorchService_EnableRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiorchServiceClient) GetRecoveryStatus(ctx context.Context, in *GetRecoveryStatusRequest, opts ...grpc.CallOption) (*GetRecoveryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecoveryStatusResponse)
	err := c.cc.Invoke(ctx, MultiorchService_GetRecoveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiorchServiceClient) TriggerRecoveryNow(ctx context.Context, in *TriggerRecoveryNowRequest, opts ...grpc.CallOption) (*TriggerRecoveryNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerRecoveryNowResponse)
	err := c.cc.Invoke(ctx, MultiorchService_TriggerRecoveryNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiorchServiceClient) ApplyCertifiedRuleChange(ctx context.Context, in *ApplyCertifiedRuleChangeRequest, opts ...grpc.CallOption) (*ApplyCertifiedRuleChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCertifiedRuleChangeResponse)
	err := c.cc.Invoke(ctx, MultiorchService_ApplyCertifiedRuleChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiorchServiceServer is the server API for MultiorchService service.
// All implementations must embed UnimplementedMultiorchServiceServer
// for forward compatibility.
//
// MultiorchService provides APIs for controlling multiorch behavior.
// This includes recovery control for testing and future operational features
// like forced failovers and chaos testing.
type MultiorchServiceServer interface {
	// GetShardStatus returns diagnostic information for a specific shard
	GetShardStatus(context.Context, *ShardStatusRequest) (*ShardStatusResponse, error)
	// DisableRecovery stops the recovery engine from automatically repairing issues.
	// This is intended for testing scenarios where manual control over recovery is needed.
	// When this returns, no recovery actions are in-flight (strong synchronization guarantee).
	DisableRecovery(context.Context, *DisableRecoveryRequest) (*DisableRecoveryResponse, error)
	// EnableRecovery resumes the recovery engine's automatic repair operations.
	EnableRecovery(context.Context, *EnableRecoveryRequest) (*EnableRecoveryResponse, error)
	// GetRecoveryStatus returns whether recovery is currently enabled or disabled.
	GetRecoveryStatus(context.Context, *GetRecoveryStatusRequest) (*GetRecoveryStatusResponse, error)
	// TriggerRecoveryNow immediately executes recovery operations and blocks until
	// either no problems remain or the request context times out.
	// This is intended for testing scenarios requiring deterministic recovery execution.
	//
	// Behavior:
	// - Re-polls all poolers to get fresh health state
	// - Runs recovery cycles repeatedly until no problems are detected
	// - Returns when either: (1) no problems remain, or (2) context times out
	// - If recovery is disabled, this temporarily enables it during this operation
	TriggerRecoveryNow(context.Context, *TriggerRecoveryNowRequest) (*TriggerRecoveryNowResponse, error)
	// ApplyCertifiedRuleChange installs a new shard rule using an externally
	// certified revocation. Handles both initial leader appointment (term 0)
	// and stuck-quorum recovery (term > 0): the caller supplies the proposed
	// leader, cohort, and durability policy, plus a cert that attests to which
	// outgoing rule and WAL position the absent cohort members are frozen at.
	ApplyCertifiedRuleChange(context.Context, *ApplyCertifiedRuleChangeRequest) (*ApplyCertifiedRuleChangeResponse, error)
	mustEmbedUnimplementedMultiorchServiceServer()
}

// UnimplementedMultiorchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiorchServiceServer struct{}

func (UnimplementedMultiorchServiceServer) GetShardStatus(context.Context, *ShardStatusRequest) (*ShardStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShardStatus not implemented")
}
func (UnimplementedMultiorchServiceServer) DisableRecovery(context.Context, *DisableRecoveryRequest) (*DisableRecoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableRecovery not implemented")
}
func (UnimplementedMultiorchServiceServer) EnableRecovery(context.Context, *EnableRecoveryRequest) (*EnableRecoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableRecovery not implemented")
}
func (UnimplementedMultiorchServiceServer) GetRecoveryStatus(context.Context, *GetRecoveryStatusRequest) (*GetRecoveryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecoveryStatus not implemented")
}
func (UnimplementedMultiorchServiceServer) TriggerRecoveryNow(context.Context, *TriggerRecoveryNowRequest) (*TriggerRecoveryNowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerRecoveryNow not implemented")
}
func (UnimplementedMultiorchServiceServer) ApplyCertifiedRuleChange(context.Context, *ApplyCertifiedRuleChangeRequest) (*ApplyCertifiedRuleChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyCertifiedRuleChange not implemented")
}
func (UnimplementedMultiorchServiceServer) mustEmbedUnimplementedMultiorchServiceServer() {}
func (UnimplementedMultiorchServiceServer) testEmbeddedByValue()                          {}

// UnsafeMultiorchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiorchServiceServer will
// result in compilation errors.
type UnsafeMultiorchServiceServer interface {
	mustEmbedUnimplementedMultiorchServiceServer()
}

func RegisterMultiorchServiceServer(s grpc.ServiceRegistrar, srv MultiorchServiceServer) {
	// If the following call pancis, it indicates UnimplementedMultiorchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiorchService_ServiceDesc, srv)
}

func _MultiorchService_GetShardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiorchServiceServer).GetShardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiorchService_GetShardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiorchServiceServer).GetShardStatus(ctx, req.(*ShardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiorchService_DisableRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiorchServiceServer).DisableRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiorchService_DisableRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiorchServiceServer).DisableRecovery(ctx, req.(*DisableRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiorchService_EnableRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiorchServiceServer).EnableRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiorchService_EnableRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiorchServiceServer).EnableRecovery(ctx, req.(*EnableRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiorchService_GetRecoveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecoveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiorchServiceServer).GetRecoveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiorchService_GetRecoveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiorchServiceServer).GetRecoveryStatus(ctx, req.(*GetRecoveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiorchService_TriggerRecoveryNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRecoveryNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiorchServiceServer).TriggerRecoveryNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiorchService_TriggerRecoveryNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiorchServiceServer).TriggerRecoveryNow(ctx, req.(*TriggerRecoveryNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiorchService_ApplyCertifiedRuleChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCertifiedRuleChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiorchServiceServer).ApplyCertifiedRuleChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiorchService_ApplyCertifiedRuleChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiorchServiceServer).ApplyCertifiedRuleChange(ctx, req.(*ApplyCertifiedRuleChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiorchService_ServiceDesc is the grpc.ServiceDesc for MultiorchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiorchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multiorch.MultiorchService",
	HandlerType: (*MultiorchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShardStatus",
			Handler:    _MultiorchService_GetShardStatus_Handler,
		},
		{
			MethodName: "DisableRecovery",
			Handler:    _MultiorchService_DisableRecovery_Handler,
		},
		{
			MethodName: "EnableRecovery",
			Handler:    _MultiorchService_EnableRecovery_Handler,
		},
		{
			MethodName: "GetRecoveryStatus",
			Handler:    _MultiorchService_GetRecoveryStatus_Handler,
		},
		{
			MethodName: "TriggerRecoveryNow",
			Handler:    _MultiorchService_TriggerRecoveryNow_Handler,
		},
		{
			MethodName: "ApplyCertifiedRuleChange",
			Handler:    _MultiorchService_ApplyCertifiedRuleChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiorchservice.proto",
}
