// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: multiorchservice.proto

package multiorch

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shard to get status for
	ShardKey      *clustermetadata.ShardKey `protobuf:"bytes,1,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardStatusRequest) Reset() {
	*x = ShardStatusRequest{}
	mi := &file_multiorchservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStatusRequest) ProtoMessage() {}

func (x *ShardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStatusRequest.ProtoReflect.Descriptor instead.
func (*ShardStatusRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{0}
}

func (x *ShardStatusRequest) GetShardKey() *clustermetadata.ShardKey {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

type ShardStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Currently detected problems for this shard
	Problems []*DetectedProblem `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	// Per-pooler health details for this shard
	PoolerHealths []*PoolerHealth `protobuf:"bytes,2,rep,name=pooler_healths,json=poolerHealths,proto3" json:"pooler_healths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardStatusResponse) Reset() {
	*x = ShardStatusResponse{}
	mi := &file_multiorchservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStatusResponse) ProtoMessage() {}

func (x *ShardStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStatusResponse.ProtoReflect.Descriptor instead.
func (*ShardStatusResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{1}
}

func (x *ShardStatusResponse) GetProblems() []*DetectedProblem {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *ShardStatusResponse) GetPoolerHealths() []*PoolerHealth {
	if x != nil {
		return x.PoolerHealths
	}
	return nil
}

type DetectedProblem struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          string                    `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                            // e.g., "PrimaryIsDead"
	CheckName     string                    `protobuf:"bytes,2,opt,name=check_name,json=checkName,proto3" json:"check_name,omitempty"` // Analyzer name
	PoolerId      *clustermetadata.ID       `protobuf:"bytes,3,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`    // Affected pooler
	ShardKey      *clustermetadata.ShardKey `protobuf:"bytes,4,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	Description   string                    `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                     `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Scope         string                    `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"` // "Shard" or "Pooler"
	DetectedAt    *timestamppb.Timestamp    `protobuf:"bytes,8,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectedProblem) Reset() {
	*x = DetectedProblem{}
	mi := &file_multiorchservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedProblem) ProtoMessage() {}

func (x *DetectedProblem) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedProblem.ProtoReflect.Descriptor instead.
func (*DetectedProblem) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{2}
}

func (x *DetectedProblem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DetectedProblem) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

func (x *DetectedProblem) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

func (x *DetectedProblem) GetShardKey() *clustermetadata.ShardKey {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

func (x *DetectedProblem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetectedProblem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DetectedProblem) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DetectedProblem) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

type PoolerHealth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PoolerId        *clustermetadata.ID    `protobuf:"bytes,1,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	StreamConnected bool                   `protobuf:"varint,2,opt,name=stream_connected,json=streamConnected,proto3" json:"stream_connected,omitempty"` // is the health stream to this pooler connected right now
	PostgresRunning bool                   `protobuf:"varint,3,opt,name=postgres_running,json=postgresRunning,proto3" json:"postgres_running,omitempty"`
	PoolerType      string                 `protobuf:"bytes,4,opt,name=pooler_type,json=poolerType,proto3" json:"pooler_type,omitempty"` // PRIMARY, REPLICA, UNKNOWN
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`       // when we last received a health snapshot
	PostgresReady   bool                   `protobuf:"varint,6,opt,name=postgres_ready,json=postgresReady,proto3" json:"postgres_ready,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PoolerHealth) Reset() {
	*x = PoolerHealth{}
	mi := &file_multiorchservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolerHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolerHealth) ProtoMessage() {}

func (x *PoolerHealth) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolerHealth.ProtoReflect.Descriptor instead.
func (*PoolerHealth) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{3}
}

func (x *PoolerHealth) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

func (x *PoolerHealth) GetStreamConnected() bool {
	if x != nil {
		return x.StreamConnected
	}
	return false
}

func (x *PoolerHealth) GetPostgresRunning() bool {
	if x != nil {
		return x.PostgresRunning
	}
	return false
}

func (x *PoolerHealth) GetPoolerType() string {
	if x != nil {
		return x.PoolerType
	}
	return ""
}

func (x *PoolerHealth) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *PoolerHealth) GetPostgresReady() bool {
	if x != nil {
		return x.PostgresReady
	}
	return false
}

type DisableRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRecoveryRequest) Reset() {
	*x = DisableRecoveryRequest{}
	mi := &file_multiorchservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRecoveryRequest) ProtoMessage() {}

func (x *DisableRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRecoveryRequest.ProtoReflect.Descriptor instead.
func (*DisableRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{4}
}

type DisableRecoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether recovery was disabled
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional context
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRecoveryResponse) Reset() {
	*x = DisableRecoveryResponse{}
	mi := &file_multiorchservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRecoveryResponse) ProtoMessage() {}

func (x *DisableRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRecoveryResponse.ProtoReflect.Descriptor instead.
func (*DisableRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{5}
}

func (x *DisableRecoveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisableRecoveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnableRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRecoveryRequest) Reset() {
	*x = EnableRecoveryRequest{}
	mi := &file_multiorchservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRecoveryRequest) ProtoMessage() {}

func (x *EnableRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRecoveryRequest.ProtoReflect.Descriptor instead.
func (*EnableRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{6}
}

type EnableRecoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether recovery was enabled
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional context
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRecoveryResponse) Reset() {
	*x = EnableRecoveryResponse{}
	mi := &file_multiorchservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRecoveryResponse) ProtoMessage() {}

func (x *EnableRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRecoveryResponse.ProtoReflect.Descriptor instead.
func (*EnableRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{7}
}

func (x *EnableRecoveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnableRecoveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRecoveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryStatusRequest) Reset() {
	*x = GetRecoveryStatusRequest{}
	mi := &file_multiorchservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryStatusRequest) ProtoMessage() {}

func (x *GetRecoveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRecoveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{8}
}

type GetRecoveryStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled indicates whether recovery is currently active
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryStatusResponse) Reset() {
	*x = GetRecoveryStatusResponse{}
	mi := &file_multiorchservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryStatusResponse) ProtoMessage() {}

func (x *GetRecoveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRecoveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecoveryStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type TriggerRecoveryNowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_cycles limits the number of recovery cycles to run.
	// If 0 (default), cycles continue until all problems are resolved or the deadline expires.
	// If 1, exactly one cycle is run and the call returns immediately with any remaining problem codes.
	// Values greater than 1 are rejected with INVALID_ARGUMENT.
	MaxCycles     uint32 `protobuf:"varint,1,opt,name=max_cycles,json=maxCycles,proto3" json:"max_cycles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRecoveryNowRequest) Reset() {
	*x = TriggerRecoveryNowRequest{}
	mi := &file_multiorchservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRecoveryNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRecoveryNowRequest) ProtoMessage() {}

func (x *TriggerRecoveryNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRecoveryNowRequest.ProtoReflect.Descriptor instead.
func (*TriggerRecoveryNowRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{10}
}

func (x *TriggerRecoveryNowRequest) GetMaxCycles() uint32 {
	if x != nil {
		return x.MaxCycles
	}
	return 0
}

type TriggerRecoveryNowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// remaining_problem_codes lists problem codes still detected (e.g., "REPLICA_NOT_REPLICATING")
	RemainingProblemCodes []string `protobuf:"bytes,4,rep,name=remaining_problem_codes,json=remainingProblemCodes,proto3" json:"remaining_problem_codes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TriggerRecoveryNowResponse) Reset() {
	*x = TriggerRecoveryNowResponse{}
	mi := &file_multiorchservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRecoveryNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRecoveryNowResponse) ProtoMessage() {}

func (x *TriggerRecoveryNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRecoveryNowResponse.ProtoReflect.Descriptor instead.
func (*TriggerRecoveryNowResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerRecoveryNowResponse) GetRemainingProblemCodes() []string {
	if x != nil {
		return x.RemainingProblemCodes
	}
	return nil
}

// ApplyCertifiedRuleChangeRequest installs a new shard rule using an externally
// certified revocation. Multiorch acts as a pure executor: it validates the
// inputs, runs the Recruit + Propose flow against the proposed cohort, and
// returns success or failure. The caller is responsible for populating every
// identity and timing field; multiorch never invents one.
//
// The cert is the caller's load-bearing safety attestation: by submitting it,
// the caller asserts that no member of the outgoing cohort will commit further
// writes past cert.outgoing_rule_number, and that any candidate leader has
// reached at least cert.frozen_lsn under that rule. Pooler-side
// ValidateRevocation enforces this at the WAL level (a node that resumes with
// progress past the certified rule will refuse the new rule), but callers
// should not rely on that floor for correctness — the cert is the primary
// safety contract.
type ApplyCertifiedRuleChangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shard to apply the rule change to.
	ShardKey *clustermetadata.ShardKey `protobuf:"bytes,1,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	// The transition to install. proposal's fields must all be populated,
	// including rule_number, coordinator_id, and creation_time.
	// proposal.rule_number.coordinator_term must equal
	// cert.term_revocation.revoked_below_term.
	//
	// decision is the caller's discovered outgoing rule. Unlike a normal
	// (non-certified) rule change, decision may name a rule the caller only
	// observed as an undecided proposal: the cert already attests that no
	// cohort member can progress beyond frozen_lsn under it, which is exactly
	// the guarantee normal quorum-verification would otherwise provide. The
	// cert makes that propagation "free" — decision can be treated as
	// authoritative here even though it was never marked decided through the
	// normal two-phase write.
	ProposedTransition *clustermetadata.RulePosition `protobuf:"bytes,2,opt,name=proposed_transition,json=proposedTransition,proto3" json:"proposed_transition,omitempty"`
	// Externally certified revocation of the outgoing cohort. All fields must
	// be populated, including term_revocation. The cert's term_revocation is
	// what each pooler will record on disk via Recruit.
	//
	// For initial leader appointment, every node already carries the {0,1}
	// row written during initdb — there is no true "no rule" state. Set
	// outgoing_rule_number to {coordinator_term=0, leader_subterm=1} and
	// frozen_lsn to "0/0".
	Cert *clustermetadata.ExternallyCertifiedRevocation `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	// Free-text, recorded in rule_history for audit.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCertifiedRuleChangeRequest) Reset() {
	*x = ApplyCertifiedRuleChangeRequest{}
	mi := &file_multiorchservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCertifiedRuleChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCertifiedRuleChangeRequest) ProtoMessage() {}

func (x *ApplyCertifiedRuleChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCertifiedRuleChangeRequest.ProtoReflect.Descriptor instead.
func (*ApplyCertifiedRuleChangeRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyCertifiedRuleChangeRequest) GetShardKey() *clustermetadata.ShardKey {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

func (x *ApplyCertifiedRuleChangeRequest) GetProposedTransition() *clustermetadata.RulePosition {
	if x != nil {
		return x.ProposedTransition
	}
	return nil
}

func (x *ApplyCertifiedRuleChangeRequest) GetCert() *clustermetadata.ExternallyCertifiedRevocation {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *ApplyCertifiedRuleChangeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApplyCertifiedRuleChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCertifiedRuleChangeResponse) Reset() {
	*x = ApplyCertifiedRuleChangeResponse{}
	mi := &file_multiorchservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCertifiedRuleChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCertifiedRuleChangeResponse) ProtoMessage() {}

func (x *ApplyCertifiedRuleChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCertifiedRuleChangeResponse.ProtoReflect.Descriptor instead.
func (*ApplyCertifiedRuleChangeResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{13}
}

var File_multiorchservice_proto protoreflect.FileDescriptor

const file_multiorchservice_proto_rawDesc = "" +
	"\n" +
	"\x16multiorchservice.proto\x12\tmultiorch\x1a\x15clustermetadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x12ShardStatusRequest\x126\n" +
	"\tshard_key\x18\x01 \x01(\v2\x19.clustermetadata.ShardKeyR\bshardKey\"\x8d\x01\n" +
	"\x13ShardStatusResponse\x126\n" +
	"\bproblems\x18\x01 \x03(\v2\x1a.multiorch.DetectedProblemR\bproblems\x12>\n" +
	"\x0epooler_healths\x18\x02 \x03(\v2\x17.multiorch.PoolerHealthR\rpoolerHealths\"\xbf\x02\n" +
	"\x0fDetectedProblem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"check_name\x18\x02 \x01(\tR\tcheckName\x120\n" +
	"\tpooler_id\x18\x03 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\x126\n" +
	"\tshard_key\x18\x04 \x01(\v2\x19.clustermetadata.ShardKeyR\bshardKey\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12;\n" +
	"\vdetected_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\"\x97\x02\n" +
	"\fPoolerHealth\x120\n" +
	"\tpooler_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\x12)\n" +
	"\x10stream_connected\x18\x02 \x01(\bR\x0fstreamConnected\x12)\n" +
	"\x10postgres_running\x18\x03 \x01(\bR\x0fpostgresRunning\x12\x1f\n" +
	"\vpooler_type\x18\x04 \x01(\tR\n" +
	"poolerType\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12%\n" +
	"\x0epostgres_ready\x18\x06 \x01(\bR\rpostgresReady\"\x18\n" +
	"\x16DisableRecoveryRequest\"M\n" +
	"\x17DisableRecoveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15EnableRecoveryRequest\"L\n" +
	"\x16EnableRecoveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\x18GetRecoveryStatusRequest\"5\n" +
	"\x19GetRecoveryStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\":\n" +
	"\x19TriggerRecoveryNowRequest\x12\x1d\n" +
	"\n" +
	"max_cycles\x18\x01 \x01(\rR\tmaxCycles\"T\n" +
	"\x1aTriggerRecoveryNowResponse\x126\n" +
	"\x17remaining_problem_codes\x18\x04 \x03(\tR\x15remainingProblemCodes\"\x85\x02\n" +
	"\x1fApplyCertifiedRuleChangeRequest\x126\n" +
	"\tshard_key\x18\x01 \x01(\v2\x19.clustermetadata.ShardKeyR\bshardKey\x12N\n" +
	"\x13proposed_transition\x18\x02 \x01(\v2\x1d.clustermetadata.RulePositionR\x12proposedTransition\x12B\n" +
	"\x04cert\x18\x03 \x01(\v2..clustermetadata.ExternallyCertifiedRevocationR\x04cert\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\"\n" +
	" ApplyCertifiedRuleChangeResponse2\xd8\x04\n" +
	"\x10MultiorchService\x12Q\n" +
	"\x0eGetShardStatus\x12\x1d.multiorch.ShardStatusRequest\x1a\x1e.multiorch.ShardStatusResponse\"\x00\x12Z\n" +
	"\x0fDisableRecovery\x12!.multiorch.DisableRecoveryRequest\x1a\".multiorch.DisableRecoveryResponse\"\x00\x12W\n" +
	"\x0eEnableRecovery\x12 .multiorch.EnableRecoveryRequest\x1a!.multiorch.EnableRecoveryResponse\"\x00\x12`\n" +
	"\x11GetRecoveryStatus\x12#.multiorch.GetRecoveryStatusRequest\x1a$.multiorch.GetRecoveryStatusResponse\"\x00\x12c\n" +
	"\x12TriggerRecoveryNow\x12$.multiorch.TriggerRecoveryNowRequest\x1a%.multiorch.TriggerRecoveryNowResponse\"\x00\x12u\n" +
	"\x18ApplyCertifiedRuleChange\x12*.multiorch.ApplyCertifiedRuleChangeRequest\x1a+.multiorch.ApplyCertifiedRuleChangeResponse\"\x00B0Z.github.com/multigres/multigres/go/pb/multiorchb\x06proto3"

var (
	file_multiorchservice_proto_rawDescOnce sync.Once
	file_multiorchservice_proto_rawDescData []byte
)

func file_multiorchservice_proto_rawDescGZIP() []byte {
	file_multiorchservice_proto_rawDescOnce.Do(func() {
		file_multiorchservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multiorchservice_proto_rawDesc), len(file_multiorchservice_proto_rawDesc)))
	})
	return file_multiorchservice_proto_rawDescData
}

var file_multiorchservice_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_multiorchservice_proto_goTypes = []any{
	(*ShardStatusRequest)(nil),                            // 0: multiorch.ShardStatusRequest
	(*ShardStatusResponse)(nil),                           // 1: multiorch.ShardStatusResponse
	(*DetectedProblem)(nil),                               // 2: multiorch.DetectedProblem
	(*PoolerHealth)(nil),                                  // 3: multiorch.PoolerHealth
	(*DisableRecoveryRequest)(nil),                        // 4: multiorch.DisableRecoveryRequest
	(*DisableRecoveryResponse)(nil),                       // 5: multiorch.DisableRecoveryResponse
	(*EnableRecoveryRequest)(nil),                         // 6: multiorch.EnableRecoveryRequest
	(*EnableRecoveryResponse)(nil),                        // 7: multiorch.EnableRecoveryResponse
	(*GetRecoveryStatusRequest)(nil),                      // 8: multiorch.GetRecoveryStatusRequest
	(*GetRecoveryStatusResponse)(nil),                     // 9: multiorch.GetRecoveryStatusResponse
	(*TriggerRecoveryNowRequest)(nil),                     // 10: multiorch.TriggerRecoveryNowRequest
	(*TriggerRecoveryNowResponse)(nil),                    // 11: multiorch.TriggerRecoveryNowResponse
	(*ApplyCertifiedRuleChangeRequest)(nil),               // 12: multiorch.ApplyCertifiedRuleChangeRequest
	(*ApplyCertifiedRuleChangeResponse)(nil),              // 13: multiorch.ApplyCertifiedRuleChangeResponse
	(*clustermetadata.ShardKey)(nil),                      // 14: clustermetadata.ShardKey
	(*clustermetadata.ID)(nil),                            // 15: clustermetadata.ID
	(*timestamppb.Timestamp)(nil),                         // 16: google.protobuf.Timestamp
	(*clustermetadata.RulePosition)(nil),                  // 17: clustermetadata.RulePosition
	(*clustermetadata.ExternallyCertifiedRevocation)(nil), // 18: clustermetadata.ExternallyCertifiedRevocation
}
var file_multiorchservice_proto_depIdxs = []int32{
	14, // 0: multiorch.ShardStatusRequest.shard_key:type_name -> clustermetadata.ShardKey
	2,  // 1: multiorch.ShardStatusResponse.problems:type_name -> multiorch.DetectedProblem
	3,  // 2: multiorch.ShardStatusResponse.pooler_healths:type_name -> multiorch.PoolerHealth
	15, // 3: multiorch.DetectedProblem.pooler_id:type_name -> clustermetadata.ID
	14, // 4: multiorch.DetectedProblem.shard_key:type_name -> clustermetadata.ShardKey
	16, // 5: multiorch.DetectedProblem.detected_at:type_name -> google.protobuf.Timestamp
	15, // 6: multiorch.PoolerHealth.pooler_id:type_name -> clustermetadata.ID
	16, // 7: multiorch.PoolerHealth.last_seen:type_name -> google.protobuf.Timestamp
	14, // 8: multiorch.ApplyCertifiedRuleChangeRequest.shard_key:type_name -> clustermetadata.ShardKey
	17, // 9: multiorch.ApplyCertifiedRuleChangeRequest.proposed_transition:type_name -> clustermetadata.RulePosition
	18, // 10: multiorch.ApplyCertifiedRuleChangeRequest.cert:type_name -> clustermetadata.ExternallyCertifiedRevocation
	0,  // 11: multiorch.MultiorchService.GetShardStatus:input_type -> multiorch.ShardStatusRequest
	4,  // 12: multiorch.MultiorchService.DisableRecovery:input_type -> multiorch.DisableRecoveryRequest
	6,  // 13: multiorch.MultiorchService.EnableRecovery:input_type -> multiorch.EnableRecoveryRequest
	8,  // 14: multiorch.MultiorchService.GetRecoveryStatus:input_type -> multiorch.GetRecoveryStatusRequest
	10, // 15: multiorch.MultiorchService.TriggerRecoveryNow:input_type -> multiorch.TriggerRecoveryNowRequest
	12, // 16: multiorch.MultiorchService.ApplyCertifiedRuleChange:input_type -> multiorch.ApplyCertifiedRuleChangeRequest
	1,  // 17: multiorch.MultiorchService.GetShardStatus:output_type -> multiorch.ShardStatusResponse
	5,  // 18: multiorch.MultiorchService.DisableRecovery:output_type -> multiorch.DisableRecoveryResponse
	7,  // 19: multiorch.MultiorchService.EnableRecovery:output_type -> multiorch.EnableRecoveryResponse
	9,  // 20: multiorch.MultiorchService.GetRecoveryStatus:output_type -> multiorch.GetRecoveryStatusResponse
	11, // 21: multiorch.MultiorchService.TriggerRecoveryNow:output_type -> multiorch.TriggerRecoveryNowResponse
	13, // 22: multiorch.MultiorchService.ApplyCertifiedRuleChange:output_type -> multiorch.ApplyCertifiedRuleChangeResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_multiorchservice_proto_init() }
func file_multiorchservice_proto_init() {
	if File_multiorchservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiorchservice_proto_rawDesc), len(file_multiorchservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiorchservice_proto_goTypes,
		DependencyIndexes: file_multiorchservice_proto_depIdxs,
		MessageInfos:      file_multiorchservice_proto_msgTypes,
	}.Build()
	File_multiorchservice_proto = out.File
	file_multiorchservice_proto_goTypes = nil
	file_multiorchservice_proto_depIdxs = nil
}
