// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Management / introspection RPCs on the multigateway. These are intended for
// multiadmin to drive per-gateway debug pages — the gateway-to-gateway query
// cancellation API lives separately on MultigatewayService.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: multigatewaymanagerservice.proto

package multigatewaymanager

import (
	multigatewaymanagerdata "github.com/multigres/multigres/go/pb/multigatewaymanagerdata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetQueryRegistryRequest specifies which slice of the per-fingerprint
// registry to return. The registry can hold thousands of fingerprints with
// multi-KB trend arrays each, so admin UIs SHOULD set limit and may set
// min_calls to keep responses bounded.
type GetQueryRegistryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// limit caps the number of fingerprints returned, sorted by call count
	// descending. 0 means no limit (return all tracked fingerprints).
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// min_calls drops fingerprints whose total call count is below this
	// threshold. 0 means no threshold.
	MinCalls      uint64 `protobuf:"varint,2,opt,name=min_calls,json=minCalls,proto3" json:"min_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryRegistryRequest) Reset() {
	*x = GetQueryRegistryRequest{}
	mi := &file_multigatewaymanagerservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryRegistryRequest) ProtoMessage() {}

func (x *GetQueryRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryRegistryRequest.ProtoReflect.Descriptor instead.
func (*GetQueryRegistryRequest) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetQueryRegistryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetQueryRegistryRequest) GetMinCalls() uint64 {
	if x != nil {
		return x.MinCalls
	}
	return 0
}

// GetQueryRegistryResponse wraps the registry snapshot.
type GetQueryRegistryResponse struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Snapshot      *multigatewaymanagerdata.QueryRegistrySnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryRegistryResponse) Reset() {
	*x = GetQueryRegistryResponse{}
	mi := &file_multigatewaymanagerservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryRegistryResponse) ProtoMessage() {}

func (x *GetQueryRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryRegistryResponse.ProtoReflect.Descriptor instead.
func (*GetQueryRegistryResponse) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetQueryRegistryResponse) GetSnapshot() *multigatewaymanagerdata.QueryRegistrySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// GetConsolidatorStatsRequest is empty — the consolidator is per-instance.
type GetConsolidatorStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidatorStatsRequest) Reset() {
	*x = GetConsolidatorStatsRequest{}
	mi := &file_multigatewaymanagerservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidatorStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidatorStatsRequest) ProtoMessage() {}

func (x *GetConsolidatorStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidatorStatsRequest.ProtoReflect.Descriptor instead.
func (*GetConsolidatorStatsRequest) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerservice_proto_rawDescGZIP(), []int{2}
}

// GetConsolidatorStatsResponse wraps the consolidator stats.
type GetConsolidatorStatsResponse struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Stats         *multigatewaymanagerdata.ConsolidatorStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidatorStatsResponse) Reset() {
	*x = GetConsolidatorStatsResponse{}
	mi := &file_multigatewaymanagerservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidatorStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidatorStatsResponse) ProtoMessage() {}

func (x *GetConsolidatorStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidatorStatsResponse.ProtoReflect.Descriptor instead.
func (*GetConsolidatorStatsResponse) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetConsolidatorStatsResponse) GetStats() *multigatewaymanagerdata.ConsolidatorStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_multigatewaymanagerservice_proto protoreflect.FileDescriptor

const file_multigatewaymanagerservice_proto_rawDesc = "" +
	"\n" +
	" multigatewaymanagerservice.proto\x12\x13multigatewaymanager\x1a\x1dmultigatewaymanagerdata.proto\"L\n" +
	"\x17GetQueryRegistryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x1b\n" +
	"\tmin_calls\x18\x02 \x01(\x04R\bminCalls\"f\n" +
	"\x18GetQueryRegistryResponse\x12J\n" +
	"\bsnapshot\x18\x01 \x01(\v2..multigatewaymanagerdata.QueryRegistrySnapshotR\bsnapshot\"\x1d\n" +
	"\x1bGetConsolidatorStatsRequest\"`\n" +
	"\x1cGetConsolidatorStatsResponse\x12@\n" +
	"\x05stats\x18\x01 \x01(\v2*.multigatewaymanagerdata.ConsolidatorStatsR\x05stats2\x83\x02\n" +
	"\x13MultigatewayManager\x12o\n" +
	"\x10GetQueryRegistry\x12,.multigatewaymanager.GetQueryRegistryRequest\x1a-.multigatewaymanager.GetQueryRegistryResponse\x12{\n" +
	"\x14GetConsolidatorStats\x120.multigatewaymanager.GetConsolidatorStatsRequest\x1a1.multigatewaymanager.GetConsolidatorStatsResponseB:Z8github.com/multigres/multigres/go/pb/multigatewaymanagerb\x06proto3"

var (
	file_multigatewaymanagerservice_proto_rawDescOnce sync.Once
	file_multigatewaymanagerservice_proto_rawDescData []byte
)

func file_multigatewaymanagerservice_proto_rawDescGZIP() []byte {
	file_multigatewaymanagerservice_proto_rawDescOnce.Do(func() {
		file_multigatewaymanagerservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multigatewaymanagerservice_proto_rawDesc), len(file_multigatewaymanagerservice_proto_rawDesc)))
	})
	return file_multigatewaymanagerservice_proto_rawDescData
}

var file_multigatewaymanagerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_multigatewaymanagerservice_proto_goTypes = []any{
	(*GetQueryRegistryRequest)(nil),                       // 0: multigatewaymanager.GetQueryRegistryRequest
	(*GetQueryRegistryResponse)(nil),                      // 1: multigatewaymanager.GetQueryRegistryResponse
	(*GetConsolidatorStatsRequest)(nil),                   // 2: multigatewaymanager.GetConsolidatorStatsRequest
	(*GetConsolidatorStatsResponse)(nil),                  // 3: multigatewaymanager.GetConsolidatorStatsResponse
	(*multigatewaymanagerdata.QueryRegistrySnapshot)(nil), // 4: multigatewaymanagerdata.QueryRegistrySnapshot
	(*multigatewaymanagerdata.ConsolidatorStats)(nil),     // 5: multigatewaymanagerdata.ConsolidatorStats
}
var file_multigatewaymanagerservice_proto_depIdxs = []int32{
	4, // 0: multigatewaymanager.GetQueryRegistryResponse.snapshot:type_name -> multigatewaymanagerdata.QueryRegistrySnapshot
	5, // 1: multigatewaymanager.GetConsolidatorStatsResponse.stats:type_name -> multigatewaymanagerdata.ConsolidatorStats
	0, // 2: multigatewaymanager.MultigatewayManager.GetQueryRegistry:input_type -> multigatewaymanager.GetQueryRegistryRequest
	2, // 3: multigatewaymanager.MultigatewayManager.GetConsolidatorStats:input_type -> multigatewaymanager.GetConsolidatorStatsRequest
	1, // 4: multigatewaymanager.MultigatewayManager.GetQueryRegistry:output_type -> multigatewaymanager.GetQueryRegistryResponse
	3, // 5: multigatewaymanager.MultigatewayManager.GetConsolidatorStats:output_type -> multigatewaymanager.GetConsolidatorStatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_multigatewaymanagerservice_proto_init() }
func file_multigatewaymanagerservice_proto_init() {
	if File_multigatewaymanagerservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multigatewaymanagerservice_proto_rawDesc), len(file_multigatewaymanagerservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multigatewaymanagerservice_proto_goTypes,
		DependencyIndexes: file_multigatewaymanagerservice_proto_depIdxs,
		MessageInfos:      file_multigatewaymanagerservice_proto_msgTypes,
	}.Build()
	File_multigatewaymanagerservice_proto = out.File
	file_multigatewaymanagerservice_proto_goTypes = nil
	file_multigatewaymanagerservice_proto_depIdxs = nil
}
