//
//Copyright 2026 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains the RPC service definition for multigateway.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multigatewayservice.proto

package multigatewayservice

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultigatewayService_CancelQuery_FullMethodName = "/multigatewayservice.MultigatewayService/CancelQuery"
)

// MultigatewayServiceClient is the client API for MultigatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultigatewayService provides cross-gateway communication for query cancellation.
type MultigatewayServiceClient interface {
	// CancelQuery forwards a cancel request to the gateway that owns the connection.
	CancelQuery(ctx context.Context, in *CancelQueryRequest, opts ...grpc.CallOption) (*CancelQueryResponse, error)
}

type multigatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultigatewayServiceClient(cc grpc.ClientConnInterface) MultigatewayServiceClient {
	return &multigatewayServiceClient{cc}
}

func (c *multigatewayServiceClient) CancelQuery(ctx context.Context, in *CancelQueryRequest, opts ...grpc.CallOption) (*CancelQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelQueryResponse)
	err := c.cc.Invoke(ctx, MultigatewayService_CancelQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultigatewayServiceServer is the server API for MultigatewayService service.
// All implementations must embed UnimplementedMultigatewayServiceServer
// for forward compatibility.
//
// MultigatewayService provides cross-gateway communication for query cancellation.
type MultigatewayServiceServer interface {
	// CancelQuery forwards a cancel request to the gateway that owns the connection.
	CancelQuery(context.Context, *CancelQueryRequest) (*CancelQueryResponse, error)
	mustEmbedUnimplementedMultigatewayServiceServer()
}

// UnimplementedMultigatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultigatewayServiceServer struct{}

func (UnimplementedMultigatewayServiceServer) CancelQuery(context.Context, *CancelQueryRequest) (*CancelQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelQuery not implemented")
}
func (UnimplementedMultigatewayServiceServer) mustEmbedUnimplementedMultigatewayServiceServer() {}
func (UnimplementedMultigatewayServiceServer) testEmbeddedByValue()                             {}

// UnsafeMultigatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultigatewayServiceServer will
// result in compilation errors.
type UnsafeMultigatewayServiceServer interface {
	mustEmbedUnimplementedMultigatewayServiceServer()
}

func RegisterMultigatewayServiceServer(s grpc.ServiceRegistrar, srv MultigatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedMultigatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultigatewayService_ServiceDesc, srv)
}

func _MultigatewayService_CancelQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultigatewayServiceServer).CancelQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultigatewayService_CancelQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultigatewayServiceServer).CancelQuery(ctx, req.(*CancelQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultigatewayService_ServiceDesc is the grpc.ServiceDesc for MultigatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultigatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multigatewayservice.MultigatewayService",
	HandlerType: (*MultigatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelQuery",
			Handler:    _MultigatewayService_CancelQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multigatewayservice.proto",
}
