//
//Copyright 2026 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains the RPC service definition for multigateway.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: multigatewayservice.proto

package multigatewayservice

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CancelQueryRequest contains the cancel key data from the PostgreSQL cancel request.
type CancelQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// process_id is the PID sent by the client, encoding gateway prefix + local conn ID.
	ProcessId uint32 `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// secret_key is the backend key data for cancel request authentication.
	// Required: the receiving gateway verifies this matches before canceling.
	// Without it, any client that can guess a PID could cancel arbitrary queries.
	SecretKey uint32 `protobuf:"varint,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// replica indicates the cancel targets a connection on the replica-reads listener.
	// When false (default), the cancel targets the primary listener. This is needed
	// because both listeners share the same PID prefix and may have overlapping local
	// connection IDs — the connection type disambiguates which listener owns the PID.
	Replica       bool `protobuf:"varint,3,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryRequest) Reset() {
	*x = CancelQueryRequest{}
	mi := &file_multigatewayservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryRequest) ProtoMessage() {}

func (x *CancelQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewayservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryRequest.ProtoReflect.Descriptor instead.
func (*CancelQueryRequest) Descriptor() ([]byte, []int) {
	return file_multigatewayservice_proto_rawDescGZIP(), []int{0}
}

func (x *CancelQueryRequest) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *CancelQueryRequest) GetSecretKey() uint32 {
	if x != nil {
		return x.SecretKey
	}
	return 0
}

func (x *CancelQueryRequest) GetReplica() bool {
	if x != nil {
		return x.Replica
	}
	return false
}

// CancelQueryResponse is empty on success.
type CancelQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryResponse) Reset() {
	*x = CancelQueryResponse{}
	mi := &file_multigatewayservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryResponse) ProtoMessage() {}

func (x *CancelQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewayservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryResponse.ProtoReflect.Descriptor instead.
func (*CancelQueryResponse) Descriptor() ([]byte, []int) {
	return file_multigatewayservice_proto_rawDescGZIP(), []int{1}
}

var File_multigatewayservice_proto protoreflect.FileDescriptor

const file_multigatewayservice_proto_rawDesc = "" +
	"\n" +
	"\x19multigatewayservice.proto\x12\x13multigatewayservice\"l\n" +
	"\x12CancelQueryRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\rR\tprocessId\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\rR\tsecretKey\x12\x18\n" +
	"\areplica\x18\x03 \x01(\bR\areplica\"\x15\n" +
	"\x13CancelQueryResponse2w\n" +
	"\x13MultigatewayService\x12`\n" +
	"\vCancelQuery\x12'.multigatewayservice.CancelQueryRequest\x1a(.multigatewayservice.CancelQueryResponseB:Z8github.com/multigres/multigres/go/pb/multigatewayserviceb\x06proto3"

var (
	file_multigatewayservice_proto_rawDescOnce sync.Once
	file_multigatewayservice_proto_rawDescData []byte
)

func file_multigatewayservice_proto_rawDescGZIP() []byte {
	file_multigatewayservice_proto_rawDescOnce.Do(func() {
		file_multigatewayservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multigatewayservice_proto_rawDesc), len(file_multigatewayservice_proto_rawDesc)))
	})
	return file_multigatewayservice_proto_rawDescData
}

var file_multigatewayservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multigatewayservice_proto_goTypes = []any{
	(*CancelQueryRequest)(nil),  // 0: multigatewayservice.CancelQueryRequest
	(*CancelQueryResponse)(nil), // 1: multigatewayservice.CancelQueryResponse
}
var file_multigatewayservice_proto_depIdxs = []int32{
	0, // 0: multigatewayservice.MultigatewayService.CancelQuery:input_type -> multigatewayservice.CancelQueryRequest
	1, // 1: multigatewayservice.MultigatewayService.CancelQuery:output_type -> multigatewayservice.CancelQueryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multigatewayservice_proto_init() }
func file_multigatewayservice_proto_init() {
	if File_multigatewayservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multigatewayservice_proto_rawDesc), len(file_multigatewayservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multigatewayservice_proto_goTypes,
		DependencyIndexes: file_multigatewayservice_proto_depIdxs,
		MessageInfos:      file_multigatewayservice_proto_msgTypes,
	}.Build()
	File_multigatewayservice_proto = out.File
	file_multigatewayservice_proto_goTypes = nil
	file_multigatewayservice_proto_depIdxs = nil
}
