// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: multiorchservice.proto

package multiorchconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	multiorch "github.com/multigres/multigres/go/pb/multiorch"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MultiorchServiceName is the fully-qualified name of the MultiorchService service.
	MultiorchServiceName = "multiorch.MultiorchService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MultiorchServiceGetShardStatusProcedure is the fully-qualified name of the MultiorchService's
	// GetShardStatus RPC.
	MultiorchServiceGetShardStatusProcedure = "/multiorch.MultiorchService/GetShardStatus"
	// MultiorchServiceDisableRecoveryProcedure is the fully-qualified name of the MultiorchService's
	// DisableRecovery RPC.
	MultiorchServiceDisableRecoveryProcedure = "/multiorch.MultiorchService/DisableRecovery"
	// MultiorchServiceEnableRecoveryProcedure is the fully-qualified name of the MultiorchService's
	// EnableRecovery RPC.
	MultiorchServiceEnableRecoveryProcedure = "/multiorch.MultiorchService/EnableRecovery"
	// MultiorchServiceGetRecoveryStatusProcedure is the fully-qualified name of the MultiorchService's
	// GetRecoveryStatus RPC.
	MultiorchServiceGetRecoveryStatusProcedure = "/multiorch.MultiorchService/GetRecoveryStatus"
	// MultiorchServiceTriggerRecoveryNowProcedure is the fully-qualified name of the MultiorchService's
	// TriggerRecoveryNow RPC.
	MultiorchServiceTriggerRecoveryNowProcedure = "/multiorch.MultiorchService/TriggerRecoveryNow"
	// MultiorchServiceApplyCertifiedRuleChangeProcedure is the fully-qualified name of the
	// MultiorchService's ApplyCertifiedRuleChange RPC.
	MultiorchServiceApplyCertifiedRuleChangeProcedure = "/multiorch.MultiorchService/ApplyCertifiedRuleChange"
)

// MultiorchServiceClient is a client for the multiorch.MultiorchService service.
type MultiorchServiceClient interface {
	// GetShardStatus returns diagnostic information for a specific shard
	GetShardStatus(context.Context, *connect.Request[multiorch.ShardStatusRequest]) (*connect.Response[multiorch.ShardStatusResponse], error)
	// DisableRecovery stops the recovery engine from automatically repairing issues.
	// This is intended for testing scenarios where manual control over recovery is needed.
	// When this returns, no recovery actions are in-flight (strong synchronization guarantee).
	DisableRecovery(context.Context, *connect.Request[multiorch.DisableRecoveryRequest]) (*connect.Response[multiorch.DisableRecoveryResponse], error)
	// EnableRecovery resumes the recovery engine's automatic repair operations.
	EnableRecovery(context.Context, *connect.Request[multiorch.EnableRecoveryRequest]) (*connect.Response[multiorch.EnableRecoveryResponse], error)
	// GetRecoveryStatus returns whether recovery is currently enabled or disabled.
	GetRecoveryStatus(context.Context, *connect.Request[multiorch.GetRecoveryStatusRequest]) (*connect.Response[multiorch.GetRecoveryStatusResponse], error)
	// TriggerRecoveryNow immediately executes recovery operations and blocks until
	// either no problems remain or the request context times out.
	// This is intended for testing scenarios requiring deterministic recovery execution.
	//
	// Behavior:
	// - Re-polls all poolers to get fresh health state
	// - Runs recovery cycles repeatedly until no problems are detected
	// - Returns when either: (1) no problems remain, or (2) context times out
	// - If recovery is disabled, this temporarily enables it during this operation
	TriggerRecoveryNow(context.Context, *connect.Request[multiorch.TriggerRecoveryNowRequest]) (*connect.Response[multiorch.TriggerRecoveryNowResponse], error)
	// ApplyCertifiedRuleChange installs a new shard rule using an externally
	// certified revocation. Handles both initial leader appointment (term 0)
	// and stuck-quorum recovery (term > 0): the caller supplies the proposed
	// leader, cohort, and durability policy, plus a cert that attests to which
	// outgoing rule and WAL position the absent cohort members are frozen at.
	ApplyCertifiedRuleChange(context.Context, *connect.Request[multiorch.ApplyCertifiedRuleChangeRequest]) (*connect.Response[multiorch.ApplyCertifiedRuleChangeResponse], error)
}

// NewMultiorchServiceClient constructs a client for the multiorch.MultiorchService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMultiorchServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MultiorchServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	multiorchServiceMethods := multiorch.File_multiorchservice_proto.Services().ByName("MultiorchService").Methods()
	return &multiorchServiceClient{
		getShardStatus: connect.NewClient[multiorch.ShardStatusRequest, multiorch.ShardStatusResponse](
			httpClient,
			baseURL+MultiorchServiceGetShardStatusProcedure,
			connect.WithSchema(multiorchServiceMethods.ByName("GetShardStatus")),
			connect.WithClientOptions(opts...),
		),
		disableRecovery: connect.NewClient[multiorch.DisableRecoveryRequest, multiorch.DisableRecoveryResponse](
			httpClient,
			baseURL+MultiorchServiceDisableRecoveryProcedure,
			connect.WithSchema(multiorchServiceMethods.ByName("DisableRecovery")),
			connect.WithClientOptions(opts...),
		),
		enableRecovery: connect.NewClient[multiorch.EnableRecoveryRequest, multiorch.EnableRecoveryResponse](
			httpClient,
			baseURL+MultiorchServiceEnableRecoveryProcedure,
			connect.WithSchema(multiorchServiceMethods.ByName("EnableRecovery")),
			connect.WithClientOptions(opts...),
		),
		getRecoveryStatus: connect.NewClient[multiorch.GetRecoveryStatusRequest, multiorch.GetRecoveryStatusResponse](
			httpClient,
			baseURL+MultiorchServiceGetRecoveryStatusProcedure,
			connect.WithSchema(multiorchServiceMethods.ByName("GetRecoveryStatus")),
			connect.WithClientOptions(opts...),
		),
		triggerRecoveryNow: connect.NewClient[multiorch.TriggerRecoveryNowRequest, multiorch.TriggerRecoveryNowResponse](
			httpClient,
			baseURL+MultiorchServiceTriggerRecoveryNowProcedure,
			connect.WithSchema(multiorchServiceMethods.ByName("TriggerRecoveryNow")),
			connect.WithClientOptions(opts...),
		),
		applyCertifiedRuleChange: connect.NewClient[multiorch.ApplyCertifiedRuleChangeRequest, multiorch.ApplyCertifiedRuleChangeResponse](
			httpClient,
			baseURL+MultiorchServiceApplyCertifiedRuleChangeProcedure,
			connect.WithSchema(multiorchServiceMethods.ByName("ApplyCertifiedRuleChange")),
			connect.WithClientOptions(opts...),
		),
	}
}

// multiorchServiceClient implements MultiorchServiceClient.
type multiorchServiceClient struct {
	getShardStatus           *connect.Client[multiorch.ShardStatusRequest, multiorch.ShardStatusResponse]
	disableRecovery          *connect.Client[multiorch.DisableRecoveryRequest, multiorch.DisableRecoveryResponse]
	enableRecovery           *connect.Client[multiorch.EnableRecoveryRequest, multiorch.EnableRecoveryResponse]
	getRecoveryStatus        *connect.Client[multiorch.GetRecoveryStatusRequest, multiorch.GetRecoveryStatusResponse]
	triggerRecoveryNow       *connect.Client[multiorch.TriggerRecoveryNowRequest, multiorch.TriggerRecoveryNowResponse]
	applyCertifiedRuleChange *connect.Client[multiorch.ApplyCertifiedRuleChangeRequest, multiorch.ApplyCertifiedRuleChangeResponse]
}

// GetShardStatus calls multiorch.MultiorchService.GetShardStatus.
func (c *multiorchServiceClient) GetShardStatus(ctx context.Context, req *connect.Request[multiorch.ShardStatusRequest]) (*connect.Response[multiorch.ShardStatusResponse], error) {
	return c.getShardStatus.CallUnary(ctx, req)
}

// DisableRecovery calls multiorch.MultiorchService.DisableRecovery.
func (c *multiorchServiceClient) DisableRecovery(ctx context.Context, req *connect.Request[multiorch.DisableRecoveryRequest]) (*connect.Response[multiorch.DisableRecoveryResponse], error) {
	return c.disableRecovery.CallUnary(ctx, req)
}

// EnableRecovery calls multiorch.MultiorchService.EnableRecovery.
func (c *multiorchServiceClient) EnableRecovery(ctx context.Context, req *connect.Request[multiorch.EnableRecoveryRequest]) (*connect.Response[multiorch.EnableRecoveryResponse], error) {
	return c.enableRecovery.CallUnary(ctx, req)
}

// GetRecoveryStatus calls multiorch.MultiorchService.GetRecoveryStatus.
func (c *multiorchServiceClient) GetRecoveryStatus(ctx context.Context, req *connect.Request[multiorch.GetRecoveryStatusRequest]) (*connect.Response[multiorch.GetRecoveryStatusResponse], error) {
	return c.getRecoveryStatus.CallUnary(ctx, req)
}

// TriggerRecoveryNow calls multiorch.MultiorchService.TriggerRecoveryNow.
func (c *multiorchServiceClient) TriggerRecoveryNow(ctx context.Context, req *connect.Request[multiorch.TriggerRecoveryNowRequest]) (*connect.Response[multiorch.TriggerRecoveryNowResponse], error) {
	return c.triggerRecoveryNow.CallUnary(ctx, req)
}

// ApplyCertifiedRuleChange calls multiorch.MultiorchService.ApplyCertifiedRuleChange.
func (c *multiorchServiceClient) ApplyCertifiedRuleChange(ctx context.Context, req *connect.Request[multiorch.ApplyCertifiedRuleChangeRequest]) (*connect.Response[multiorch.ApplyCertifiedRuleChangeResponse], error) {
	return c.applyCertifiedRuleChange.CallUnary(ctx, req)
}

// MultiorchServiceHandler is an implementation of the multiorch.MultiorchService service.
type MultiorchServiceHandler interface {
	// GetShardStatus returns diagnostic information for a specific shard
	GetShardStatus(context.Context, *connect.Request[multiorch.ShardStatusRequest]) (*connect.Response[multiorch.ShardStatusResponse], error)
	// DisableRecovery stops the recovery engine from automatically repairing issues.
	// This is intended for testing scenarios where manual control over recovery is needed.
	// When this returns, no recovery actions are in-flight (strong synchronization guarantee).
	DisableRecovery(context.Context, *connect.Request[multiorch.DisableRecoveryRequest]) (*connect.Response[multiorch.DisableRecoveryResponse], error)
	// EnableRecovery resumes the recovery engine's automatic repair operations.
	EnableRecovery(context.Context, *connect.Request[multiorch.EnableRecoveryRequest]) (*connect.Response[multiorch.EnableRecoveryResponse], error)
	// GetRecoveryStatus returns whether recovery is currently enabled or disabled.
	GetRecoveryStatus(context.Context, *connect.Request[multiorch.GetRecoveryStatusRequest]) (*connect.Response[multiorch.GetRecoveryStatusResponse], error)
	// TriggerRecoveryNow immediately executes recovery operations and blocks until
	// either no problems remain or the request context times out.
	// This is intended for testing scenarios requiring deterministic recovery execution.
	//
	// Behavior:
	// - Re-polls all poolers to get fresh health state
	// - Runs recovery cycles repeatedly until no problems are detected
	// - Returns when either: (1) no problems remain, or (2) context times out
	// - If recovery is disabled, this temporarily enables it during this operation
	TriggerRecoveryNow(context.Context, *connect.Request[multiorch.TriggerRecoveryNowRequest]) (*connect.Response[multiorch.TriggerRecoveryNowResponse], error)
	// ApplyCertifiedRuleChange installs a new shard rule using an externally
	// certified revocation. Handles both initial leader appointment (term 0)
	// and stuck-quorum recovery (term > 0): the caller supplies the proposed
	// leader, cohort, and durability policy, plus a cert that attests to which
	// outgoing rule and WAL position the absent cohort members are frozen at.
	ApplyCertifiedRuleChange(context.Context, *connect.Request[multiorch.ApplyCertifiedRuleChangeRequest]) (*connect.Response[multiorch.ApplyCertifiedRuleChangeResponse], error)
}

// NewMultiorchServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMultiorchServiceHandler(svc MultiorchServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	multiorchServiceMethods := multiorch.File_multiorchservice_proto.Services().ByName("MultiorchService").Methods()
	multiorchServiceGetShardStatusHandler := connect.NewUnaryHandler(
		MultiorchServiceGetShardStatusProcedure,
		svc.GetShardStatus,
		connect.WithSchema(multiorchServiceMethods.ByName("GetShardStatus")),
		connect.WithHandlerOptions(opts...),
	)
	multiorchServiceDisableRecoveryHandler := connect.NewUnaryHandler(
		MultiorchServiceDisableRecoveryProcedure,
		svc.DisableRecovery,
		connect.WithSchema(multiorchServiceMethods.ByName("DisableRecovery")),
		connect.WithHandlerOptions(opts...),
	)
	multiorchServiceEnableRecoveryHandler := connect.NewUnaryHandler(
		MultiorchServiceEnableRecoveryProcedure,
		svc.EnableRecovery,
		connect.WithSchema(multiorchServiceMethods.ByName("EnableRecovery")),
		connect.WithHandlerOptions(opts...),
	)
	multiorchServiceGetRecoveryStatusHandler := connect.NewUnaryHandler(
		MultiorchServiceGetRecoveryStatusProcedure,
		svc.GetRecoveryStatus,
		connect.WithSchema(multiorchServiceMethods.ByName("GetRecoveryStatus")),
		connect.WithHandlerOptions(opts...),
	)
	multiorchServiceTriggerRecoveryNowHandler := connect.NewUnaryHandler(
		MultiorchServiceTriggerRecoveryNowProcedure,
		svc.TriggerRecoveryNow,
		connect.WithSchema(multiorchServiceMethods.ByName("TriggerRecoveryNow")),
		connect.WithHandlerOptions(opts...),
	)
	multiorchServiceApplyCertifiedRuleChangeHandler := connect.NewUnaryHandler(
		MultiorchServiceApplyCertifiedRuleChangeProcedure,
		svc.ApplyCertifiedRuleChange,
		connect.WithSchema(multiorchServiceMethods.ByName("ApplyCertifiedRuleChange")),
		connect.WithHandlerOptions(opts...),
	)
	return "/multiorch.MultiorchService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MultiorchServiceGetShardStatusProcedure:
			multiorchServiceGetShardStatusHandler.ServeHTTP(w, r)
		case MultiorchServiceDisableRecoveryProcedure:
			multiorchServiceDisableRecoveryHandler.ServeHTTP(w, r)
		case MultiorchServiceEnableRecoveryProcedure:
			multiorchServiceEnableRecoveryHandler.ServeHTTP(w, r)
		case MultiorchServiceGetRecoveryStatusProcedure:
			multiorchServiceGetRecoveryStatusHandler.ServeHTTP(w, r)
		case MultiorchServiceTriggerRecoveryNowProcedure:
			multiorchServiceTriggerRecoveryNowHandler.ServeHTTP(w, r)
		case MultiorchServiceApplyCertifiedRuleChangeProcedure:
			multiorchServiceApplyCertifiedRuleChangeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMultiorchServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMultiorchServiceHandler struct{}

func (UnimplementedMultiorchServiceHandler) GetShardStatus(context.Context, *connect.Request[multiorch.ShardStatusRequest]) (*connect.Response[multiorch.ShardStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multiorch.MultiorchService.GetShardStatus is not implemented"))
}

func (UnimplementedMultiorchServiceHandler) DisableRecovery(context.Context, *connect.Request[multiorch.DisableRecoveryRequest]) (*connect.Response[multiorch.DisableRecoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multiorch.MultiorchService.DisableRecovery is not implemented"))
}

func (UnimplementedMultiorchServiceHandler) EnableRecovery(context.Context, *connect.Request[multiorch.EnableRecoveryRequest]) (*connect.Response[multiorch.EnableRecoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multiorch.MultiorchService.EnableRecovery is not implemented"))
}

func (UnimplementedMultiorchServiceHandler) GetRecoveryStatus(context.Context, *connect.Request[multiorch.GetRecoveryStatusRequest]) (*connect.Response[multiorch.GetRecoveryStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multiorch.MultiorchService.GetRecoveryStatus is not implemented"))
}

func (UnimplementedMultiorchServiceHandler) TriggerRecoveryNow(context.Context, *connect.Request[multiorch.TriggerRecoveryNowRequest]) (*connect.Response[multiorch.TriggerRecoveryNowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multiorch.MultiorchService.TriggerRecoveryNow is not implemented"))
}

func (UnimplementedMultiorchServiceHandler) ApplyCertifiedRuleChange(context.Context, *connect.Request[multiorch.ApplyCertifiedRuleChangeRequest]) (*connect.Response[multiorch.ApplyCertifiedRuleChangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multiorch.MultiorchService.ApplyCertifiedRuleChange is not implemented"))
}
