// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multipoolermanagerservice.proto

package multipoolermanager

import (
	context "context"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultipoolerManager_WaitForLSN_FullMethodName                 = "/multipoolermanager.MultipoolerManager/WaitForLSN"
	MultipoolerManager_StartReplication_FullMethodName           = "/multipoolermanager.MultipoolerManager/StartReplication"
	MultipoolerManager_StopReplication_FullMethodName            = "/multipoolermanager.MultipoolerManager/StopReplication"
	MultipoolerManager_Status_FullMethodName                     = "/multipoolermanager.MultipoolerManager/Status"
	MultipoolerManager_Backup_FullMethodName                     = "/multipoolermanager.MultipoolerManager/Backup"
	MultipoolerManager_GetBackups_FullMethodName                 = "/multipoolermanager.MultipoolerManager/GetBackups"
	MultipoolerManager_GetBackupByJobId_FullMethodName           = "/multipoolermanager.MultipoolerManager/GetBackupByJobId"
	MultipoolerManager_ExpireBackups_FullMethodName              = "/multipoolermanager.MultipoolerManager/ExpireBackups"
	MultipoolerManager_VerifyBackups_FullMethodName              = "/multipoolermanager.MultipoolerManager/VerifyBackups"
	MultipoolerManager_ResignLeadership_FullMethodName           = "/multipoolermanager.MultipoolerManager/ResignLeadership"
	MultipoolerManager_SetPostgresRestartsEnabled_FullMethodName = "/multipoolermanager.MultipoolerManager/SetPostgresRestartsEnabled"
	MultipoolerManager_ReconcileFollowers_FullMethodName         = "/multipoolermanager.MultipoolerManager/ReconcileFollowers"
	MultipoolerManager_ReloadConfig_FullMethodName               = "/multipoolermanager.MultipoolerManager/ReloadConfig"
	MultipoolerManager_ManagerHealthStream_FullMethodName        = "/multipoolermanager.MultipoolerManager/ManagerHealthStream"
)

// MultipoolerManagerClient is the client API for MultipoolerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultipoolerManager provides management APIs for PostgreSQL connection poolers
type MultipoolerManagerClient interface {
	// WaitForLSN waits for PostgreSQL server to reach a specific LSN position
	WaitForLSN(ctx context.Context, in *multipoolermanagerdata.WaitForLSNRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.WaitForLSNResponse, error)
	// StartReplication starts WAL replay on standby (calls pg_wal_replay_resume)
	StartReplication(ctx context.Context, in *multipoolermanagerdata.StartReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StartReplicationResponse, error)
	// StopReplication stops WAL replay on standby (calls pg_wal_replay_pause)
	StopReplication(ctx context.Context, in *multipoolermanagerdata.StopReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StopReplicationResponse, error)
	// Status gets unified status that works for both PRIMARY and REPLICA poolers
	// The multipooler returns information based on what type it believes itself to be,
	// avoiding disparity between what Multiorch thinks versus actual state
	Status(ctx context.Context, in *multipoolermanagerdata.StatusRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StatusResponse, error)
	// Backup performs a backup
	Backup(ctx context.Context, in *multipoolermanagerdata.BackupRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.BackupResponse, error)
	// GetBackups retrieves backup information
	GetBackups(ctx context.Context, in *multipoolermanagerdata.GetBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupsResponse, error)
	// GetBackupByJobId queries a backup by its job_id annotation.
	// Returns the backup metadata if found, or nil backup if not.
	GetBackupByJobId(ctx context.Context, in *multipoolermanagerdata.GetBackupByJobIdRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupByJobIdResponse, error)
	// ExpireBackups removes backups that exceed the configured retention policy.
	ExpireBackups(ctx context.Context, in *multipoolermanagerdata.ExpireBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ExpireBackupsResponse, error)
	// VerifyBackups runs a full-stanza pgbackrest verify (no --set). This is
	// a periodic backup-integrity check; not scoped to any single backup.
	VerifyBackups(ctx context.Context, in *multipoolermanagerdata.VerifyBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.VerifyBackupsResponse, error)
	// ResignLeadership gracefully resigns this pooler from leadership.
	// Transitions the pooler to NOT_SERVING (rejecting new queries with MTF01),
	// drains write connections, publishes REQUESTING_DEMOTION, and returns the
	// WAL flush LSN at the moment writes were quiesced. The caller can then wait
	// for standbys to reach that LSN before triggering a new election.
	//
	// Only valid on a pooler that is currently the consensus leader (PRIMARY).
	// Does NOT restart postgres as standby — that happens later via the normal
	// Recruit path when multiorch picks up REQUESTING_DEMOTION.
	ResignLeadership(ctx context.Context, in *multipoolermanagerdata.ResignLeadershipRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ResignLeadershipResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts.
	// When disabled, the monitor continues to run but will not auto-restart a stopped
	// PostgreSQL instance. Used by tests and demos to prevent premature restarts during
	// controlled failovers.
	SetPostgresRestartsEnabled(ctx context.Context, in *multipoolermanagerdata.SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error)
	// ReconcileFollowers declares to the primary the full set of cohort-eligible
	// follower members it should hold per-follower physical replication slots for.
	// The primary creates any missing slot and drops managed slots for members no
	// longer in the set. It is level-triggered and declarative: the orchestrator
	// re-sends the set each cycle, so a missed event or a primary restart
	// self-heals. It creates only the physical slots (so a late-joining standby
	// can stream); it does NOT touch synchronized_standby_slots — a follower is
	// added there only once it is streaming and caught up, via the cohort path.
	ReconcileFollowers(ctx context.Context, in *multipoolermanagerdata.ReconcileFollowersRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ReconcileFollowersResponse, error)
	// ReloadConfig triggers a PostgreSQL configuration reload (SIGHUP via pgctld)
	// on this multipooler's local PostgreSQL and confirms it took effect by
	// waiting for pg_conf_load_time() to advance. The returned config_load_time
	// lets the caller verify its config-file change was re-read.
	ReloadConfig(ctx context.Context, in *multipoolermanagerdata.ReloadConfigRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ReloadConfigResponse, error)
	// ManagerHealthStream is a bidirectional health stream between orchestrator
	// and pooler.
	//
	// The orchestrator sends a start message (ManagerHealthStreamClientMessage
	// with the start field set) to open the stream, then may send poll requests
	// at any time to trigger an immediate snapshot.
	//
	// The pooler sends a full health snapshot on connection, on every state
	// change, in response to poll requests, and periodically as a heartbeat.
	// Every message is a complete snapshot — there are no incremental updates.
	//
	// The orchestrator MUST implement a staleness timeout. The recommended
	// timeout is provided in the timeout field of each snapshot. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	ManagerHealthStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse], error)
}

type multipoolerManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewMultipoolerManagerClient(cc grpc.ClientConnInterface) MultipoolerManagerClient {
	return &multipoolerManagerClient{cc}
}

func (c *multipoolerManagerClient) WaitForLSN(ctx context.Context, in *multipoolermanagerdata.WaitForLSNRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.WaitForLSNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.WaitForLSNResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_WaitForLSN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) StartReplication(ctx context.Context, in *multipoolermanagerdata.StartReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StartReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.StartReplicationResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_StartReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) StopReplication(ctx context.Context, in *multipoolermanagerdata.StopReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StopReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.StopReplicationResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_StopReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) Status(ctx context.Context, in *multipoolermanagerdata.StatusRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.StatusResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) Backup(ctx context.Context, in *multipoolermanagerdata.BackupRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.BackupResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) GetBackups(ctx context.Context, in *multipoolermanagerdata.GetBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.GetBackupsResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_GetBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) GetBackupByJobId(ctx context.Context, in *multipoolermanagerdata.GetBackupByJobIdRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupByJobIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.GetBackupByJobIdResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_GetBackupByJobId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) ExpireBackups(ctx context.Context, in *multipoolermanagerdata.ExpireBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ExpireBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.ExpireBackupsResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_ExpireBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) VerifyBackups(ctx context.Context, in *multipoolermanagerdata.VerifyBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.VerifyBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.VerifyBackupsResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_VerifyBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) ResignLeadership(ctx context.Context, in *multipoolermanagerdata.ResignLeadershipRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ResignLeadershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.ResignLeadershipResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_ResignLeadership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) SetPostgresRestartsEnabled(ctx context.Context, in *multipoolermanagerdata.SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.SetPostgresRestartsEnabledResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_SetPostgresRestartsEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) ReconcileFollowers(ctx context.Context, in *multipoolermanagerdata.ReconcileFollowersRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ReconcileFollowersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.ReconcileFollowersResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_ReconcileFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) ReloadConfig(ctx context.Context, in *multipoolermanagerdata.ReloadConfigRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ReloadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.ReloadConfigResponse)
	err := c.cc.Invoke(ctx, MultipoolerManager_ReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multipoolerManagerClient) ManagerHealthStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultipoolerManager_ServiceDesc.Streams[0], MultipoolerManager_ManagerHealthStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerManager_ManagerHealthStreamClient = grpc.BidiStreamingClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]

// MultipoolerManagerServer is the server API for MultipoolerManager service.
// All implementations must embed UnimplementedMultipoolerManagerServer
// for forward compatibility.
//
// MultipoolerManager provides management APIs for PostgreSQL connection poolers
type MultipoolerManagerServer interface {
	// WaitForLSN waits for PostgreSQL server to reach a specific LSN position
	WaitForLSN(context.Context, *multipoolermanagerdata.WaitForLSNRequest) (*multipoolermanagerdata.WaitForLSNResponse, error)
	// StartReplication starts WAL replay on standby (calls pg_wal_replay_resume)
	StartReplication(context.Context, *multipoolermanagerdata.StartReplicationRequest) (*multipoolermanagerdata.StartReplicationResponse, error)
	// StopReplication stops WAL replay on standby (calls pg_wal_replay_pause)
	StopReplication(context.Context, *multipoolermanagerdata.StopReplicationRequest) (*multipoolermanagerdata.StopReplicationResponse, error)
	// Status gets unified status that works for both PRIMARY and REPLICA poolers
	// The multipooler returns information based on what type it believes itself to be,
	// avoiding disparity between what Multiorch thinks versus actual state
	Status(context.Context, *multipoolermanagerdata.StatusRequest) (*multipoolermanagerdata.StatusResponse, error)
	// Backup performs a backup
	Backup(context.Context, *multipoolermanagerdata.BackupRequest) (*multipoolermanagerdata.BackupResponse, error)
	// GetBackups retrieves backup information
	GetBackups(context.Context, *multipoolermanagerdata.GetBackupsRequest) (*multipoolermanagerdata.GetBackupsResponse, error)
	// GetBackupByJobId queries a backup by its job_id annotation.
	// Returns the backup metadata if found, or nil backup if not.
	GetBackupByJobId(context.Context, *multipoolermanagerdata.GetBackupByJobIdRequest) (*multipoolermanagerdata.GetBackupByJobIdResponse, error)
	// ExpireBackups removes backups that exceed the configured retention policy.
	ExpireBackups(context.Context, *multipoolermanagerdata.ExpireBackupsRequest) (*multipoolermanagerdata.ExpireBackupsResponse, error)
	// VerifyBackups runs a full-stanza pgbackrest verify (no --set). This is
	// a periodic backup-integrity check; not scoped to any single backup.
	VerifyBackups(context.Context, *multipoolermanagerdata.VerifyBackupsRequest) (*multipoolermanagerdata.VerifyBackupsResponse, error)
	// ResignLeadership gracefully resigns this pooler from leadership.
	// Transitions the pooler to NOT_SERVING (rejecting new queries with MTF01),
	// drains write connections, publishes REQUESTING_DEMOTION, and returns the
	// WAL flush LSN at the moment writes were quiesced. The caller can then wait
	// for standbys to reach that LSN before triggering a new election.
	//
	// Only valid on a pooler that is currently the consensus leader (PRIMARY).
	// Does NOT restart postgres as standby — that happens later via the normal
	// Recruit path when multiorch picks up REQUESTING_DEMOTION.
	ResignLeadership(context.Context, *multipoolermanagerdata.ResignLeadershipRequest) (*multipoolermanagerdata.ResignLeadershipResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts.
	// When disabled, the monitor continues to run but will not auto-restart a stopped
	// PostgreSQL instance. Used by tests and demos to prevent premature restarts during
	// controlled failovers.
	SetPostgresRestartsEnabled(context.Context, *multipoolermanagerdata.SetPostgresRestartsEnabledRequest) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error)
	// ReconcileFollowers declares to the primary the full set of cohort-eligible
	// follower members it should hold per-follower physical replication slots for.
	// The primary creates any missing slot and drops managed slots for members no
	// longer in the set. It is level-triggered and declarative: the orchestrator
	// re-sends the set each cycle, so a missed event or a primary restart
	// self-heals. It creates only the physical slots (so a late-joining standby
	// can stream); it does NOT touch synchronized_standby_slots — a follower is
	// added there only once it is streaming and caught up, via the cohort path.
	ReconcileFollowers(context.Context, *multipoolermanagerdata.ReconcileFollowersRequest) (*multipoolermanagerdata.ReconcileFollowersResponse, error)
	// ReloadConfig triggers a PostgreSQL configuration reload (SIGHUP via pgctld)
	// on this multipooler's local PostgreSQL and confirms it took effect by
	// waiting for pg_conf_load_time() to advance. The returned config_load_time
	// lets the caller verify its config-file change was re-read.
	ReloadConfig(context.Context, *multipoolermanagerdata.ReloadConfigRequest) (*multipoolermanagerdata.ReloadConfigResponse, error)
	// ManagerHealthStream is a bidirectional health stream between orchestrator
	// and pooler.
	//
	// The orchestrator sends a start message (ManagerHealthStreamClientMessage
	// with the start field set) to open the stream, then may send poll requests
	// at any time to trigger an immediate snapshot.
	//
	// The pooler sends a full health snapshot on connection, on every state
	// change, in response to poll requests, and periodically as a heartbeat.
	// Every message is a complete snapshot — there are no incremental updates.
	//
	// The orchestrator MUST implement a staleness timeout. The recommended
	// timeout is provided in the timeout field of each snapshot. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	ManagerHealthStream(grpc.BidiStreamingServer[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]) error
	mustEmbedUnimplementedMultipoolerManagerServer()
}

// UnimplementedMultipoolerManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultipoolerManagerServer struct{}

func (UnimplementedMultipoolerManagerServer) WaitForLSN(context.Context, *multipoolermanagerdata.WaitForLSNRequest) (*multipoolermanagerdata.WaitForLSNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForLSN not implemented")
}
func (UnimplementedMultipoolerManagerServer) StartReplication(context.Context, *multipoolermanagerdata.StartReplicationRequest) (*multipoolermanagerdata.StartReplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartReplication not implemented")
}
func (UnimplementedMultipoolerManagerServer) StopReplication(context.Context, *multipoolermanagerdata.StopReplicationRequest) (*multipoolermanagerdata.StopReplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopReplication not implemented")
}
func (UnimplementedMultipoolerManagerServer) Status(context.Context, *multipoolermanagerdata.StatusRequest) (*multipoolermanagerdata.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMultipoolerManagerServer) Backup(context.Context, *multipoolermanagerdata.BackupRequest) (*multipoolermanagerdata.BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedMultipoolerManagerServer) GetBackups(context.Context, *multipoolermanagerdata.GetBackupsRequest) (*multipoolermanagerdata.GetBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackups not implemented")
}
func (UnimplementedMultipoolerManagerServer) GetBackupByJobId(context.Context, *multipoolermanagerdata.GetBackupByJobIdRequest) (*multipoolermanagerdata.GetBackupByJobIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackupByJobId not implemented")
}
func (UnimplementedMultipoolerManagerServer) ExpireBackups(context.Context, *multipoolermanagerdata.ExpireBackupsRequest) (*multipoolermanagerdata.ExpireBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireBackups not implemented")
}
func (UnimplementedMultipoolerManagerServer) VerifyBackups(context.Context, *multipoolermanagerdata.VerifyBackupsRequest) (*multipoolermanagerdata.VerifyBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBackups not implemented")
}
func (UnimplementedMultipoolerManagerServer) ResignLeadership(context.Context, *multipoolermanagerdata.ResignLeadershipRequest) (*multipoolermanagerdata.ResignLeadershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResignLeadership not implemented")
}
func (UnimplementedMultipoolerManagerServer) SetPostgresRestartsEnabled(context.Context, *multipoolermanagerdata.SetPostgresRestartsEnabledRequest) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPostgresRestartsEnabled not implemented")
}
func (UnimplementedMultipoolerManagerServer) ReconcileFollowers(context.Context, *multipoolermanagerdata.ReconcileFollowersRequest) (*multipoolermanagerdata.ReconcileFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconcileFollowers not implemented")
}
func (UnimplementedMultipoolerManagerServer) ReloadConfig(context.Context, *multipoolermanagerdata.ReloadConfigRequest) (*multipoolermanagerdata.ReloadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedMultipoolerManagerServer) ManagerHealthStream(grpc.BidiStreamingServer[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ManagerHealthStream not implemented")
}
func (UnimplementedMultipoolerManagerServer) mustEmbedUnimplementedMultipoolerManagerServer() {}
func (UnimplementedMultipoolerManagerServer) testEmbeddedByValue()                            {}

// UnsafeMultipoolerManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultipoolerManagerServer will
// result in compilation errors.
type UnsafeMultipoolerManagerServer interface {
	mustEmbedUnimplementedMultipoolerManagerServer()
}

func RegisterMultipoolerManagerServer(s grpc.ServiceRegistrar, srv MultipoolerManagerServer) {
	// If the following call pancis, it indicates UnimplementedMultipoolerManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultipoolerManager_ServiceDesc, srv)
}

func _MultipoolerManager_WaitForLSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.WaitForLSNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).WaitForLSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_WaitForLSN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).WaitForLSN(ctx, req.(*multipoolermanagerdata.WaitForLSNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_StartReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.StartReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).StartReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_StartReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).StartReplication(ctx, req.(*multipoolermanagerdata.StartReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_StopReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.StopReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).StopReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_StopReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).StopReplication(ctx, req.(*multipoolermanagerdata.StopReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).Status(ctx, req.(*multipoolermanagerdata.StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).Backup(ctx, req.(*multipoolermanagerdata.BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_GetBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.GetBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).GetBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_GetBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).GetBackups(ctx, req.(*multipoolermanagerdata.GetBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_GetBackupByJobId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.GetBackupByJobIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).GetBackupByJobId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_GetBackupByJobId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).GetBackupByJobId(ctx, req.(*multipoolermanagerdata.GetBackupByJobIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_ExpireBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.ExpireBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).ExpireBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_ExpireBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).ExpireBackups(ctx, req.(*multipoolermanagerdata.ExpireBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_VerifyBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.VerifyBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).VerifyBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_VerifyBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).VerifyBackups(ctx, req.(*multipoolermanagerdata.VerifyBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_ResignLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.ResignLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).ResignLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_ResignLeadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).ResignLeadership(ctx, req.(*multipoolermanagerdata.ResignLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_SetPostgresRestartsEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.SetPostgresRestartsEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).SetPostgresRestartsEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_SetPostgresRestartsEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).SetPostgresRestartsEnabled(ctx, req.(*multipoolermanagerdata.SetPostgresRestartsEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_ReconcileFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.ReconcileFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).ReconcileFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_ReconcileFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).ReconcileFollowers(ctx, req.(*multipoolermanagerdata.ReconcileFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultipoolerManagerServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultipoolerManager_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultipoolerManagerServer).ReloadConfig(ctx, req.(*multipoolermanagerdata.ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultipoolerManager_ManagerHealthStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultipoolerManagerServer).ManagerHealthStream(&grpc.GenericServerStream[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultipoolerManager_ManagerHealthStreamServer = grpc.BidiStreamingServer[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]

// MultipoolerManager_ServiceDesc is the grpc.ServiceDesc for MultipoolerManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultipoolerManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multipoolermanager.MultipoolerManager",
	HandlerType: (*MultipoolerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WaitForLSN",
			Handler:    _MultipoolerManager_WaitForLSN_Handler,
		},
		{
			MethodName: "StartReplication",
			Handler:    _MultipoolerManager_StartReplication_Handler,
		},
		{
			MethodName: "StopReplication",
			Handler:    _MultipoolerManager_StopReplication_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _MultipoolerManager_Status_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _MultipoolerManager_Backup_Handler,
		},
		{
			MethodName: "GetBackups",
			Handler:    _MultipoolerManager_GetBackups_Handler,
		},
		{
			MethodName: "GetBackupByJobId",
			Handler:    _MultipoolerManager_GetBackupByJobId_Handler,
		},
		{
			MethodName: "ExpireBackups",
			Handler:    _MultipoolerManager_ExpireBackups_Handler,
		},
		{
			MethodName: "VerifyBackups",
			Handler:    _MultipoolerManager_VerifyBackups_Handler,
		},
		{
			MethodName: "ResignLeadership",
			Handler:    _MultipoolerManager_ResignLeadership_Handler,
		},
		{
			MethodName: "SetPostgresRestartsEnabled",
			Handler:    _MultipoolerManager_SetPostgresRestartsEnabled_Handler,
		},
		{
			MethodName: "ReconcileFollowers",
			Handler:    _MultipoolerManager_ReconcileFollowers_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _MultipoolerManager_ReloadConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ManagerHealthStream",
			Handler:       _MultipoolerManager_ManagerHealthStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "multipoolermanagerservice.proto",
}
