// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: consensusdata.proto

package consensusdata

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CoordinatorProposal is a coordinator-assisted rule proposal. It either reflects
// a rule that's not yet in WAL that the coordinator wants to write, or it could
// reflect a rule discovered in WAL that hasn't been propagated to the point of
// becoming a decision.
type CoordinatorProposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authority under which this proposal is made. Coordinators must revoke
	// previous agents before making a proposal.
	TermRevocation *clustermetadata.TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	// The node that should become primary to facilitate this proposal.
	ProposalLeader *clustermetadata.PoolerAddress `protobuf:"bytes,2,opt,name=proposal_leader,json=proposalLeader,proto3" json:"proposal_leader,omitempty"`
	// The transition this proposal makes: decision is the full outgoing decision
	// this proposal supersedes. proposal is the full new rule being proposed: an
	// entirely new rule or an existing one that hasn't yet finished propagating to
	// durability.
	//
	// TODO: decision here doesn't always mean a confirmed decision — propagation
	// (see go/common/consensus/proposals.go's buildProposalCore) can legitimately
	// set it to a rule that was only ever an undecided proposal on the outgoing
	// side, trusted as the baseline being superseded. RulePosition{Decision,
	// Proposal} is otherwise used to mean "a pooler's own confirmed decision plus
	// any outstanding proposal beyond it" (PoolerPosition.position), a different
	// meaning that happens to share this shape. Introduce a dedicated message for
	// a coordinator's proposed transition instead of reusing RulePosition here.
	ProposedTransition *clustermetadata.RulePosition `protobuf:"bytes,3,opt,name=proposed_transition,json=proposedTransition,proto3" json:"proposed_transition,omitempty"`
	// When true, the leader must apply the incoming cohort GUC directly without
	// first satisfying the outgoing cohort quorum. Only valid for externally-
	// certified proposals (bootstrap, etc.).
	SkipOutgoingQuorum bool `protobuf:"varint,4,opt,name=skip_outgoing_quorum,json=skipOutgoingQuorum,proto3" json:"skip_outgoing_quorum,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CoordinatorProposal) Reset() {
	*x = CoordinatorProposal{}
	mi := &file_consensusdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorProposal) ProtoMessage() {}

func (x *CoordinatorProposal) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorProposal.ProtoReflect.Descriptor instead.
func (*CoordinatorProposal) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinatorProposal) GetTermRevocation() *clustermetadata.TermRevocation {
	if x != nil {
		return x.TermRevocation
	}
	return nil
}

func (x *CoordinatorProposal) GetProposalLeader() *clustermetadata.PoolerAddress {
	if x != nil {
		return x.ProposalLeader
	}
	return nil
}

func (x *CoordinatorProposal) GetProposedTransition() *clustermetadata.RulePosition {
	if x != nil {
		return x.ProposedTransition
	}
	return nil
}

func (x *CoordinatorProposal) GetSkipOutgoingQuorum() bool {
	if x != nil {
		return x.SkipOutgoingQuorum
	}
	return false
}

// RecruitRequest asks a pooler to revoke all terms below the one in the
// enclosed term_revocation and record the coordinator's exclusive right to
// propose at this term.
type RecruitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The revocation to accept. The pooler persists this to disk and responds
	// with its current ConsensusStatus (which includes the updated revocation).
	TermRevocation *clustermetadata.TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecruitRequest) Reset() {
	*x = RecruitRequest{}
	mi := &file_consensusdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecruitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitRequest) ProtoMessage() {}

func (x *RecruitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitRequest.ProtoReflect.Descriptor instead.
func (*RecruitRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{1}
}

func (x *RecruitRequest) GetTermRevocation() *clustermetadata.TermRevocation {
	if x != nil {
		return x.TermRevocation
	}
	return nil
}

// RecruitResponse carries the pooler's authoritative state after processing
// a RecruitRequest. The coordinator uses current_position to select the best
// promotion candidate.
type RecruitResponse struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecruitResponse) Reset() {
	*x = RecruitResponse{}
	mi := &file_consensusdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecruitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitResponse) ProtoMessage() {}

func (x *RecruitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitResponse.ProtoReflect.Descriptor instead.
func (*RecruitResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{2}
}

func (x *RecruitResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

// PromoteRequest carries the coordinator's complete proposal for a new shard
// state. Every cohort member receives this: the designated leader promotes
// itself; all others configure replication toward the new primary.
type PromoteRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Proposal *CoordinatorProposal   `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	// Human-readable reason for this proposal (e.g. "dead_primary", "bootstrap").
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// IDs of cohort members that accepted the term revocation during recruitment.
	// Used to record which nodes acknowledged the proposal in the rule history.
	AcceptedNodeIds []*clustermetadata.ID `protobuf:"bytes,3,rep,name=accepted_node_ids,json=acceptedNodeIds,proto3" json:"accepted_node_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PromoteRequest) Reset() {
	*x = PromoteRequest{}
	mi := &file_consensusdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRequest) ProtoMessage() {}

func (x *PromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRequest.ProtoReflect.Descriptor instead.
func (*PromoteRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{3}
}

func (x *PromoteRequest) GetProposal() *CoordinatorProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *PromoteRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PromoteRequest) GetAcceptedNodeIds() []*clustermetadata.ID {
	if x != nil {
		return x.AcceptedNodeIds
	}
	return nil
}

// PromoteResponse carries the pooler's state after applying a PromoteRequest.
type PromoteResponse struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PromoteResponse) Reset() {
	*x = PromoteResponse{}
	mi := &file_consensusdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteResponse) ProtoMessage() {}

func (x *PromoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteResponse.ProtoReflect.Descriptor instead.
func (*PromoteResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{4}
}

func (x *PromoteResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

// SetPrimaryRequest tells a pooler about the current leader and the rule
// the caller knows the cluster is at. The pooler compares the supplied rule
// against its own; if the supplied rule is strictly higher it applies the
// change (standby: update primary_conninfo; stale primary: demote), otherwise
// it returns success without changes. Idempotent under retries and safe
// against out-of-order delivery from stale recovery rounds.
//
// The pooler also validates that leader.id matches rule.leader_id — the
// rule's identity is authoritative; the leader field is just the contact
// information needed to act on that identity.
type SetPrimaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The (position, primary, rewind_ready) the follower should adopt. Contact
	// info for the leader is replication_primary.primary (host + postgres_port
	// used to rewrite primary_conninfo); the position is
	// replication_primary.position, which the pooler compares against its own
	// observed position and only applies when strictly higher. primary.id must
	// match the position's leader_id. replication_primary.rewind_ready relays
	// whether the leader has checkpointed onto its current timeline: a
	// diverged follower defers its pg_rewind until it is true, but sets up
	// primary_conninfo and attempts to stream regardless.
	ReplicationPrimary *clustermetadata.ReplicationPrimary `protobuf:"bytes,3,opt,name=replication_primary,json=replicationPrimary,proto3" json:"replication_primary,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetPrimaryRequest) Reset() {
	*x = SetPrimaryRequest{}
	mi := &file_consensusdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryRequest) ProtoMessage() {}

func (x *SetPrimaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryRequest.ProtoReflect.Descriptor instead.
func (*SetPrimaryRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{5}
}

func (x *SetPrimaryRequest) GetReplicationPrimary() *clustermetadata.ReplicationPrimary {
	if x != nil {
		return x.ReplicationPrimary
	}
	return nil
}

// SetPrimaryResponse carries the pooler's state after processing a
// SetPrimaryRequest.
type SetPrimaryResponse struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetPrimaryResponse) Reset() {
	*x = SetPrimaryResponse{}
	mi := &file_consensusdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryResponse) ProtoMessage() {}

func (x *SetPrimaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryResponse.ProtoReflect.Descriptor instead.
func (*SetPrimaryResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{6}
}

func (x *SetPrimaryResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

var File_consensusdata_proto protoreflect.FileDescriptor

const file_consensusdata_proto_rawDesc = "" +
	"\n" +
	"\x13consensusdata.proto\x12\rconsensusdata\x1a\x15clustermetadata.proto\"\xaa\x02\n" +
	"\x13CoordinatorProposal\x12H\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1f.clustermetadata.TermRevocationR\x0etermRevocation\x12G\n" +
	"\x0fproposal_leader\x18\x02 \x01(\v2\x1e.clustermetadata.PoolerAddressR\x0eproposalLeader\x12N\n" +
	"\x13proposed_transition\x18\x03 \x01(\v2\x1d.clustermetadata.RulePositionR\x12proposedTransition\x120\n" +
	"\x14skip_outgoing_quorum\x18\x04 \x01(\bR\x12skipOutgoingQuorum\"Z\n" +
	"\x0eRecruitRequest\x12H\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1f.clustermetadata.TermRevocationR\x0etermRevocation\"^\n" +
	"\x0fRecruitResponse\x12K\n" +
	"\x10consensus_status\x18\x01 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\"\xa9\x01\n" +
	"\x0ePromoteRequest\x12>\n" +
	"\bproposal\x18\x01 \x01(\v2\".consensusdata.CoordinatorProposalR\bproposal\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12?\n" +
	"\x11accepted_node_ids\x18\x03 \x03(\v2\x13.clustermetadata.IDR\x0facceptedNodeIds\"^\n" +
	"\x0fPromoteResponse\x12K\n" +
	"\x10consensus_status\x18\x01 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\"i\n" +
	"\x11SetPrimaryRequest\x12T\n" +
	"\x13replication_primary\x18\x03 \x01(\v2#.clustermetadata.ReplicationPrimaryR\x12replicationPrimary\"a\n" +
	"\x12SetPrimaryResponse\x12K\n" +
	"\x10consensus_status\x18\x01 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatusB4Z2github.com/multigres/multigres/go/pb/consensusdatab\x06proto3"

var (
	file_consensusdata_proto_rawDescOnce sync.Once
	file_consensusdata_proto_rawDescData []byte
)

func file_consensusdata_proto_rawDescGZIP() []byte {
	file_consensusdata_proto_rawDescOnce.Do(func() {
		file_consensusdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensusdata_proto_rawDesc), len(file_consensusdata_proto_rawDesc)))
	})
	return file_consensusdata_proto_rawDescData
}

var file_consensusdata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_consensusdata_proto_goTypes = []any{
	(*CoordinatorProposal)(nil),                // 0: consensusdata.CoordinatorProposal
	(*RecruitRequest)(nil),                     // 1: consensusdata.RecruitRequest
	(*RecruitResponse)(nil),                    // 2: consensusdata.RecruitResponse
	(*PromoteRequest)(nil),                     // 3: consensusdata.PromoteRequest
	(*PromoteResponse)(nil),                    // 4: consensusdata.PromoteResponse
	(*SetPrimaryRequest)(nil),                  // 5: consensusdata.SetPrimaryRequest
	(*SetPrimaryResponse)(nil),                 // 6: consensusdata.SetPrimaryResponse
	(*clustermetadata.TermRevocation)(nil),     // 7: clustermetadata.TermRevocation
	(*clustermetadata.PoolerAddress)(nil),      // 8: clustermetadata.PoolerAddress
	(*clustermetadata.RulePosition)(nil),       // 9: clustermetadata.RulePosition
	(*clustermetadata.ConsensusStatus)(nil),    // 10: clustermetadata.ConsensusStatus
	(*clustermetadata.ID)(nil),                 // 11: clustermetadata.ID
	(*clustermetadata.ReplicationPrimary)(nil), // 12: clustermetadata.ReplicationPrimary
}
var file_consensusdata_proto_depIdxs = []int32{
	7,  // 0: consensusdata.CoordinatorProposal.term_revocation:type_name -> clustermetadata.TermRevocation
	8,  // 1: consensusdata.CoordinatorProposal.proposal_leader:type_name -> clustermetadata.PoolerAddress
	9,  // 2: consensusdata.CoordinatorProposal.proposed_transition:type_name -> clustermetadata.RulePosition
	7,  // 3: consensusdata.RecruitRequest.term_revocation:type_name -> clustermetadata.TermRevocation
	10, // 4: consensusdata.RecruitResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	0,  // 5: consensusdata.PromoteRequest.proposal:type_name -> consensusdata.CoordinatorProposal
	11, // 6: consensusdata.PromoteRequest.accepted_node_ids:type_name -> clustermetadata.ID
	10, // 7: consensusdata.PromoteResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	12, // 8: consensusdata.SetPrimaryRequest.replication_primary:type_name -> clustermetadata.ReplicationPrimary
	10, // 9: consensusdata.SetPrimaryResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_consensusdata_proto_init() }
func file_consensusdata_proto_init() {
	if File_consensusdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensusdata_proto_rawDesc), len(file_consensusdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensusdata_proto_goTypes,
		DependencyIndexes: file_consensusdata_proto_depIdxs,
		MessageInfos:      file_consensusdata_proto_msgTypes,
	}.Build()
	File_consensusdata_proto = out.File
	file_consensusdata_proto_goTypes = nil
	file_consensusdata_proto_depIdxs = nil
}
