// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: multipoolermanagerservice.proto

package multipoolermanagerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	multipoolermanager "github.com/multigres/multigres/go/pb/multipoolermanager"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MultipoolerManagerName is the fully-qualified name of the MultipoolerManager service.
	MultipoolerManagerName = "multipoolermanager.MultipoolerManager"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MultipoolerManagerWaitForLSNProcedure is the fully-qualified name of the MultipoolerManager's
	// WaitForLSN RPC.
	MultipoolerManagerWaitForLSNProcedure = "/multipoolermanager.MultipoolerManager/WaitForLSN"
	// MultipoolerManagerStartReplicationProcedure is the fully-qualified name of the
	// MultipoolerManager's StartReplication RPC.
	MultipoolerManagerStartReplicationProcedure = "/multipoolermanager.MultipoolerManager/StartReplication"
	// MultipoolerManagerStopReplicationProcedure is the fully-qualified name of the
	// MultipoolerManager's StopReplication RPC.
	MultipoolerManagerStopReplicationProcedure = "/multipoolermanager.MultipoolerManager/StopReplication"
	// MultipoolerManagerStatusProcedure is the fully-qualified name of the MultipoolerManager's Status
	// RPC.
	MultipoolerManagerStatusProcedure = "/multipoolermanager.MultipoolerManager/Status"
	// MultipoolerManagerBackupProcedure is the fully-qualified name of the MultipoolerManager's Backup
	// RPC.
	MultipoolerManagerBackupProcedure = "/multipoolermanager.MultipoolerManager/Backup"
	// MultipoolerManagerGetBackupsProcedure is the fully-qualified name of the MultipoolerManager's
	// GetBackups RPC.
	MultipoolerManagerGetBackupsProcedure = "/multipoolermanager.MultipoolerManager/GetBackups"
	// MultipoolerManagerGetBackupByJobIdProcedure is the fully-qualified name of the
	// MultipoolerManager's GetBackupByJobId RPC.
	MultipoolerManagerGetBackupByJobIdProcedure = "/multipoolermanager.MultipoolerManager/GetBackupByJobId"
	// MultipoolerManagerExpireBackupsProcedure is the fully-qualified name of the MultipoolerManager's
	// ExpireBackups RPC.
	MultipoolerManagerExpireBackupsProcedure = "/multipoolermanager.MultipoolerManager/ExpireBackups"
	// MultipoolerManagerVerifyBackupsProcedure is the fully-qualified name of the MultipoolerManager's
	// VerifyBackups RPC.
	MultipoolerManagerVerifyBackupsProcedure = "/multipoolermanager.MultipoolerManager/VerifyBackups"
	// MultipoolerManagerResignLeadershipProcedure is the fully-qualified name of the
	// MultipoolerManager's ResignLeadership RPC.
	MultipoolerManagerResignLeadershipProcedure = "/multipoolermanager.MultipoolerManager/ResignLeadership"
	// MultipoolerManagerSetPostgresRestartsEnabledProcedure is the fully-qualified name of the
	// MultipoolerManager's SetPostgresRestartsEnabled RPC.
	MultipoolerManagerSetPostgresRestartsEnabledProcedure = "/multipoolermanager.MultipoolerManager/SetPostgresRestartsEnabled"
	// MultipoolerManagerReconcileFollowersProcedure is the fully-qualified name of the
	// MultipoolerManager's ReconcileFollowers RPC.
	MultipoolerManagerReconcileFollowersProcedure = "/multipoolermanager.MultipoolerManager/ReconcileFollowers"
	// MultipoolerManagerReloadConfigProcedure is the fully-qualified name of the MultipoolerManager's
	// ReloadConfig RPC.
	MultipoolerManagerReloadConfigProcedure = "/multipoolermanager.MultipoolerManager/ReloadConfig"
	// MultipoolerManagerManagerHealthStreamProcedure is the fully-qualified name of the
	// MultipoolerManager's ManagerHealthStream RPC.
	MultipoolerManagerManagerHealthStreamProcedure = "/multipoolermanager.MultipoolerManager/ManagerHealthStream"
)

// MultipoolerManagerClient is a client for the multipoolermanager.MultipoolerManager service.
type MultipoolerManagerClient interface {
	// WaitForLSN waits for PostgreSQL server to reach a specific LSN position
	WaitForLSN(context.Context, *connect.Request[multipoolermanagerdata.WaitForLSNRequest]) (*connect.Response[multipoolermanagerdata.WaitForLSNResponse], error)
	// StartReplication starts WAL replay on standby (calls pg_wal_replay_resume)
	StartReplication(context.Context, *connect.Request[multipoolermanagerdata.StartReplicationRequest]) (*connect.Response[multipoolermanagerdata.StartReplicationResponse], error)
	// StopReplication stops WAL replay on standby (calls pg_wal_replay_pause)
	StopReplication(context.Context, *connect.Request[multipoolermanagerdata.StopReplicationRequest]) (*connect.Response[multipoolermanagerdata.StopReplicationResponse], error)
	// Status gets unified status that works for both PRIMARY and REPLICA poolers
	// The multipooler returns information based on what type it believes itself to be,
	// avoiding disparity between what Multiorch thinks versus actual state
	Status(context.Context, *connect.Request[multipoolermanagerdata.StatusRequest]) (*connect.Response[multipoolermanagerdata.StatusResponse], error)
	// Backup performs a backup
	Backup(context.Context, *connect.Request[multipoolermanagerdata.BackupRequest]) (*connect.Response[multipoolermanagerdata.BackupResponse], error)
	// GetBackups retrieves backup information
	GetBackups(context.Context, *connect.Request[multipoolermanagerdata.GetBackupsRequest]) (*connect.Response[multipoolermanagerdata.GetBackupsResponse], error)
	// GetBackupByJobId queries a backup by its job_id annotation.
	// Returns the backup metadata if found, or nil backup if not.
	GetBackupByJobId(context.Context, *connect.Request[multipoolermanagerdata.GetBackupByJobIdRequest]) (*connect.Response[multipoolermanagerdata.GetBackupByJobIdResponse], error)
	// ExpireBackups removes backups that exceed the configured retention policy.
	ExpireBackups(context.Context, *connect.Request[multipoolermanagerdata.ExpireBackupsRequest]) (*connect.Response[multipoolermanagerdata.ExpireBackupsResponse], error)
	// VerifyBackups runs a full-stanza pgbackrest verify (no --set). This is
	// a periodic backup-integrity check; not scoped to any single backup.
	VerifyBackups(context.Context, *connect.Request[multipoolermanagerdata.VerifyBackupsRequest]) (*connect.Response[multipoolermanagerdata.VerifyBackupsResponse], error)
	// ResignLeadership gracefully resigns this pooler from leadership.
	// Transitions the pooler to NOT_SERVING (rejecting new queries with MTF01),
	// drains write connections, publishes REQUESTING_DEMOTION, and returns the
	// WAL flush LSN at the moment writes were quiesced. The caller can then wait
	// for standbys to reach that LSN before triggering a new election.
	//
	// Only valid on a pooler that is currently the consensus leader (PRIMARY).
	// Does NOT restart postgres as standby — that happens later via the normal
	// Recruit path when multiorch picks up REQUESTING_DEMOTION.
	ResignLeadership(context.Context, *connect.Request[multipoolermanagerdata.ResignLeadershipRequest]) (*connect.Response[multipoolermanagerdata.ResignLeadershipResponse], error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts.
	// When disabled, the monitor continues to run but will not auto-restart a stopped
	// PostgreSQL instance. Used by tests and demos to prevent premature restarts during
	// controlled failovers.
	SetPostgresRestartsEnabled(context.Context, *connect.Request[multipoolermanagerdata.SetPostgresRestartsEnabledRequest]) (*connect.Response[multipoolermanagerdata.SetPostgresRestartsEnabledResponse], error)
	// ReconcileFollowers declares to the primary the full set of cohort-eligible
	// follower members it should hold per-follower physical replication slots for.
	// The primary creates any missing slot and drops managed slots for members no
	// longer in the set. It is level-triggered and declarative: the orchestrator
	// re-sends the set each cycle, so a missed event or a primary restart
	// self-heals. It creates only the physical slots (so a late-joining standby
	// can stream); it does NOT touch synchronized_standby_slots — a follower is
	// added there only once it is streaming and caught up, via the cohort path.
	ReconcileFollowers(context.Context, *connect.Request[multipoolermanagerdata.ReconcileFollowersRequest]) (*connect.Response[multipoolermanagerdata.ReconcileFollowersResponse], error)
	// ReloadConfig triggers a PostgreSQL configuration reload (SIGHUP via pgctld)
	// on this multipooler's local PostgreSQL and confirms it took effect by
	// waiting for pg_conf_load_time() to advance. The returned config_load_time
	// lets the caller verify its config-file change was re-read.
	ReloadConfig(context.Context, *connect.Request[multipoolermanagerdata.ReloadConfigRequest]) (*connect.Response[multipoolermanagerdata.ReloadConfigResponse], error)
	// ManagerHealthStream is a bidirectional health stream between orchestrator
	// and pooler.
	//
	// The orchestrator sends a start message (ManagerHealthStreamClientMessage
	// with the start field set) to open the stream, then may send poll requests
	// at any time to trigger an immediate snapshot.
	//
	// The pooler sends a full health snapshot on connection, on every state
	// change, in response to poll requests, and periodically as a heartbeat.
	// Every message is a complete snapshot — there are no incremental updates.
	//
	// The orchestrator MUST implement a staleness timeout. The recommended
	// timeout is provided in the timeout field of each snapshot. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	ManagerHealthStream(context.Context) *connect.BidiStreamForClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]
}

// NewMultipoolerManagerClient constructs a client for the multipoolermanager.MultipoolerManager
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMultipoolerManagerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MultipoolerManagerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	multipoolerManagerMethods := multipoolermanager.File_multipoolermanagerservice_proto.Services().ByName("MultipoolerManager").Methods()
	return &multipoolerManagerClient{
		waitForLSN: connect.NewClient[multipoolermanagerdata.WaitForLSNRequest, multipoolermanagerdata.WaitForLSNResponse](
			httpClient,
			baseURL+MultipoolerManagerWaitForLSNProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("WaitForLSN")),
			connect.WithClientOptions(opts...),
		),
		startReplication: connect.NewClient[multipoolermanagerdata.StartReplicationRequest, multipoolermanagerdata.StartReplicationResponse](
			httpClient,
			baseURL+MultipoolerManagerStartReplicationProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("StartReplication")),
			connect.WithClientOptions(opts...),
		),
		stopReplication: connect.NewClient[multipoolermanagerdata.StopReplicationRequest, multipoolermanagerdata.StopReplicationResponse](
			httpClient,
			baseURL+MultipoolerManagerStopReplicationProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("StopReplication")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[multipoolermanagerdata.StatusRequest, multipoolermanagerdata.StatusResponse](
			httpClient,
			baseURL+MultipoolerManagerStatusProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		backup: connect.NewClient[multipoolermanagerdata.BackupRequest, multipoolermanagerdata.BackupResponse](
			httpClient,
			baseURL+MultipoolerManagerBackupProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("Backup")),
			connect.WithClientOptions(opts...),
		),
		getBackups: connect.NewClient[multipoolermanagerdata.GetBackupsRequest, multipoolermanagerdata.GetBackupsResponse](
			httpClient,
			baseURL+MultipoolerManagerGetBackupsProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("GetBackups")),
			connect.WithClientOptions(opts...),
		),
		getBackupByJobId: connect.NewClient[multipoolermanagerdata.GetBackupByJobIdRequest, multipoolermanagerdata.GetBackupByJobIdResponse](
			httpClient,
			baseURL+MultipoolerManagerGetBackupByJobIdProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("GetBackupByJobId")),
			connect.WithClientOptions(opts...),
		),
		expireBackups: connect.NewClient[multipoolermanagerdata.ExpireBackupsRequest, multipoolermanagerdata.ExpireBackupsResponse](
			httpClient,
			baseURL+MultipoolerManagerExpireBackupsProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("ExpireBackups")),
			connect.WithClientOptions(opts...),
		),
		verifyBackups: connect.NewClient[multipoolermanagerdata.VerifyBackupsRequest, multipoolermanagerdata.VerifyBackupsResponse](
			httpClient,
			baseURL+MultipoolerManagerVerifyBackupsProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("VerifyBackups")),
			connect.WithClientOptions(opts...),
		),
		resignLeadership: connect.NewClient[multipoolermanagerdata.ResignLeadershipRequest, multipoolermanagerdata.ResignLeadershipResponse](
			httpClient,
			baseURL+MultipoolerManagerResignLeadershipProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("ResignLeadership")),
			connect.WithClientOptions(opts...),
		),
		setPostgresRestartsEnabled: connect.NewClient[multipoolermanagerdata.SetPostgresRestartsEnabledRequest, multipoolermanagerdata.SetPostgresRestartsEnabledResponse](
			httpClient,
			baseURL+MultipoolerManagerSetPostgresRestartsEnabledProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("SetPostgresRestartsEnabled")),
			connect.WithClientOptions(opts...),
		),
		reconcileFollowers: connect.NewClient[multipoolermanagerdata.ReconcileFollowersRequest, multipoolermanagerdata.ReconcileFollowersResponse](
			httpClient,
			baseURL+MultipoolerManagerReconcileFollowersProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("ReconcileFollowers")),
			connect.WithClientOptions(opts...),
		),
		reloadConfig: connect.NewClient[multipoolermanagerdata.ReloadConfigRequest, multipoolermanagerdata.ReloadConfigResponse](
			httpClient,
			baseURL+MultipoolerManagerReloadConfigProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("ReloadConfig")),
			connect.WithClientOptions(opts...),
		),
		managerHealthStream: connect.NewClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse](
			httpClient,
			baseURL+MultipoolerManagerManagerHealthStreamProcedure,
			connect.WithSchema(multipoolerManagerMethods.ByName("ManagerHealthStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// multipoolerManagerClient implements MultipoolerManagerClient.
type multipoolerManagerClient struct {
	waitForLSN                 *connect.Client[multipoolermanagerdata.WaitForLSNRequest, multipoolermanagerdata.WaitForLSNResponse]
	startReplication           *connect.Client[multipoolermanagerdata.StartReplicationRequest, multipoolermanagerdata.StartReplicationResponse]
	stopReplication            *connect.Client[multipoolermanagerdata.StopReplicationRequest, multipoolermanagerdata.StopReplicationResponse]
	status                     *connect.Client[multipoolermanagerdata.StatusRequest, multipoolermanagerdata.StatusResponse]
	backup                     *connect.Client[multipoolermanagerdata.BackupRequest, multipoolermanagerdata.BackupResponse]
	getBackups                 *connect.Client[multipoolermanagerdata.GetBackupsRequest, multipoolermanagerdata.GetBackupsResponse]
	getBackupByJobId           *connect.Client[multipoolermanagerdata.GetBackupByJobIdRequest, multipoolermanagerdata.GetBackupByJobIdResponse]
	expireBackups              *connect.Client[multipoolermanagerdata.ExpireBackupsRequest, multipoolermanagerdata.ExpireBackupsResponse]
	verifyBackups              *connect.Client[multipoolermanagerdata.VerifyBackupsRequest, multipoolermanagerdata.VerifyBackupsResponse]
	resignLeadership           *connect.Client[multipoolermanagerdata.ResignLeadershipRequest, multipoolermanagerdata.ResignLeadershipResponse]
	setPostgresRestartsEnabled *connect.Client[multipoolermanagerdata.SetPostgresRestartsEnabledRequest, multipoolermanagerdata.SetPostgresRestartsEnabledResponse]
	reconcileFollowers         *connect.Client[multipoolermanagerdata.ReconcileFollowersRequest, multipoolermanagerdata.ReconcileFollowersResponse]
	reloadConfig               *connect.Client[multipoolermanagerdata.ReloadConfigRequest, multipoolermanagerdata.ReloadConfigResponse]
	managerHealthStream        *connect.Client[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]
}

// WaitForLSN calls multipoolermanager.MultipoolerManager.WaitForLSN.
func (c *multipoolerManagerClient) WaitForLSN(ctx context.Context, req *connect.Request[multipoolermanagerdata.WaitForLSNRequest]) (*connect.Response[multipoolermanagerdata.WaitForLSNResponse], error) {
	return c.waitForLSN.CallUnary(ctx, req)
}

// StartReplication calls multipoolermanager.MultipoolerManager.StartReplication.
func (c *multipoolerManagerClient) StartReplication(ctx context.Context, req *connect.Request[multipoolermanagerdata.StartReplicationRequest]) (*connect.Response[multipoolermanagerdata.StartReplicationResponse], error) {
	return c.startReplication.CallUnary(ctx, req)
}

// StopReplication calls multipoolermanager.MultipoolerManager.StopReplication.
func (c *multipoolerManagerClient) StopReplication(ctx context.Context, req *connect.Request[multipoolermanagerdata.StopReplicationRequest]) (*connect.Response[multipoolermanagerdata.StopReplicationResponse], error) {
	return c.stopReplication.CallUnary(ctx, req)
}

// Status calls multipoolermanager.MultipoolerManager.Status.
func (c *multipoolerManagerClient) Status(ctx context.Context, req *connect.Request[multipoolermanagerdata.StatusRequest]) (*connect.Response[multipoolermanagerdata.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Backup calls multipoolermanager.MultipoolerManager.Backup.
func (c *multipoolerManagerClient) Backup(ctx context.Context, req *connect.Request[multipoolermanagerdata.BackupRequest]) (*connect.Response[multipoolermanagerdata.BackupResponse], error) {
	return c.backup.CallUnary(ctx, req)
}

// GetBackups calls multipoolermanager.MultipoolerManager.GetBackups.
func (c *multipoolerManagerClient) GetBackups(ctx context.Context, req *connect.Request[multipoolermanagerdata.GetBackupsRequest]) (*connect.Response[multipoolermanagerdata.GetBackupsResponse], error) {
	return c.getBackups.CallUnary(ctx, req)
}

// GetBackupByJobId calls multipoolermanager.MultipoolerManager.GetBackupByJobId.
func (c *multipoolerManagerClient) GetBackupByJobId(ctx context.Context, req *connect.Request[multipoolermanagerdata.GetBackupByJobIdRequest]) (*connect.Response[multipoolermanagerdata.GetBackupByJobIdResponse], error) {
	return c.getBackupByJobId.CallUnary(ctx, req)
}

// ExpireBackups calls multipoolermanager.MultipoolerManager.ExpireBackups.
func (c *multipoolerManagerClient) ExpireBackups(ctx context.Context, req *connect.Request[multipoolermanagerdata.ExpireBackupsRequest]) (*connect.Response[multipoolermanagerdata.ExpireBackupsResponse], error) {
	return c.expireBackups.CallUnary(ctx, req)
}

// VerifyBackups calls multipoolermanager.MultipoolerManager.VerifyBackups.
func (c *multipoolerManagerClient) VerifyBackups(ctx context.Context, req *connect.Request[multipoolermanagerdata.VerifyBackupsRequest]) (*connect.Response[multipoolermanagerdata.VerifyBackupsResponse], error) {
	return c.verifyBackups.CallUnary(ctx, req)
}

// ResignLeadership calls multipoolermanager.MultipoolerManager.ResignLeadership.
func (c *multipoolerManagerClient) ResignLeadership(ctx context.Context, req *connect.Request[multipoolermanagerdata.ResignLeadershipRequest]) (*connect.Response[multipoolermanagerdata.ResignLeadershipResponse], error) {
	return c.resignLeadership.CallUnary(ctx, req)
}

// SetPostgresRestartsEnabled calls
// multipoolermanager.MultipoolerManager.SetPostgresRestartsEnabled.
func (c *multipoolerManagerClient) SetPostgresRestartsEnabled(ctx context.Context, req *connect.Request[multipoolermanagerdata.SetPostgresRestartsEnabledRequest]) (*connect.Response[multipoolermanagerdata.SetPostgresRestartsEnabledResponse], error) {
	return c.setPostgresRestartsEnabled.CallUnary(ctx, req)
}

// ReconcileFollowers calls multipoolermanager.MultipoolerManager.ReconcileFollowers.
func (c *multipoolerManagerClient) ReconcileFollowers(ctx context.Context, req *connect.Request[multipoolermanagerdata.ReconcileFollowersRequest]) (*connect.Response[multipoolermanagerdata.ReconcileFollowersResponse], error) {
	return c.reconcileFollowers.CallUnary(ctx, req)
}

// ReloadConfig calls multipoolermanager.MultipoolerManager.ReloadConfig.
func (c *multipoolerManagerClient) ReloadConfig(ctx context.Context, req *connect.Request[multipoolermanagerdata.ReloadConfigRequest]) (*connect.Response[multipoolermanagerdata.ReloadConfigResponse], error) {
	return c.reloadConfig.CallUnary(ctx, req)
}

// ManagerHealthStream calls multipoolermanager.MultipoolerManager.ManagerHealthStream.
func (c *multipoolerManagerClient) ManagerHealthStream(ctx context.Context) *connect.BidiStreamForClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse] {
	return c.managerHealthStream.CallBidiStream(ctx)
}

// MultipoolerManagerHandler is an implementation of the multipoolermanager.MultipoolerManager
// service.
type MultipoolerManagerHandler interface {
	// WaitForLSN waits for PostgreSQL server to reach a specific LSN position
	WaitForLSN(context.Context, *connect.Request[multipoolermanagerdata.WaitForLSNRequest]) (*connect.Response[multipoolermanagerdata.WaitForLSNResponse], error)
	// StartReplication starts WAL replay on standby (calls pg_wal_replay_resume)
	StartReplication(context.Context, *connect.Request[multipoolermanagerdata.StartReplicationRequest]) (*connect.Response[multipoolermanagerdata.StartReplicationResponse], error)
	// StopReplication stops WAL replay on standby (calls pg_wal_replay_pause)
	StopReplication(context.Context, *connect.Request[multipoolermanagerdata.StopReplicationRequest]) (*connect.Response[multipoolermanagerdata.StopReplicationResponse], error)
	// Status gets unified status that works for both PRIMARY and REPLICA poolers
	// The multipooler returns information based on what type it believes itself to be,
	// avoiding disparity between what Multiorch thinks versus actual state
	Status(context.Context, *connect.Request[multipoolermanagerdata.StatusRequest]) (*connect.Response[multipoolermanagerdata.StatusResponse], error)
	// Backup performs a backup
	Backup(context.Context, *connect.Request[multipoolermanagerdata.BackupRequest]) (*connect.Response[multipoolermanagerdata.BackupResponse], error)
	// GetBackups retrieves backup information
	GetBackups(context.Context, *connect.Request[multipoolermanagerdata.GetBackupsRequest]) (*connect.Response[multipoolermanagerdata.GetBackupsResponse], error)
	// GetBackupByJobId queries a backup by its job_id annotation.
	// Returns the backup metadata if found, or nil backup if not.
	GetBackupByJobId(context.Context, *connect.Request[multipoolermanagerdata.GetBackupByJobIdRequest]) (*connect.Response[multipoolermanagerdata.GetBackupByJobIdResponse], error)
	// ExpireBackups removes backups that exceed the configured retention policy.
	ExpireBackups(context.Context, *connect.Request[multipoolermanagerdata.ExpireBackupsRequest]) (*connect.Response[multipoolermanagerdata.ExpireBackupsResponse], error)
	// VerifyBackups runs a full-stanza pgbackrest verify (no --set). This is
	// a periodic backup-integrity check; not scoped to any single backup.
	VerifyBackups(context.Context, *connect.Request[multipoolermanagerdata.VerifyBackupsRequest]) (*connect.Response[multipoolermanagerdata.VerifyBackupsResponse], error)
	// ResignLeadership gracefully resigns this pooler from leadership.
	// Transitions the pooler to NOT_SERVING (rejecting new queries with MTF01),
	// drains write connections, publishes REQUESTING_DEMOTION, and returns the
	// WAL flush LSN at the moment writes were quiesced. The caller can then wait
	// for standbys to reach that LSN before triggering a new election.
	//
	// Only valid on a pooler that is currently the consensus leader (PRIMARY).
	// Does NOT restart postgres as standby — that happens later via the normal
	// Recruit path when multiorch picks up REQUESTING_DEMOTION.
	ResignLeadership(context.Context, *connect.Request[multipoolermanagerdata.ResignLeadershipRequest]) (*connect.Response[multipoolermanagerdata.ResignLeadershipResponse], error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts.
	// When disabled, the monitor continues to run but will not auto-restart a stopped
	// PostgreSQL instance. Used by tests and demos to prevent premature restarts during
	// controlled failovers.
	SetPostgresRestartsEnabled(context.Context, *connect.Request[multipoolermanagerdata.SetPostgresRestartsEnabledRequest]) (*connect.Response[multipoolermanagerdata.SetPostgresRestartsEnabledResponse], error)
	// ReconcileFollowers declares to the primary the full set of cohort-eligible
	// follower members it should hold per-follower physical replication slots for.
	// The primary creates any missing slot and drops managed slots for members no
	// longer in the set. It is level-triggered and declarative: the orchestrator
	// re-sends the set each cycle, so a missed event or a primary restart
	// self-heals. It creates only the physical slots (so a late-joining standby
	// can stream); it does NOT touch synchronized_standby_slots — a follower is
	// added there only once it is streaming and caught up, via the cohort path.
	ReconcileFollowers(context.Context, *connect.Request[multipoolermanagerdata.ReconcileFollowersRequest]) (*connect.Response[multipoolermanagerdata.ReconcileFollowersResponse], error)
	// ReloadConfig triggers a PostgreSQL configuration reload (SIGHUP via pgctld)
	// on this multipooler's local PostgreSQL and confirms it took effect by
	// waiting for pg_conf_load_time() to advance. The returned config_load_time
	// lets the caller verify its config-file change was re-read.
	ReloadConfig(context.Context, *connect.Request[multipoolermanagerdata.ReloadConfigRequest]) (*connect.Response[multipoolermanagerdata.ReloadConfigResponse], error)
	// ManagerHealthStream is a bidirectional health stream between orchestrator
	// and pooler.
	//
	// The orchestrator sends a start message (ManagerHealthStreamClientMessage
	// with the start field set) to open the stream, then may send poll requests
	// at any time to trigger an immediate snapshot.
	//
	// The pooler sends a full health snapshot on connection, on every state
	// change, in response to poll requests, and periodically as a heartbeat.
	// Every message is a complete snapshot — there are no incremental updates.
	//
	// The orchestrator MUST implement a staleness timeout. The recommended
	// timeout is provided in the timeout field of each snapshot. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	ManagerHealthStream(context.Context, *connect.BidiStream[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]) error
}

// NewMultipoolerManagerHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMultipoolerManagerHandler(svc MultipoolerManagerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	multipoolerManagerMethods := multipoolermanager.File_multipoolermanagerservice_proto.Services().ByName("MultipoolerManager").Methods()
	multipoolerManagerWaitForLSNHandler := connect.NewUnaryHandler(
		MultipoolerManagerWaitForLSNProcedure,
		svc.WaitForLSN,
		connect.WithSchema(multipoolerManagerMethods.ByName("WaitForLSN")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerStartReplicationHandler := connect.NewUnaryHandler(
		MultipoolerManagerStartReplicationProcedure,
		svc.StartReplication,
		connect.WithSchema(multipoolerManagerMethods.ByName("StartReplication")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerStopReplicationHandler := connect.NewUnaryHandler(
		MultipoolerManagerStopReplicationProcedure,
		svc.StopReplication,
		connect.WithSchema(multipoolerManagerMethods.ByName("StopReplication")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerStatusHandler := connect.NewUnaryHandler(
		MultipoolerManagerStatusProcedure,
		svc.Status,
		connect.WithSchema(multipoolerManagerMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerBackupHandler := connect.NewUnaryHandler(
		MultipoolerManagerBackupProcedure,
		svc.Backup,
		connect.WithSchema(multipoolerManagerMethods.ByName("Backup")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerGetBackupsHandler := connect.NewUnaryHandler(
		MultipoolerManagerGetBackupsProcedure,
		svc.GetBackups,
		connect.WithSchema(multipoolerManagerMethods.ByName("GetBackups")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerGetBackupByJobIdHandler := connect.NewUnaryHandler(
		MultipoolerManagerGetBackupByJobIdProcedure,
		svc.GetBackupByJobId,
		connect.WithSchema(multipoolerManagerMethods.ByName("GetBackupByJobId")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerExpireBackupsHandler := connect.NewUnaryHandler(
		MultipoolerManagerExpireBackupsProcedure,
		svc.ExpireBackups,
		connect.WithSchema(multipoolerManagerMethods.ByName("ExpireBackups")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerVerifyBackupsHandler := connect.NewUnaryHandler(
		MultipoolerManagerVerifyBackupsProcedure,
		svc.VerifyBackups,
		connect.WithSchema(multipoolerManagerMethods.ByName("VerifyBackups")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerResignLeadershipHandler := connect.NewUnaryHandler(
		MultipoolerManagerResignLeadershipProcedure,
		svc.ResignLeadership,
		connect.WithSchema(multipoolerManagerMethods.ByName("ResignLeadership")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerSetPostgresRestartsEnabledHandler := connect.NewUnaryHandler(
		MultipoolerManagerSetPostgresRestartsEnabledProcedure,
		svc.SetPostgresRestartsEnabled,
		connect.WithSchema(multipoolerManagerMethods.ByName("SetPostgresRestartsEnabled")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerReconcileFollowersHandler := connect.NewUnaryHandler(
		MultipoolerManagerReconcileFollowersProcedure,
		svc.ReconcileFollowers,
		connect.WithSchema(multipoolerManagerMethods.ByName("ReconcileFollowers")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerReloadConfigHandler := connect.NewUnaryHandler(
		MultipoolerManagerReloadConfigProcedure,
		svc.ReloadConfig,
		connect.WithSchema(multipoolerManagerMethods.ByName("ReloadConfig")),
		connect.WithHandlerOptions(opts...),
	)
	multipoolerManagerManagerHealthStreamHandler := connect.NewBidiStreamHandler(
		MultipoolerManagerManagerHealthStreamProcedure,
		svc.ManagerHealthStream,
		connect.WithSchema(multipoolerManagerMethods.ByName("ManagerHealthStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/multipoolermanager.MultipoolerManager/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MultipoolerManagerWaitForLSNProcedure:
			multipoolerManagerWaitForLSNHandler.ServeHTTP(w, r)
		case MultipoolerManagerStartReplicationProcedure:
			multipoolerManagerStartReplicationHandler.ServeHTTP(w, r)
		case MultipoolerManagerStopReplicationProcedure:
			multipoolerManagerStopReplicationHandler.ServeHTTP(w, r)
		case MultipoolerManagerStatusProcedure:
			multipoolerManagerStatusHandler.ServeHTTP(w, r)
		case MultipoolerManagerBackupProcedure:
			multipoolerManagerBackupHandler.ServeHTTP(w, r)
		case MultipoolerManagerGetBackupsProcedure:
			multipoolerManagerGetBackupsHandler.ServeHTTP(w, r)
		case MultipoolerManagerGetBackupByJobIdProcedure:
			multipoolerManagerGetBackupByJobIdHandler.ServeHTTP(w, r)
		case MultipoolerManagerExpireBackupsProcedure:
			multipoolerManagerExpireBackupsHandler.ServeHTTP(w, r)
		case MultipoolerManagerVerifyBackupsProcedure:
			multipoolerManagerVerifyBackupsHandler.ServeHTTP(w, r)
		case MultipoolerManagerResignLeadershipProcedure:
			multipoolerManagerResignLeadershipHandler.ServeHTTP(w, r)
		case MultipoolerManagerSetPostgresRestartsEnabledProcedure:
			multipoolerManagerSetPostgresRestartsEnabledHandler.ServeHTTP(w, r)
		case MultipoolerManagerReconcileFollowersProcedure:
			multipoolerManagerReconcileFollowersHandler.ServeHTTP(w, r)
		case MultipoolerManagerReloadConfigProcedure:
			multipoolerManagerReloadConfigHandler.ServeHTTP(w, r)
		case MultipoolerManagerManagerHealthStreamProcedure:
			multipoolerManagerManagerHealthStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMultipoolerManagerHandler returns CodeUnimplemented from all methods.
type UnimplementedMultipoolerManagerHandler struct{}

func (UnimplementedMultipoolerManagerHandler) WaitForLSN(context.Context, *connect.Request[multipoolermanagerdata.WaitForLSNRequest]) (*connect.Response[multipoolermanagerdata.WaitForLSNResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.WaitForLSN is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) StartReplication(context.Context, *connect.Request[multipoolermanagerdata.StartReplicationRequest]) (*connect.Response[multipoolermanagerdata.StartReplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.StartReplication is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) StopReplication(context.Context, *connect.Request[multipoolermanagerdata.StopReplicationRequest]) (*connect.Response[multipoolermanagerdata.StopReplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.StopReplication is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) Status(context.Context, *connect.Request[multipoolermanagerdata.StatusRequest]) (*connect.Response[multipoolermanagerdata.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.Status is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) Backup(context.Context, *connect.Request[multipoolermanagerdata.BackupRequest]) (*connect.Response[multipoolermanagerdata.BackupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.Backup is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) GetBackups(context.Context, *connect.Request[multipoolermanagerdata.GetBackupsRequest]) (*connect.Response[multipoolermanagerdata.GetBackupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.GetBackups is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) GetBackupByJobId(context.Context, *connect.Request[multipoolermanagerdata.GetBackupByJobIdRequest]) (*connect.Response[multipoolermanagerdata.GetBackupByJobIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.GetBackupByJobId is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) ExpireBackups(context.Context, *connect.Request[multipoolermanagerdata.ExpireBackupsRequest]) (*connect.Response[multipoolermanagerdata.ExpireBackupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.ExpireBackups is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) VerifyBackups(context.Context, *connect.Request[multipoolermanagerdata.VerifyBackupsRequest]) (*connect.Response[multipoolermanagerdata.VerifyBackupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.VerifyBackups is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) ResignLeadership(context.Context, *connect.Request[multipoolermanagerdata.ResignLeadershipRequest]) (*connect.Response[multipoolermanagerdata.ResignLeadershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.ResignLeadership is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) SetPostgresRestartsEnabled(context.Context, *connect.Request[multipoolermanagerdata.SetPostgresRestartsEnabledRequest]) (*connect.Response[multipoolermanagerdata.SetPostgresRestartsEnabledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.SetPostgresRestartsEnabled is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) ReconcileFollowers(context.Context, *connect.Request[multipoolermanagerdata.ReconcileFollowersRequest]) (*connect.Response[multipoolermanagerdata.ReconcileFollowersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.ReconcileFollowers is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) ReloadConfig(context.Context, *connect.Request[multipoolermanagerdata.ReloadConfigRequest]) (*connect.Response[multipoolermanagerdata.ReloadConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.ReloadConfig is not implemented"))
}

func (UnimplementedMultipoolerManagerHandler) ManagerHealthStream(context.Context, *connect.BidiStream[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("multipoolermanager.MultipoolerManager.ManagerHealthStream is not implemented"))
}
