// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data types for management / introspection RPCs on the multigateway —
// snapshots of the per-fingerprint query registry and the prepared-statement
// consolidator. Consumed by multiadmin to render the per-gateway debug pages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: multigatewaymanagerdata.proto

package multigatewaymanagerdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryStatSnapshot is a single row in the per-fingerprint query registry,
// extended with rolling trend samples for sparkline rendering.
type QueryStatSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fingerprint is the xxh3-64 hex of the normalized SQL, or one of the
	// synthetic bucket labels ("__utility__", "__other__").
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// normalized_sql is the parameterized SQL for this fingerprint, truncated
	// to the registry's MaxSQLLength.
	NormalizedSql string `protobuf:"bytes,2,opt,name=normalized_sql,json=normalizedSql,proto3" json:"normalized_sql,omitempty"`
	// calls is the cumulative number of executions tracked since the registry
	// admitted this fingerprint.
	Calls uint64 `protobuf:"varint,3,opt,name=calls,proto3" json:"calls,omitempty"`
	// errors is the cumulative number of failed executions.
	Errors uint64 `protobuf:"varint,4,opt,name=errors,proto3" json:"errors,omitempty"`
	// total_duration is the cumulative wall-clock time spent executing this
	// fingerprint's queries.
	TotalDuration *durationpb.Duration `protobuf:"bytes,5,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	// average_duration is total_duration / calls.
	AverageDuration *durationpb.Duration `protobuf:"bytes,6,opt,name=average_duration,json=averageDuration,proto3" json:"average_duration,omitempty"`
	// min_duration is the smallest observed execution duration.
	MinDuration *durationpb.Duration `protobuf:"bytes,7,opt,name=min_duration,json=minDuration,proto3" json:"min_duration,omitempty"`
	// max_duration is the largest observed execution duration.
	MaxDuration *durationpb.Duration `protobuf:"bytes,8,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	// p50_duration is the median execution duration computed from the
	// per-fingerprint histogram.
	P50Duration *durationpb.Duration `protobuf:"bytes,9,opt,name=p50_duration,json=p50Duration,proto3" json:"p50_duration,omitempty"`
	// p99_duration is the 99th-percentile execution duration computed from the
	// per-fingerprint histogram.
	P99Duration *durationpb.Duration `protobuf:"bytes,10,opt,name=p99_duration,json=p99Duration,proto3" json:"p99_duration,omitempty"`
	// total_rows is the cumulative row count returned across all executions.
	TotalRows uint64 `protobuf:"varint,11,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	// last_seen is the timestamp of the most recent execution.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// sample_interval is the cadence at which the trend slices below were
	// captured. Empty when trend sampling is disabled.
	SampleInterval *durationpb.Duration `protobuf:"bytes,13,opt,name=sample_interval,json=sampleInterval,proto3" json:"sample_interval,omitempty"`
	// call_rate_trend holds calls/s samples, oldest first.
	CallRateTrends []float64 `protobuf:"fixed64,14,rep,packed,name=call_rate_trends,json=callRateTrends,proto3" json:"call_rate_trends,omitempty"`
	// total_time_ms_trend holds duration-ms-per-second-of-wall-clock samples.
	TotalTimeMsTrends []float64 `protobuf:"fixed64,15,rep,packed,name=total_time_ms_trends,json=totalTimeMsTrends,proto3" json:"total_time_ms_trends,omitempty"`
	// p50_ms_trend holds p50 latency (ms) samples over time.
	P50MsTrends []float64 `protobuf:"fixed64,16,rep,packed,name=p50_ms_trends,json=p50MsTrends,proto3" json:"p50_ms_trends,omitempty"`
	// p99_ms_trend holds p99 latency (ms) samples over time.
	P99MsTrends []float64 `protobuf:"fixed64,17,rep,packed,name=p99_ms_trends,json=p99MsTrends,proto3" json:"p99_ms_trends,omitempty"`
	// rows_rate_trend holds rows-per-second samples over time.
	RowsRateTrends []float64 `protobuf:"fixed64,18,rep,packed,name=rows_rate_trends,json=rowsRateTrends,proto3" json:"rows_rate_trends,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryStatSnapshot) Reset() {
	*x = QueryStatSnapshot{}
	mi := &file_multigatewaymanagerdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatSnapshot) ProtoMessage() {}

func (x *QueryStatSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatSnapshot.ProtoReflect.Descriptor instead.
func (*QueryStatSnapshot) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerdata_proto_rawDescGZIP(), []int{0}
}

func (x *QueryStatSnapshot) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *QueryStatSnapshot) GetNormalizedSql() string {
	if x != nil {
		return x.NormalizedSql
	}
	return ""
}

func (x *QueryStatSnapshot) GetCalls() uint64 {
	if x != nil {
		return x.Calls
	}
	return 0
}

func (x *QueryStatSnapshot) GetErrors() uint64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *QueryStatSnapshot) GetTotalDuration() *durationpb.Duration {
	if x != nil {
		return x.TotalDuration
	}
	return nil
}

func (x *QueryStatSnapshot) GetAverageDuration() *durationpb.Duration {
	if x != nil {
		return x.AverageDuration
	}
	return nil
}

func (x *QueryStatSnapshot) GetMinDuration() *durationpb.Duration {
	if x != nil {
		return x.MinDuration
	}
	return nil
}

func (x *QueryStatSnapshot) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

func (x *QueryStatSnapshot) GetP50Duration() *durationpb.Duration {
	if x != nil {
		return x.P50Duration
	}
	return nil
}

func (x *QueryStatSnapshot) GetP99Duration() *durationpb.Duration {
	if x != nil {
		return x.P99Duration
	}
	return nil
}

func (x *QueryStatSnapshot) GetTotalRows() uint64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *QueryStatSnapshot) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *QueryStatSnapshot) GetSampleInterval() *durationpb.Duration {
	if x != nil {
		return x.SampleInterval
	}
	return nil
}

func (x *QueryStatSnapshot) GetCallRateTrends() []float64 {
	if x != nil {
		return x.CallRateTrends
	}
	return nil
}

func (x *QueryStatSnapshot) GetTotalTimeMsTrends() []float64 {
	if x != nil {
		return x.TotalTimeMsTrends
	}
	return nil
}

func (x *QueryStatSnapshot) GetP50MsTrends() []float64 {
	if x != nil {
		return x.P50MsTrends
	}
	return nil
}

func (x *QueryStatSnapshot) GetP99MsTrends() []float64 {
	if x != nil {
		return x.P99MsTrends
	}
	return nil
}

func (x *QueryStatSnapshot) GetRowsRateTrends() []float64 {
	if x != nil {
		return x.RowsRateTrends
	}
	return nil
}

// QueryRegistrySnapshot is the full registry response, suitable for rendering
// a per-gateway "Top Queries" page.
type QueryRegistrySnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// queries is the set of tracked query fingerprints with their stats and trends.
	Queries []*QueryStatSnapshot `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	// tracked_fingerprints is the total count currently held in the registry,
	// independent of any limit applied to the queries field.
	TrackedFingerprints uint32 `protobuf:"varint,2,opt,name=tracked_fingerprints,json=trackedFingerprints,proto3" json:"tracked_fingerprints,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryRegistrySnapshot) Reset() {
	*x = QueryRegistrySnapshot{}
	mi := &file_multigatewaymanagerdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRegistrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRegistrySnapshot) ProtoMessage() {}

func (x *QueryRegistrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRegistrySnapshot.ProtoReflect.Descriptor instead.
func (*QueryRegistrySnapshot) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerdata_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRegistrySnapshot) GetQueries() []*QueryStatSnapshot {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *QueryRegistrySnapshot) GetTrackedFingerprints() uint32 {
	if x != nil {
		return x.TrackedFingerprints
	}
	return 0
}

// ConsolidatorPreparedStatement is one entry in the per-prepared-statement
// consolidator stats list.
type ConsolidatorPreparedStatement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the prepared-statement name as declared by the client.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// query is the original SQL of the prepared statement.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// refs is the number of distinct connections currently sharing this entry.
	Refs          uint32 `protobuf:"varint,3,opt,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidatorPreparedStatement) Reset() {
	*x = ConsolidatorPreparedStatement{}
	mi := &file_multigatewaymanagerdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidatorPreparedStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidatorPreparedStatement) ProtoMessage() {}

func (x *ConsolidatorPreparedStatement) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidatorPreparedStatement.ProtoReflect.Descriptor instead.
func (*ConsolidatorPreparedStatement) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerdata_proto_rawDescGZIP(), []int{2}
}

func (x *ConsolidatorPreparedStatement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsolidatorPreparedStatement) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ConsolidatorPreparedStatement) GetRefs() uint32 {
	if x != nil {
		return x.Refs
	}
	return 0
}

// ConsolidatorStats is a snapshot of the prepared-statement consolidator,
// suitable for rendering a per-gateway diagnostic page.
type ConsolidatorStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique_statements is the number of distinct prepared statements held.
	UniqueStatements uint32 `protobuf:"varint,1,opt,name=unique_statements,json=uniqueStatements,proto3" json:"unique_statements,omitempty"`
	// total_references is the sum of refs across all unique statements — i.e.
	// the number of (connection, prepared-statement) pairs being shared.
	TotalReferences uint32 `protobuf:"varint,2,opt,name=total_references,json=totalReferences,proto3" json:"total_references,omitempty"`
	// connection_count is the number of distinct client connections currently
	// sharing one or more prepared statements.
	ConnectionCount uint32 `protobuf:"varint,3,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	// prepared_statements is one entry per unique prepared-statement, ordered
	// by ref count (most-shared first).
	PreparedStatements []*ConsolidatorPreparedStatement `protobuf:"bytes,4,rep,name=prepared_statements,json=preparedStatements,proto3" json:"prepared_statements,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsolidatorStats) Reset() {
	*x = ConsolidatorStats{}
	mi := &file_multigatewaymanagerdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidatorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidatorStats) ProtoMessage() {}

func (x *ConsolidatorStats) ProtoReflect() protoreflect.Message {
	mi := &file_multigatewaymanagerdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidatorStats.ProtoReflect.Descriptor instead.
func (*ConsolidatorStats) Descriptor() ([]byte, []int) {
	return file_multigatewaymanagerdata_proto_rawDescGZIP(), []int{3}
}

func (x *ConsolidatorStats) GetUniqueStatements() uint32 {
	if x != nil {
		return x.UniqueStatements
	}
	return 0
}

func (x *ConsolidatorStats) GetTotalReferences() uint32 {
	if x != nil {
		return x.TotalReferences
	}
	return 0
}

func (x *ConsolidatorStats) GetConnectionCount() uint32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *ConsolidatorStats) GetPreparedStatements() []*ConsolidatorPreparedStatement {
	if x != nil {
		return x.PreparedStatements
	}
	return nil
}

var File_multigatewaymanagerdata_proto protoreflect.FileDescriptor

const file_multigatewaymanagerdata_proto_rawDesc = "" +
	"\n" +
	"\x1dmultigatewaymanagerdata.proto\x12\x17multigatewaymanagerdata\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x06\n" +
	"\x11QueryStatSnapshot\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12%\n" +
	"\x0enormalized_sql\x18\x02 \x01(\tR\rnormalizedSql\x12\x14\n" +
	"\x05calls\x18\x03 \x01(\x04R\x05calls\x12\x16\n" +
	"\x06errors\x18\x04 \x01(\x04R\x06errors\x12@\n" +
	"\x0etotal_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\rtotalDuration\x12D\n" +
	"\x10average_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x0faverageDuration\x12<\n" +
	"\fmin_duration\x18\a \x01(\v2\x19.google.protobuf.DurationR\vminDuration\x12<\n" +
	"\fmax_duration\x18\b \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\x12<\n" +
	"\fp50_duration\x18\t \x01(\v2\x19.google.protobuf.DurationR\vp50Duration\x12<\n" +
	"\fp99_duration\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\vp99Duration\x12\x1d\n" +
	"\n" +
	"total_rows\x18\v \x01(\x04R\ttotalRows\x127\n" +
	"\tlast_seen\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12B\n" +
	"\x0fsample_interval\x18\r \x01(\v2\x19.google.protobuf.DurationR\x0esampleInterval\x12(\n" +
	"\x10call_rate_trends\x18\x0e \x03(\x01R\x0ecallRateTrends\x12/\n" +
	"\x14total_time_ms_trends\x18\x0f \x03(\x01R\x11totalTimeMsTrends\x12\"\n" +
	"\rp50_ms_trends\x18\x10 \x03(\x01R\vp50MsTrends\x12\"\n" +
	"\rp99_ms_trends\x18\x11 \x03(\x01R\vp99MsTrends\x12(\n" +
	"\x10rows_rate_trends\x18\x12 \x03(\x01R\x0erowsRateTrends\"\x90\x01\n" +
	"\x15QueryRegistrySnapshot\x12D\n" +
	"\aqueries\x18\x01 \x03(\v2*.multigatewaymanagerdata.QueryStatSnapshotR\aqueries\x121\n" +
	"\x14tracked_fingerprints\x18\x02 \x01(\rR\x13trackedFingerprints\"]\n" +
	"\x1dConsolidatorPreparedStatement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04refs\x18\x03 \x01(\rR\x04refs\"\xff\x01\n" +
	"\x11ConsolidatorStats\x12+\n" +
	"\x11unique_statements\x18\x01 \x01(\rR\x10uniqueStatements\x12)\n" +
	"\x10total_references\x18\x02 \x01(\rR\x0ftotalReferences\x12)\n" +
	"\x10connection_count\x18\x03 \x01(\rR\x0fconnectionCount\x12g\n" +
	"\x13prepared_statements\x18\x04 \x03(\v26.multigatewaymanagerdata.ConsolidatorPreparedStatementR\x12preparedStatementsB>Z<github.com/multigres/multigres/go/pb/multigatewaymanagerdatab\x06proto3"

var (
	file_multigatewaymanagerdata_proto_rawDescOnce sync.Once
	file_multigatewaymanagerdata_proto_rawDescData []byte
)

func file_multigatewaymanagerdata_proto_rawDescGZIP() []byte {
	file_multigatewaymanagerdata_proto_rawDescOnce.Do(func() {
		file_multigatewaymanagerdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multigatewaymanagerdata_proto_rawDesc), len(file_multigatewaymanagerdata_proto_rawDesc)))
	})
	return file_multigatewaymanagerdata_proto_rawDescData
}

var file_multigatewaymanagerdata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_multigatewaymanagerdata_proto_goTypes = []any{
	(*QueryStatSnapshot)(nil),             // 0: multigatewaymanagerdata.QueryStatSnapshot
	(*QueryRegistrySnapshot)(nil),         // 1: multigatewaymanagerdata.QueryRegistrySnapshot
	(*ConsolidatorPreparedStatement)(nil), // 2: multigatewaymanagerdata.ConsolidatorPreparedStatement
	(*ConsolidatorStats)(nil),             // 3: multigatewaymanagerdata.ConsolidatorStats
	(*durationpb.Duration)(nil),           // 4: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
}
var file_multigatewaymanagerdata_proto_depIdxs = []int32{
	4,  // 0: multigatewaymanagerdata.QueryStatSnapshot.total_duration:type_name -> google.protobuf.Duration
	4,  // 1: multigatewaymanagerdata.QueryStatSnapshot.average_duration:type_name -> google.protobuf.Duration
	4,  // 2: multigatewaymanagerdata.QueryStatSnapshot.min_duration:type_name -> google.protobuf.Duration
	4,  // 3: multigatewaymanagerdata.QueryStatSnapshot.max_duration:type_name -> google.protobuf.Duration
	4,  // 4: multigatewaymanagerdata.QueryStatSnapshot.p50_duration:type_name -> google.protobuf.Duration
	4,  // 5: multigatewaymanagerdata.QueryStatSnapshot.p99_duration:type_name -> google.protobuf.Duration
	5,  // 6: multigatewaymanagerdata.QueryStatSnapshot.last_seen:type_name -> google.protobuf.Timestamp
	4,  // 7: multigatewaymanagerdata.QueryStatSnapshot.sample_interval:type_name -> google.protobuf.Duration
	0,  // 8: multigatewaymanagerdata.QueryRegistrySnapshot.queries:type_name -> multigatewaymanagerdata.QueryStatSnapshot
	2,  // 9: multigatewaymanagerdata.ConsolidatorStats.prepared_statements:type_name -> multigatewaymanagerdata.ConsolidatorPreparedStatement
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_multigatewaymanagerdata_proto_init() }
func file_multigatewaymanagerdata_proto_init() {
	if File_multigatewaymanagerdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multigatewaymanagerdata_proto_rawDesc), len(file_multigatewaymanagerdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multigatewaymanagerdata_proto_goTypes,
		DependencyIndexes: file_multigatewaymanagerdata_proto_depIdxs,
		MessageInfos:      file_multigatewaymanagerdata_proto_msgTypes,
	}.Build()
	File_multigatewaymanagerdata_proto = out.File
	file_multigatewaymanagerdata_proto_goTypes = nil
	file_multigatewaymanagerdata_proto_depIdxs = nil
}
